Repository GeoNode/geonode, pull requests merged in 2019-11, with the labels that each got.

#5164 [Fixes #4661] Replace Layer functionality incomplete/broken
  geonode/geoserver/tests/__init__.py
  geonode/geoserver/tests/test_helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/upload.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/tests/integration.py
  geonode/upload/utils.py
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5173 [Fixes #5172] Add docs for thesaurus and fix management command
  docs/admin/index.rst
  docs/admin/thesaurus/img/thesaurus_filter.png
  docs/admin/thesaurus/index.rst
  geonode/base/management/commands/load_thesaurus.py
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5175 Backport 5164 to 2.10.1
  geonode/geoserver/tests/__init__.py
  geonode/geoserver/tests/test_helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/upload.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/tests/integration.py
  geonode/upload/utils.py
Labels: cla-signed

#5176 Backport 5164 to 2.10.x
  geonode/geoserver/tests/__init__.py
  geonode/geoserver/tests/test_helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/upload.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/tests/integration.py
  geonode/upload/utils.py
Labels: cla-signed

#5211 [Fixes #5209] MapStore client critical slow-down with latest Chrome updates
  requirements.txt
Labels: backport 2.10.1, backport 2.10.x, cla-signed, dependencies

#5213 Backport 5211 to 2.10.1
  requirements.txt
Labels: cla-signed

#5218 Revert "Bump amqp from 2.5.1 to 2.5.2"
  requirements.txt
Labels: cla-signed

#5217 [Fixes #5214] Fix regression on monitoring countries endpoint
  geonode/monitoring/collector.py
  geonode/monitoring/tests/integration.py
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5198 [Fixes #5197] Admin Panel add Menu Item does not work for UTF-8 Characters
  geonode/base/models.py
  geonode/base/tests.py
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5240 [Backport to 2.10.1][Fixes #5223] Layer details broken if no store identified
  codecov.yml
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/proxy/tests.py
  geonode/version.py
  pavement.py
  requirements.txt
Labels: cla-signed

#5241 [Backport 2.10.x][Fixes #5223] Layer details broken if no store identified
  codecov.yml
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/proxy/tests.py
  geonode/version.py
  pavement.py
  requirements.txt
Labels: cla-signed

#5259 [Fixes #5258] Duplicate Headline in /about
  geonode/templates/about.html
Labels: backport 2.10.x, cla-signed

#5265 [Fixes #5264] Use GeoServer 2.15.3
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose.async.yml
  docker-compose.yml
  docs/install/core/index.rst
  docs/install/project/index.rst
  scripts/spcgeonode/geoserver/Dockerfile
Labels: backport 2.10.x, cla-signed

#5270 [Backport 2.10.x] Update django-modeltranslation requirement
  requirements.txt
Labels: cla-signed

#5269 [Fixes #4635] Encoding issues when uploading layers using a shapefile
  geonode/upload/upload.py
  geonode/upload/views.py
  requirements.txt
Labels: backport 2.10.x, cla-signed

#5273 [Fixes #5272] Line layer uploaded to GeoNode is rendered as point layer
  geonode/geoserver/upload.py
Labels: backport 2.10.x, cla-signed

#5277 Fixes #5260 Failed to get the LE certificates with SPC
  scripts/spcgeonode/letsencrypt/Dockerfile
  scripts/spcgeonode/letsencrypt/docker-entrypoint.sh
Labels: backport 2.10.x, cla-signed

#5284 [Fixes #5283] UnicodeEncodeError when trying to delete a Layer on a GeoNode instance with action streams containing exotic characters.
  geonode/geoserver/helpers.py
  geonode/groups/models.py
  geonode/monitoring/models.py
  requirements.txt
Labels: backport 2.10.x, cla-signed, dependencies

#5292 Added kikislater to contributors
  .clabot
Labels: cla-signed

#5293 [Fixes #5028] Maps migrated from GeoExplorer don't display the correct initial extent in MapStore
  geonode/local_settings.py.geoserver.sample
  geonode/static/mapstorestyle/img/bing_aerial_w_labels.png
  geonode/static/mapstorestyle/img/bing_canvas_dark.png
  geonode/static/mapstorestyle/img/bing_road_on_demand.png
  requirements.txt
Labels: backport 2.10.x, cla-signed, dependencies

#5299 Bump geoserver-restconfig from 1.0.4 to 1.0.5
  geonode/geoserver/createlayer/utils.py
  geonode/geoserver/helpers.py
  geonode/layers/views.py
  geonode/monitoring/tests/integration.py
  geonode/services/serviceprocessors/base.py
  geonode/services/tests.py
  geonode/services/utils.py
  geonode/upload/tests/integration.py
  requirements.txt
Labels: backport 2.10.x, cla-signed, dependencies

#5307 Fixes: #5306 Add new contributors to cla
  .clabot
Labels: backport 2.10.x, cla-signed

#5305 [Fixes #5304] Add more themes customizations colors
  geonode/templates/base.html
  geonode/themes/admin.py
  geonode/themes/migrations/0008_auto_20191122_1714.py
  geonode/themes/models.py
  geonode/themes/tests.py
Labels: backport 2.10.x, cla-signed

#5312 Fixes #5311 user_messages div does not completely disappear
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
Labels: backport 2.10.x, cla-signed

#5313 [Issue #4276] Bump Celery to 4.3.0
  geonode/maps/qgis_server_views.py
  geonode/qgis_server/helpers.py
  geonode/qgis_server/signals.py
  geonode/qgis_server/tasks/update.py
  geonode/qgis_server/tests/test_helpers.py
  geonode/qgis_server/views.py
  requirements.txt
Labels: cla-signed, dependencies

#5314 [Issue #4276] Upgrade boto to boto3
  geonode/settings.py
  package/debian/control
  requirements.txt
  scripts/cloud/README.rst
  scripts/cloud/ec2.py
  scripts/misc/upload.py
Labels: cla-signed, dependencies

#5315 [Issue #4276] Updated to import unittest.mock over legacy mock package
  geonode/people/test_adapters.py
  geonode/proxy/tests.py
  geonode/services/tests.py
  geonode/upload/tests/test_upload_preprocessing.py
Labels: cla-signed, dependencies

#5317 [Fixes: #5263] Styling issues at welcome page
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/leaflet-plugins.min.js
Labels: backport 2.10.x, cla-signed

#5319 [Fixes #5318] Wrong sections disposition on Welcome page
  geonode/catalogue/templates/geonode_metadata_full.html
  geonode/client/static/geonode/css/geoexplorer/map_geoexplorer.css
  geonode/client/templates/geoext/ext_header.html
  geonode/static/geonode/css/ux-all.css
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/assets/cancel.png
  geonode/static/lib/css/assets/cancel.svg
  geonode/static/lib/css/assets/cancel_@2X.png
  geonode/static/lib/css/assets/check.png
  geonode/static/lib/css/assets/check.svg
  geonode/static/lib/css/assets/check_@2X.png
  geonode/static/lib/css/assets/focus.png
  geonode/static/lib/css/assets/focus.svg
  geonode/static/lib/css/assets/focus_@2X.png
  geonode/static/lib/css/assets/leaflet-measure.png
  geonode/static/lib/css/assets/rulers.png
  geonode/static/lib/css/assets/rulers.svg
  geonode/static/lib/css/assets/rulers_@2X.png
  geonode/static/lib/css/assets/start.png
  geonode/static/lib/css/assets/start.svg
  geonode/static/lib/css/assets/start_@2X.png
  geonode/static/lib/css/assets/trash.png
  geonode/static/lib/css/assets/trash.svg
  geonode/static/lib/css/assets/trash_@2X.png
  geonode/static/lib/css/fonts/raty.eot
  geonode/static/lib/css/fonts/raty.svg
  geonode/static/lib/css/fonts/raty.ttf
  geonode/static/lib/css/fonts/raty.woff
  geonode/static/lib/css/fullscreen.png
  geonode/static/lib/css/fullscreen@2x.png
  geonode/static/lib/css/jquery-ui.theme.css
  geonode/static/lib/fonts/glyphicons-halflings-regular.eot
  geonode/static/lib/fonts/glyphicons-halflings-regular.svg
  geonode/static/lib/fonts/glyphicons-halflings-regular.ttf
  geonode/static/lib/fonts/glyphicons-halflings-regular.woff
  geonode/static/lib/fonts/glyphicons-halflings-regular.woff2
  geonode/templates/500.html
  geonode/templates/base.html
  geonode/templates/index.html
  geonode/templates/pinax/notifications/request_download_resourcebase/full.txt
  geonode/themes/admin.py
  geonode/themes/migrations/0009_geonodethemecustomization_footer_bg_color.py
  geonode/themes/models.py
Labels: backport 2.10.x, cla-signed

#5324 [Fixes #5316] Removed simplejson dependency
  geonode/base/management/commands/backup.py
  geonode/base/management/commands/helpers.py
  geonode/base/management/commands/lib/gn20_to_24.py
  geonode/base/management/commands/lib/gn24_to_24.py
  geonode/base/management/commands/restore.py
  geonode/client/hooksets.py
  geonode/layers/forms.py
  geonode/layers/views.py
  geonode/maps/management/commands/changemaplayertitle.py
  geonode/maps/models.py
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/middleware.py
  geonode/security/utils.py
  geonode/security/views.py
  geonode/utils.py
  geonode/views.py
  package/debian/control
  requirements.txt
  scripts/backup-restore/helpers.py
Labels: backport 2.10.x, cla-signed, dependencies

#5326 [Fixes #5325] Improve Featured Datasets thumbs layout on main page
  geonode/templates/index.html
Labels: backport 2.10.x, cla-signed

#5334 [Issue #4276] Upgrade api for Python 2.7/3 compatibility
  geonode/api/api.py
  geonode/api/resourcebase_api.py
  geonode/api/tests.py
Labels: cla-signed, python-3

#5331 [Fixes #5330][Performance] Avoid making WMS GetCapa request unless strictly necessary
  geonode/layers/views.py
  geonode/maps/views.py
Labels: backport 2.10.x, cla-signed, performance

#5332 [Fixes #5329] Shapefiles upload fails with files having name with spaces
  geonode/tests/data/UNESCO Global Geoparks.zip
  geonode/tests/data/UNESCO Global Geoparks/UNESCO Global Geoparks.dbf
  geonode/tests/data/UNESCO Global Geoparks/UNESCO Global Geoparks.prj
  geonode/tests/data/UNESCO Global Geoparks/UNESCO Global Geoparks.qpj
  geonode/tests/data/UNESCO Global Geoparks/UNESCO Global Geoparks.shp
  geonode/tests/data/UNESCO Global Geoparks/UNESCO Global Geoparks.shx
  geonode/tests/data/UNESCO Global Geoparks/uNESCO Global Geoparks.sld
  geonode/tests/integration.py
  geonode/utils.py
Labels: backport 2.10.x, cla-signed

#5337 [Fixes #5335] Auto assignment of users to "registered-members" group is not working under certain conditions
  docs/basic/settings/index.rst
  geonode/groups/tests.py
  geonode/people/signals.py
Labels: backport 2.10.x, cla-signed

#5343 [Issue #4276] Upgrade documents for Python 2.7/3 compatibility
  geonode/documents/autocomplete_light_registry.py
  geonode/documents/migrations/0028_auto_20170801_1228.py
  geonode/documents/migrations/0028_auto_20170801_1228_squashed_0035_auto_20190404_0820.py
  geonode/documents/migrations/0029_auto_20180301_1947.py
  geonode/documents/migrations/0029_auto_20190429_0831.py
  geonode/documents/migrations/0030_auto_20180302_0430.py
  geonode/documents/migrations/0031_auto_20180409_1238.py
  geonode/documents/migrations/0032_auto_20180412_0822.py
  geonode/documents/migrations/0033_auto_20180414_2120.py
  geonode/documents/migrations/0034_auto_20190329_1652.py
  geonode/documents/migrations/0035_auto_20190404_0820.py
  geonode/documents/migrations/24_initial.py
  geonode/documents/migrations/25_add_documentresourcelink_table.py
  geonode/documents/migrations/27_drop_resource_columns_from_document_table.py
  geonode/documents/models.py
  geonode/documents/renderers.py
  geonode/documents/tests.py
  geonode/documents/utils.py
  geonode/documents/views.py
Labels: cla-signed, python-3

#5340 [Fixes #5339][Performance] Vectorial Layers are quite slow while trying to fetch the details page
  geonode/layers/views.py
Labels: backport 2.10.x, cla-signed, performance

#5342 [Issue #4276] Upgrade client for Python 2.7/3 compatibility
  geonode/client/hooks.py
  geonode/client/hooksets.py
  geonode/client/migrations/0001_initial.py
  geonode/client/migrations/0002_auto_20180412_1039.py
  geonode/client/migrations/0002_auto_20180412_1039_squashed_0005_auto_20181015_1201.py
  geonode/client/migrations/0003_geonodethemecustomization_jumbotron_welcome_hide.py
  geonode/client/migrations/0004_auto_20180416_1319.py
  geonode/client/migrations/0005_auto_20181015_1201.py
Labels: cla-signed, python-3

#5344 [Issue #4276] Upgrade geonode.utils for Python 2.7/3 compatibility
  geonode/utils.py
Labels: backport 2.10.x, cla-signed, python-3

#5346 [Fixes #5345][Performance] Get rid of broken URLs around
  docs/basic/settings/index.rst
  docs/intermediate/monitoring/geonode_monitoring/index.rst
  geonode/client/static/geonode/js/extjs/GeoNode-GeoExplorer.js
  geonode/client/static/geonode/js/extjs/GeoNode-mixin.js
  geonode/client/static/geonode/js/extjs/Geonode-CatalogueApiSearch.js
  geonode/client/static/geonode/js/extjs/ux.js
  geonode/client/static/geonode/js/lang.js
  geonode/client/templates/geoext/app_header.html
  geonode/client/templates/ol/layers/layer_ol2_map.html
  geonode/client/templates/ol/layers/layer_ol3_map.html
  geonode/client/templates/ol/maps/map_ol2.html
  geonode/client/templates/ol/maps/map_ol3.html
  geonode/monitoring/middleware.py
  geonode/security/middleware.py
  geonode/templates/base.html
  geonode/urls.py
  geonode/version.py
Labels: backport 2.10.x, cla-signed, performance
