Repository GeoNode/geonode, pull requests merged in 2019-07, with the labels that each got.

#4663 Bump owslib from 0.17.1 to 0.18.0
  geonode/upload/tests/integration.py
  pavement.py
  requirements.txt
Labels: backport 2.10.x, dependencies

#4679 [Backport 2.10.x] requirements from master branch
  AUTHORS
  requirements.txt
  requirements_docs.txt
Labels: dependencies

#4680 Fix geonode docker image version
  Dockerfile
  docker-compose.async.yml
  docker-compose.yml
Labels: backport 2.10.x

#4464 [Draft] Make templates use static url set by Django
  geonode/static/geonode/js/search/cart.js
  geonode/static/geonode/js/status/main.js
  geonode/static/geonode/js/upload/csv.js
  geonode/static/geonode/js/upload/main.js
  geonode/static/geonode/js/upload/srs.js
  geonode/static/geonode/js/upload/time.js
  geonode/static/geonode/js/utils/batch_ops.js
  geonode/templates/base.html
Labels: feature

#4702 updated some strings in the italian translation
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: tranlsations
