Repository GeoNode/geonode, pull requests merged in 2019-09, with the labels that each got.

#4796 [Fixes: #4488] Add missing ngCookies when DEBUG_STATIC true
  geonode/templates/search/search_scripts.html
Labels: cla-signed

#4806 [Fixes: #4805] updated angular, select2, bootstrap
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/bootstrap.min.css
  geonode/static/lib/js/affix.js
  geonode/static/lib/js/alert.js
  geonode/static/lib/js/angular.js
  geonode/static/lib/js/angular.min.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/bootstrap-datetimepicker.js
  geonode/static/lib/js/bootstrap-select.js
  geonode/static/lib/js/bootstrap-select.min.js
  geonode/static/lib/js/bootstrap.js
  geonode/static/lib/js/bootstrap.min.js
  geonode/static/lib/js/button.js
  geonode/static/lib/js/carousel.js
  geonode/static/lib/js/collapse.js
  geonode/static/lib/js/dropdown.js
  geonode/static/lib/js/index.js
  geonode/static/lib/js/jquery.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/lib/js/modal.js
  geonode/static/lib/js/popover.js
  geonode/static/lib/js/require.js
  geonode/static/lib/js/scrollspy.js
  geonode/static/lib/js/tab.js
  geonode/static/lib/js/text.js
  geonode/static/lib/js/tooltip.js
  geonode/static/lib/js/transition.js
  geonode/static/lib/js/underscore.js
  geonode/static/package.json
  geonode/static/yarn.lock
Labels: backport 2.10.x, cla-signed, security

#4801 [Backport 4796 to 2.10.x] [Fixes: #4488] Add missing ngCookies when DEBUG_STATIC true (#4796)
  .clabot
  .github/PULL_REQUEST_TEMPLATE.md
  CLA_INDIVIDUAL.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING
  CONTRIBUTING.md
  README.md
  docs/start/quick/index.rst
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/jquery.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/lib/js/require.js
  geonode/static/lib/js/text.js
  geonode/static/lib/js/underscore.js
  geonode/templates/search/search_scripts.html
  requirements.txt
Labels: cla-signed

#4811 [Backport to 2.10.x] updated angular, select2, bootstrap
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/bootstrap.min.css
  geonode/static/lib/js/affix.js
  geonode/static/lib/js/alert.js
  geonode/static/lib/js/angular.js
  geonode/static/lib/js/angular.min.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/bootstrap-datetimepicker.js
  geonode/static/lib/js/bootstrap-select.js
  geonode/static/lib/js/bootstrap-select.min.js
  geonode/static/lib/js/bootstrap.js
  geonode/static/lib/js/bootstrap.min.js
  geonode/static/lib/js/button.js
  geonode/static/lib/js/carousel.js
  geonode/static/lib/js/collapse.js
  geonode/static/lib/js/dropdown.js
  geonode/static/lib/js/index.js
  geonode/static/lib/js/modal.js
  geonode/static/lib/js/popover.js
  geonode/static/lib/js/scrollspy.js
  geonode/static/lib/js/tab.js
  geonode/static/lib/js/tooltip.js
  geonode/static/lib/js/transition.js
  geonode/static/package.json
  geonode/static/yarn.lock
Labels: cla-signed

#4810 [Fixes #4809] Static assets still using Select2 3.5 instead of Select2 4
  geonode/static/gruntfile.js
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/select2.min.css
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/select2.full.js
  geonode/static/lib/js/select2.full.min.js
  geonode/static/lib/js/select2.js
  geonode/static/lib/js/select2.min.js
  geonode/templates/_permissions.html
  geonode/templates/_permissions_form_js.html
Labels: backport 2.10.x, cla-signed

#4816 [Backport 2.10.x] Backporting dependabot requirements to 2.10.x
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/gnip.md
  .github/ISSUE_TEMPLATE/report_issue.md
  requirements.txt
Labels: cla-signed, dependencies

#4817 [Fixes #4813] Removing a layer is broken - Celery error
  geonode/documents/tasks.py
  geonode/geoserver/tasks.py
  geonode/layers/tasks.py
  geonode/maps/tasks.py
  geonode/qgis_server/tasks/update.py
  geonode/services/tasks.py
  geonode/settings.py
  geonode/tasks/tasks.py
Labels: backport 2.10.x, cla-signed

#4818 [Fixes #4772] Get rid of deprecated "Publish local map layers as WMS …
  geonode/maps/models.py
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/urls.py
  geonode/maps/views.py
  geonode/utils.py
  requirements.txt
Labels: backport 2.10.x, cla-signed

#4821 [Backport 4817 to 2.10.x] Removing a layer is broken - Celery error
  geonode/documents/tasks.py
  geonode/geoserver/tasks.py
  geonode/layers/tasks.py
  geonode/maps/tasks.py
  geonode/qgis_server/tasks/update.py
  geonode/services/tasks.py
  geonode/settings.py
  geonode/tasks/tasks.py
Labels: cla-signed

#4259 Test standard docker setup with geonode-selenium
  .travis.yml
Labels: cla-signed, draft, in progress, stale

#4573 Spcgeonode with mapstore2 and postgis
  scripts/spcgeonode/django/initialize.py
  scripts/spcgeonode/docker-compose.yml
  scripts/spcgeonode/nginx/spcgeonode.conf
Labels: cla-signed, docker, feature

#4832 [Fixes #4831] GeoNode Importer mode not really asynchronous
  geonode/layers/templates/layers/layer_detail.html
  geonode/upload/tests/integration.py
  geonode/upload/upload.py
  geonode/upload/views.py
Labels: backport 2.10.x, cla-signed

#4833 [Backport to 2.10.x] Backport requirements.txt to 2.10.x
  requirements.txt
Labels: cla-signed

#4834 [Backport 4573 to 2.10.x] Spcgeonode with mapstore2 and postgis
  scripts/spcgeonode/django/initialize.py
  scripts/spcgeonode/docker-compose.yml
  scripts/spcgeonode/nginx/spcgeonode.conf
Labels: cla-signed

#4836 Bump django-mapstore-adapter from 1.0.5 to 1.0.6
  requirements.txt
Labels: backport 2.10.x, cla-signed, dependencies

#4835 [Backport 4259 to 2.10.x] Test standard docker setup with geonode-sel…
  .travis.yml
Labels: cla-signed

#4845 Fixes #4844
  geonode/settings.py
Labels: cla-signed

#4843 [Fixes #4842] Monitoring APIs improvements
  docs/intermediate/monitoring/user_analytics/index.rst
  geonode/monitoring/collector.py
  geonode/monitoring/tests/integration.py
  geonode/monitoring/utils.py
  geonode/monitoring/views.py
Labels: backport 2.10.x, cla-signed

#4850 [Fixes #4849] retrieve cpu and mem usage metric data
  geonode/monitoring/collector.py
  geonode/monitoring/fixtures/metric_data.json
  geonode/monitoring/tests/integration.py
Labels: backport 2.10.x, cla-signed

#4860 [Fixes #4855] Download links always return whole world bbox
  geonode/geoserver/signals.py
  geonode/monitoring/collector.py
  geonode/monitoring/management/commands/collect_metrics.py
  geonode/monitoring/tests/integration.py
  geonode/security/tests.py
  geonode/settings.py
  geonode/tests/utils.py
  geonode/upload/tests/integration.py
  geonode/upload/tests/test_settings.py
  geonode/upload/utils.py
  geonode/upload/views.py
Labels: backport 2.10.x, cla-signed

#4852 Bump django-mapstore-adapter from 1.0.6 to 1.0.7
  requirements.txt
Labels: backport 2.10.x, cla-signed, dependencies

#4854 Bump gn-gsimporter from 1.0.10 to 1.0.12
  requirements.txt
Labels: backport 2.10.x, cla-signed, dependencies

#4865 [Fixes #4863] Trying to assign permission to more than one users, fails
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/templates/_permissions.html
  geonode/templates/_permissions_form_js.html
Labels: backport 2.10.x, cla-signed

#4868 [Fixes #4827] Line layer uploaded to GeoNode is rendered as point layer
  geonode/geoserver/helpers.py
  geonode/tests/integration.py
Labels: backport 2.10.x, cla-signed

#4864 [Fixes #4861] improved monitoring api filtering
  docs/intermediate/monitoring/api/index.rst
  docs/intermediate/monitoring/user_analytics/index.rst
  geonode/monitoring/admin.py
  geonode/monitoring/collector.py
  geonode/monitoring/tests/integration.py
  geonode/monitoring/utils.py
  geonode/monitoring/views.py
Labels: backport 2.10.x, cla-signed

#4877 [Backport 4864 to 2.10.x] [Fixes #4861] improved monitoring api filtering (#4864)
  docs/intermediate/monitoring/api/index.rst
  docs/intermediate/monitoring/user_analytics/index.rst
  geonode/monitoring/admin.py
  geonode/monitoring/collector.py
  geonode/monitoring/tests/integration.py
  geonode/monitoring/utils.py
  geonode/monitoring/views.py
Labels: cla-signed

#4875 [Backport 4868 to 2.10.x] [Fixes #4827] Line layer uploaded to GeoNode is rendered as point layer (#4868)
  geonode/geoserver/helpers.py
  geonode/tests/integration.py
Labels: cla-signed

#4889 [Backport 4867 to 2.10.x] [Fixes #4846, Fixes #4866] Curated thumbnails are not used and API doesn't return username (#4867)
  geonode/api/resourcebase_api.py
Labels: cla-signed

#4891 [Fixes #4884] Attached SLD works only with ZIP files when "geonode.im…
  geonode/layers/utils.py
  geonode/upload/tests/__init__.py
  geonode/upload/tests/test_upload_preprocessing.py
  geonode/upload/upload_validators.py
  geonode/utils.py
Labels: backport 2.10.x, cla-signed

#4897 [Fixes #4896] fixing data in response
  geonode/monitoring/collector.py
  geonode/monitoring/models.py
  geonode/monitoring/tests/integration.py
Labels: backport 2.10.x, cla-signed

#4899 [Fixes #4790] Issue adding remote service with non-ascii characters i…
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/tests.py
Labels: backport 2.10.x, cla-signed

#4904 [Fixes #4903] fixing wrong hits count
  geonode/monitoring/collector.py
  geonode/monitoring/tests/integration.py
Labels: backport 2.10.x, cla-signed

#4909 [Fixes #4908] change monitoring label
  geonode/locale/en/LC_MESSAGES/django.mo
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/en/LC_MESSAGES/djangojs.mo
  geonode/locale/en/LC_MESSAGES/djangojs.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/djangojs.mo
  geonode/locale/it/LC_MESSAGES/djangojs.po
  geonode/templates/base.html
Labels: backport 2.10.x, cla-signed

#4912 [Fixes #4911] On Monitoring plugin the uptime is not correctly computed
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/djangojs.mo
  geonode/locale/it/LC_MESSAGES/djangojs.po
  geonode/monitoring/frontend/monitoring/src/components/cels/response-table/index.js
  geonode/monitoring/frontend/monitoring/src/components/cels/response-time/index.js
  geonode/monitoring/frontend/monitoring/src/components/cels/uptime/index.js
  geonode/monitoring/frontend/monitoring/src/utils.js
  geonode/monitoring/models.py
  geonode/monitoring/static/monitoring/bundle.js
  geonode/monitoring/templates/monitoring/index.html
  geonode/monitoring/templates/monitoring/non_superuser.html
  geonode/monitoring/utils.py
  geonode/settings.py
Labels: backport 2.10.x

#4919 [Fixes #4916] – show featured items on startpage
  geonode/templates/index.html
Labels: backport 2.10.x, cla-signed

#4921 [Fixes: #4920] Footer Display Code on Detail Layer pages
  geonode/layers/templates/layers/layer_detail.html
Labels: backport 2.10.x, cla-signed, minor

#4925 [Fixes #4924] Add member to Group is broken
  geonode/groups/forms.py
  geonode/groups/templates/groups/group_members.html
  geonode/groups/views.py
Labels: backport 2.10.x, cla-signed

#4927 [Backport to 2.10.x][Fixes #4924] Add member to Group is broken
  geonode/groups/forms.py
  geonode/groups/templates/groups/group_members.html
  geonode/groups/views.py
Labels: cla-signed

#4928 Bump django-mapstore-adapter to 1.0.8
  requirements.txt
Labels: backport 2.10.x, cla-signed, dependencies

#4934 [Fixes #4907] Add the possibility of enabling "captcha" on GeoNode si…
  docs/basic/settings/index.rst
  geonode/people/forms.py
  geonode/settings.py
  requirements.txt
Labels: backport 2.10.x, cla-signed

#4940 [Fixes: #4933] forgot password in modal
  geonode/templates/base.html
Labels: backport 2.10.x, cla-signed

#4944 [Fixes: #4963] Fix wrong template include for all_auth
  geonode/templates/account/verification_sent.html
Labels: backport 2.10.x, cla-signed

#4955 [Fixes #4739] Layer post_save deletes links to external thumbnails / …
  geonode/base/models.py
Labels: backport 2.10.x, cla-signed

#4958 [Fixes #4949] UnicodeEncodeError in upload.models.update_from_session
  geonode/upload/models.py
  geonode/upload/tests/integration.py
Labels: backport 2.10.x, cla-signed

#4963 Use Tomcat 8.5.46
  docs/install/core/index.rst
Labels: backport 2.10.x, docs

#4969 [Fixes #4964] Date widget has gone
  geonode/static/geonode/js/search/search.js
  geonode/templates/base.html
Labels: backport 2.10.x, cla-signed

#4960 [Fixes #4959] By using UPLOADER=geonode.rest we are facing a timing i…
  geonode/geoserver/signals.py
  geonode/messaging/consumer.py
  geonode/tests/csw.py
Labels: backport 2.10.x, cla-signed
