Repository GeoNode/geonode, pull requests merged in 2019-08, with the labels that each got.

#4729 Use defusedxml instead of xml
  geonode/base/management/commands/load_thesaurus.py
  geonode/catalogue/backends/generic.py
  geonode/catalogue/backends/pycsw_local.py
  geonode/catalogue/metadataxsl/views.py
  geonode/catalogue/models.py
  geonode/catalogue/views.py
  geonode/geoserver/helpers.py
  geonode/geoserver/views.py
  geonode/layers/metadata.py
  geonode/layers/views.py
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/monitoring/tests.py
  geonode/monitoring/utils.py
  geonode/qgis_server/gis_tools.py
  geonode/qgis_server/helpers.py
  geonode/qgis_server/models.py
  geonode/qgis_server/tests/test_helpers.py
  geonode/qgis_server/tests/test_views.py
  geonode/security/tests.py
  geonode/tests/csw.py
  geonode/tests/integration.py
  geonode/upload/utils.py
  requirements.txt
Labels: backport 2.10.x, minor, security

#4733 [Backport 4729 to 2.10.x] Use defusedxml instead of xml
  geonode/base/management/commands/load_thesaurus.py
  geonode/catalogue/backends/generic.py
  geonode/catalogue/backends/pycsw_local.py
  geonode/catalogue/metadataxsl/views.py
  geonode/catalogue/models.py
  geonode/catalogue/views.py
  geonode/geoserver/helpers.py
  geonode/geoserver/views.py
  geonode/layers/metadata.py
  geonode/layers/views.py
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/monitoring/tests.py
  geonode/monitoring/utils.py
  geonode/qgis_server/gis_tools.py
  geonode/qgis_server/helpers.py
  geonode/qgis_server/models.py
  geonode/qgis_server/tests/test_helpers.py
  geonode/qgis_server/tests/test_views.py
  geonode/security/tests.py
  geonode/tests/csw.py
  geonode/tests/integration.py
  geonode/upload/utils.py
  requirements.txt
Labels: dependencies, security

#4735 Bump django-geonode-mapstore-client from 1.3.1 to 1.4.0
  requirements.txt
Labels: backport 2.10.x, dependencies, security

#4745 Bump geonode-oauth-toolkit from 1.3.1 to 1.1.4.1rc0
  geonode/settings.py
  requirements.txt
Labels: backport 2.10.x, dependencies

#4751 [Fixes #4713] Attributes are not added in layers_attributes table when a layer is uploaded
  geonode/geoserver/helpers.py
  geonode/proxy/views.py
  geonode/security/tests.py
  geonode/settings.py
  geonode/upload/tests/integration.py
  geonode/utils.py
Labels: backport 2.10.x

#4753 Backporting dependabot requirements updates from master branch
  requirements.txt
Labels: dependencies

#4756 Update django-tastypie requirement from <=0.14.0 to <0.15.0
  geonode/tests/integration.py
  requirements.txt
Labels: backport 2.10.x, dependencies

#4763 [Backports to 2.10.x] Update django-tastypie requirement from <=0.14.0 to <0.15.0
  geonode/tests/integration.py
  requirements.txt
Labels: dependencies

#4779 [Fixes: #4774][Fixes: #4771] Removed autocomplete from password fields
  geonode/monitoring/frontend/index.html
  geonode/templates/500.html
  geonode/templates/base.html
Labels: minor, security

#4782 [Docs] Add sentence regarding minimal requirements
  docs/start/quick/index.rst
Labels: cla-signed, docs

#4784 [Fixes: #4765] - improved upload error handling
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/jquery.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/lib/js/require.js
  geonode/static/lib/js/text.js
  geonode/static/lib/js/underscore.js
Labels: cla-signed, feature
