Repository GeoNode/geonode, pull requests merged in 2019-10, with the labels that each got.

#4991 [Fixes #4990] fix set_layers_permissions managament command
  geonode/layers/management/commands/set_layers_permissions.py
  geonode/layers/tests.py
  geonode/layers/utils.py
Labels: backport 2.10.x, cla-signed

#4982 [Fixes #4976] Auxiliary file not uploaded to Geoserver with geonode.importer / [Hardening] Make master more resilient to errors
  geonode/base/migrations/0029_resourcebase_last_updated.py
  geonode/base/migrations/0030_resourcebase_created.py
  geonode/base/models.py
  geonode/catalogue/metadataxsl/models.py
  geonode/catalogue/models.py
  geonode/documents/models.py
  geonode/geoserver/helpers.py
  geonode/geoserver/management/commands/sync_geonode_layers.py
  geonode/geoserver/signals.py
  geonode/layers/models.py
  geonode/security/models.py
  geonode/services/migrations/0028_remove_service_last_updated.py
  geonode/services/migrations/0029_remove_service_created.py
  geonode/services/models.py
  geonode/tests/csw.py
  geonode/upload/files.py
  geonode/upload/tests/data/arc_sample.zip
  geonode/upload/tests/data/arc_sample/precip30min.asc
  geonode/upload/tests/data/arc_sample/precip30min.prj
  geonode/upload/tests/integration.py
  geonode/utils.py
Labels: backport 2.10.x, cla-signed

#5001 [Fixes: #5000] Update Frontend section
  docs/contribute/frontend-development/index.rst
Labels: backport 2.10.x, cla-signed, docs

#5018 [Documentation] LDAP Contrib Module Documentation
  docs/advanced/contrib/index.rst
  docs/advanced/index.rst
  docs/advanced/ldap/index.rst
Labels: backport 2.10.x, cla-signed, docs

#5019 [Documentation] Backporting GeoNode/GeoServer AA Sections
  docs/admin/mgmt_commands/img/add_test_user.png
  docs/admin/mgmt_commands/img/add_user.png
  docs/admin/mgmt_commands/img/admin_interface.png
  docs/admin/mgmt_commands/img/menu_admin.png
  docs/admin/mgmt_commands/img/permissions_django_admin.png
  docs/admin/mgmt_commands/img/register.png
  docs/admin/mgmt_commands/img/sign_up_test_user.png
  docs/admin/mgmt_commands/index.rst
  docs/advanced/components/img/google_ssl_001.png
  docs/advanced/components/img/google_ssl_002.png
  docs/advanced/components/img/google_ssl_003.png
  docs/advanced/components/img/google_ssl_004.png
  docs/advanced/components/img/google_ssl_005.png
  docs/advanced/components/img/google_ssl_006.png
  docs/advanced/components/img/google_ssl_007.png
  docs/advanced/components/img/google_ssl_008.png
  docs/advanced/components/img/google_ssl_009.png
  docs/advanced/components/img/google_ssl_010.png
  docs/advanced/components/img/google_ssl_011.png
  docs/advanced/components/img/google_ssl_012.png
  docs/advanced/components/img/google_ssl_013.png
  docs/advanced/components/img/oauth001.png
  docs/advanced/components/img/oauth002.png
  docs/advanced/components/img/oauth003.png
  docs/advanced/components/img/oauth004.png
  docs/advanced/components/img/oauth005.png
  docs/advanced/components/img/oauth006.png
  docs/advanced/components/img/oauth007.png
  docs/advanced/components/img/oauth008.png
  docs/advanced/components/img/oauth009.png
  docs/advanced/components/img/oauth010.png
  docs/advanced/components/img/oauth011.png
  docs/advanced/components/img/oauth012.png
  docs/advanced/components/img/oauth013.png
  docs/advanced/components/img/oauth014.png
  docs/advanced/components/img/oauth015.png
  docs/advanced/components/img/oauth016.png
  docs/advanced/components/img/oauth017.png
  docs/advanced/components/img/oauth018.png
  docs/advanced/components/img/oauth019.png
  docs/advanced/components/img/oauth020.png
  docs/advanced/components/img/oauth021.png
  docs/advanced/components/img/oauth022.png
  docs/advanced/components/img/oauth023.png
  docs/advanced/components/img/oauth024.png
  docs/advanced/components/img/oauth025.png
  docs/advanced/components/img/oauth026.png
  docs/advanced/components/img/oauth027.png
  docs/advanced/components/img/oauth028.png
  docs/advanced/components/img/oauth029.png
  docs/advanced/components/img/oauth030.png
  docs/advanced/components/img/oauth031.png
  docs/advanced/components/img/oauth032.png
  docs/advanced/components/img/oauth033.png
  docs/advanced/components/index.rst
Labels: backport 2.10.x, cla-signed, docs

#5022 [Documentation] Loading (and Processing) external data / importlayers and updatelayers Management Commands
  docs/admin/mgmt_commands/img/geoserver_admin.png
  docs/admin/mgmt_commands/img/geoserver_layer_params.png
  docs/admin/mgmt_commands/img/geoserver_layers.png
  docs/admin/mgmt_commands/img/geoserver_new_store.png
  docs/admin/mgmt_commands/img/geoserver_postgis_params.png
  docs/admin/mgmt_commands/img/geoserver_publish_layers.png
  docs/admin/mgmt_commands/img/geoserver_srs.png
  docs/admin/mgmt_commands/img/geoserver_srs_2.png
  docs/admin/mgmt_commands/img/layer_info_vector.png
  docs/admin/mgmt_commands/img/tiled_vs_stripped.png
  docs/admin/mgmt_commands/img/upload_shapefile.png
  docs/admin/mgmt_commands/index.rst
Labels: backport 2.10.x, cla-signed, docs

#5035 [Fixes: #4930] Remove Edit Data button for RASTER layer
  geonode/layers/templates/layers/layer_detail.html
Labels: cla-signed

#5033 [Fixes: #4929] Remove Google+ from share options
  geonode/documents/templates/documents/document_detail.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/maps/templates/maps/map_detail.html
  geonode/settings.py
Labels: cla-signed

#5040 [Backport to 2.10.x] #4930 Remove Edit Data button for RASTER layer (#5035)
  geonode/layers/templates/layers/layer_detail.html
Labels: cla-signed

#5055 [Fixes: #5054 | Fixes: #5053] German Translations and Documents Section
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
Labels: backport 2.10.x, cla-signed

#5060 [Fixes #5031] Disable monitoring by default
  geonode/settings.py
Labels: backport 2.10.x, cla-signed

#5061 [Fixes #4956] "Original Dataset" Link behavior improvements
  geonode/layers/templates/layers/layer_detail.html
  geonode/proxy/templatetags/__init__.py
  geonode/proxy/templatetags/proxy_lib_tags.py
  geonode/proxy/views.py
  geonode/templates/401.html
  geonode/templates/base.html
Labels: backport 2.10.x, cla-signed

#5062 [Fixes #4942] Download layer filter not sending CQL filter anymore
  geonode/layers/templates/layers/layer_detail.html
Labels: backport 2.10.x, cla-signed

#5068 [Fixes #4659] Double message on Submit invite users
  geonode/templates/invitations/forms/_invite.html
Labels: backport 2.10.x, cla-signed

#5071 [Fixes #5070] Add Bing background layer config to MapStore2 adapter if apiKey is provided
  docs/basic/settings/index.rst
  geonode/settings.py
  requirements.txt
Labels: backport 2.10.x, cla-signed

#5074 [Fixes #5073] Update install docs
  docs/install/core/index.rst
Labels: backport 2.10.x, cla-signed, docs

#5075 Backport 5074 to 2.10.x
  docs/install/core/index.rst
Labels: cla-signed

#5097 [Fixes #5096] Disabling geonode.monitoring causes model exceptions on views
  geonode/settings.py
  pavement.py
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5090 [Fixes #5089] Update index.html
  geonode/templates/index.html
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5092 [Fixes #4827] Line layer uploaded to GeoNode is rendered as point layer
  geonode/catalogue/models.py
  geonode/geoserver/helpers.py
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5122 [Fixes #5121] ResourceBase API returns an error if a curated thumbnail img file is not existing anymore
  geonode/api/resourcebase_api.py
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5135 [Fixes #5117] Publishing layers of two remote services with same
  geonode/groups/tests.py
  geonode/layers/models.py
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/maps/migrations/0028_maplayer_store.py
  geonode/maps/models.py
  geonode/maps/views.py
  geonode/utils.py
  requirements.txt
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5142 [Fixes #5137][Fixes #5138] Encode Hierarchical tags and external service
  geonode/base/models.py
  geonode/layers/tests.py
  geonode/services/templates/services/service_detail.html
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5157 [Fixes #5105] Error when using THESAURI
  geonode/base/widgets.py
Labels: backport 2.10.1, backport 2.10.x, cla-signed

#5169 [Backport to 2.10.1][Fixes #2932] Unable to update a layer (replace action) nor create a new layer with the same name of a already deleted layer (#4829)
  geonode/layers/tests.py
  geonode/layers/utils.py
Labels: cla-signed
