Repository GeoNode/geonode, pull requests merged in 2019-12, with the labels that each got.

#5341 [Issue #4276] Upgrade catalogue for Python 2.7/3 compatibility
  geonode/catalogue/__init__.py
  geonode/catalogue/backends/generic.py
  geonode/catalogue/backends/pycsw_local.py
  geonode/catalogue/backends/pycsw_plugin.py
  geonode/catalogue/metadataxsl/management/commands/addmissinglinks.py
  geonode/catalogue/metadataxsl/models.py
  geonode/catalogue/tests.py
  geonode/catalogue/views.py
Labels: cla-signed, python-3

#5333 [Issue #4276] Upgrade geonode-agon-ratings to pinax-ratings
  docs/basic/settings/index.rst
  geonode/base/management/commands/settings.ini
  geonode/base/models.py
  geonode/base/templatetags/base_tags.py
  geonode/documents/search_indexes.py
  geonode/documents/templates/documents/document_detail.html
  geonode/geoserver/helpers.py
  geonode/layers/models.py
  geonode/layers/search_indexes.py
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_metadata_upload.html
  geonode/layers/templates/layers/layer_replace.html
  geonode/layers/templates/layers/layer_style_edit.html
  geonode/layers/templates/layers/layer_style_upload.html
  geonode/layers/tests.py
  geonode/maps/models.py
  geonode/maps/search_indexes.py
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/tests.py
  geonode/settings.py
  geonode/social/signals.py
  geonode/urls.py
  package/debian/control
  requirements.txt
  scripts/backup-restore/settings.ini
Labels: cla-signed, python-3

#5349 [Fixes #5348][Performance] Cache Busting mechanism to manage static resources cache
  docs/basic/settings/index.rst
  geonode/api/resourcebase_api.py
  geonode/base/models.py
  geonode/base/templates/base/thumbnail_upload.html
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/client/templates/geoext/app_header.html
  geonode/client/templates/geoext/ext_header.html
  geonode/client/templates/geoext/geo_header.html
  geonode/client/templates/geoext/geo_header_debug.html
  geonode/client/templates/geoext/geo_header_mini.html
  geonode/client/templates/geoext/sdk_header.html
  geonode/documents/templates/documents/document_thumb_upload.html
  geonode/documents/templates/documents/document_upload.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoserver/helpers.py
  geonode/layers/templates/layers/layer_metadata_upload.html
  geonode/layers/templates/layers/layer_replace.html
  geonode/layers/templates/layers/layer_style_upload.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/templates/upload/layer_upload.html
  geonode/layers/templates/upload/layer_upload_crs.html
  geonode/layers/templates/upload/layer_upload_csv.html
  geonode/layers/templates/upload/layer_upload_time.html
  geonode/layers/utils.py
  geonode/local_settings.py.geoserver.sample
  geonode/maps/templates/layouts/map_panels.html
  geonode/proxy/templatetags/proxy_lib_tags.py
  geonode/proxy/views.py
  geonode/security/tests.py
  geonode/security/views.py
  geonode/settings.py
  geonode/templates/500.html
  geonode/templates/base.html
  geonode/templates/metadata_base.html
  geonode/templates/metadata_form_js.html
  geonode/templates/search/search_scripts.html
  geonode/tests/integration.py
  geonode/utils.py
  package/support/geonode.local_settings
  scripts/backup-restore/helpers.py
Labels: backport 2.10.x, cla-signed, performance

#5350 [Issue #4276] Upgrade upload for Python 2.7/3 compatibility
  geonode/upload/files.py
  geonode/upload/forms.py
  geonode/upload/models.py
  geonode/upload/tests/__init__.py
  geonode/upload/tests/integration.py
  geonode/upload/tests/test_settings.py
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/upload/views.py
Labels: cla-signed, python-3

#5351 [Issue #4276] Upgrade favorite for Python 2.7/3 compatibility
  geonode/favorite/models.py
  geonode/favorite/utils.py
  geonode/favorite/views.py
Labels: cla-signed, python-3

#5352 [Issue #4276] Upgrade groups for Python 2.7/3 compatibility
  geonode/groups/templatetags/groups_tags.py
  geonode/groups/tests.py
Labels: cla-signed, python-3

#5360 [Issue #4276] Upgrade maps for Python 2.7/3 compatibility
  geonode/maps/autocomplete_light_registry.py
  geonode/maps/management/commands/remove_broken_layers.py
  geonode/maps/qgis_server_views.py
  geonode/maps/tests.py
  geonode/maps/utils.py
  geonode/maps/views.py
Labels: cla-signed, python-3

#5361 [Issue #4276] Upgrade messaging for Python 2.7/3 compatibility
  geonode/messaging/consumer.py
  geonode/messaging/producer.py
Labels: cla-signed, python-3

#5362 [Issue #4276] Upgrade monitoring for Python 2.7/3 compatibility
  geonode/monitoring/__init__.py
  geonode/monitoring/aggregation.py
  geonode/monitoring/collector.py
  geonode/monitoring/management/commands/collect_metrics.py
  geonode/monitoring/management/commands/render_metrics.py
  geonode/monitoring/middleware.py
  geonode/monitoring/models.py
  geonode/monitoring/probes.py
  geonode/monitoring/tests/integration.py
  geonode/monitoring/utils.py
Labels: cla-signed, python-3

#5363 [Issue #4276] Python 2.7/3 compatibility fixes for merged core apps
  geonode/api/api.py
  geonode/api/resourcebase_api.py
  geonode/catalogue/backends/pycsw_local.py
  geonode/catalogue/tests.py
  geonode/catalogue/views.py
  geonode/client/hooks.py
  geonode/client/hooksets.py
  geonode/client/migrations/0001_initial.py
  geonode/client/migrations/0002_auto_20180412_1039.py
  geonode/client/migrations/0002_auto_20180412_1039_squashed_0005_auto_20181015_1201.py
  geonode/client/migrations/0003_geonodethemecustomization_jumbotron_welcome_hide.py
  geonode/client/migrations/0004_auto_20180416_1319.py
  geonode/client/migrations/0005_auto_20181015_1201.py
  geonode/documents/migrations/0028_auto_20170801_1228.py
  geonode/documents/migrations/0028_auto_20170801_1228_squashed_0035_auto_20190404_0820.py
  geonode/documents/migrations/0029_auto_20180301_1947.py
  geonode/documents/migrations/0029_auto_20190429_0831.py
  geonode/documents/migrations/0030_auto_20180302_0430.py
  geonode/documents/migrations/0031_auto_20180409_1238.py
  geonode/documents/migrations/0032_auto_20180412_0822.py
  geonode/documents/migrations/0033_auto_20180414_2120.py
  geonode/documents/migrations/0034_auto_20190329_1652.py
  geonode/documents/migrations/0035_auto_20190404_0820.py
  geonode/documents/migrations/24_initial.py
  geonode/documents/migrations/25_add_documentresourcelink_table.py
  geonode/documents/migrations/27_drop_resource_columns_from_document_table.py
Labels: cla-signed, python-3

#5359 [Issue #4276] Upgrade layers for Python 2.7/3 compatibility
  geonode/layers/autocomplete_light_registry.py
  geonode/layers/management/commands/importlayers.py
  geonode/layers/models.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
Labels: cla-signed, python-3

#5367 [Fixes #5366] Sentinel Cloudless Background should use JPEG format rather than PNG
  docs/basic/settings/index.rst
  geonode/local_settings.py.geoserver.sample
  geonode/settings.py
Labels: backport 2.10.x, cla-signed, performance

#5369 [Issue #4276] Upgrade geoserver for Python 2.7/3 compatibility
  geonode/geoserver/createlayer/utils.py
  geonode/geoserver/helpers.py
  geonode/geoserver/management/commands/find_geoserver_broken_layers.py
  geonode/geoserver/management/commands/sync_geonode_layers.py
  geonode/geoserver/management/commands/updatelayers.py
  geonode/geoserver/ows.py
  geonode/geoserver/views.py
Labels: cla-signed, python-3

#5371 [Issue #4276] Upgrade qgis_server for Python 2.7/3 compatibility
  geonode/qgis_server/gis_tools.py
  geonode/qgis_server/helpers.py
  geonode/qgis_server/management/commands/import_qgis_styles.py
  geonode/qgis_server/tests/test_helpers.py
  geonode/qgis_server/tests/test_management.py
  geonode/qgis_server/tests/test_views.py
  geonode/qgis_server/tests/test_xml_utilities.py
  geonode/qgis_server/views.py
  geonode/qgis_server/xml_utilities.py
Labels: cla-signed, python-3

#5375 [Issue #4276] Upgrade base dir for Python 2.7/3 compatibility
  pavement.py
  tasks.py
Labels: cla-signed, python-3

#5380 [Issue #4276] Running 2to3 on scripts module
  scripts/backup-restore/backup.py
  scripts/backup-restore/helpers.py
  scripts/backup-restore/migrate_layers.py
  scripts/backup-restore/restore.py
  scripts/cloud/demo_site.py
  scripts/cloud/ec2.py
  scripts/cloud/fabfile.py
  scripts/misc/create_full_geonode_db.py
  scripts/misc/upload.py
Labels: cla-signed, python-3

#5384 [Issue #4267] Make GeoNode migrations Python3 compatible
  geonode/base/migrations/0027_auto_20170801_1228_squashed_0037_auto_20190222_1347.py
  geonode/base/migrations/0028_curatedthumbnail.py
  geonode/base/migrations/0029_auto_20171114_0341.py
  geonode/base/migrations/0033_auto_20180330_0951.py
  geonode/base/migrations/0037_auto_20190222_1347.py
  geonode/base/migrations/24_initial.py
  geonode/base/migrations/24_to_26.py
  geonode/base/migrations/26_to_27.py
  geonode/client/migrations/0001_initial.py
  geonode/client/migrations/0002_auto_20180412_1039.py
  geonode/client/migrations/0002_auto_20180412_1039_squashed_0005_auto_20181015_1201.py
  geonode/documents/migrations/0028_auto_20170801_1228_squashed_0035_auto_20190404_0820.py
  geonode/documents/migrations/24_initial.py
  geonode/groups/migrations/0027_auto_20180105_1631_squashed_0028_auto_20180606_1543.py
  geonode/groups/migrations/24_initial.py
  geonode/layers/migrations/0027_auto_20170801_1228_squashed_0033_auto_20180606_1543.py
  geonode/layers/migrations/0032_auto_20180424_1638.py
  geonode/layers/migrations/0033_auto_20180606_1543.py
  geonode/layers/migrations/24_initial.py
  geonode/layers/migrations/24_to_26.py
  geonode/maps/migrations/0025_auto_20170801_1228_squashed_0032_auto_20190404_0820.py
  geonode/monitoring/migrations/0001_monitoring_init.py
  geonode/monitoring/migrations/0003_monitoring_resources.py
  geonode/monitoring/migrations/0004_monitoring_metric_type.py
  geonode/monitoring/migrations/0005_monitoring_ows_service.py
  geonode/monitoring/migrations/0006_monitoring_path_text.py
  geonode/monitoring/migrations/0007_monitoring_exception_message.py
  geonode/monitoring/migrations/0008_monitoring_notifications_check.py
  geonode/monitoring/migrations/0010_metric_unit.py
  geonode/monitoring/migrations/0011_notification_def.py
  geonode/monitoring/migrations/0012_notifications_service.py
  geonode/monitoring/migrations/0015_notification_grace_period.py
  geonode/monitoring/migrations/0016_notification_severity.py
  geonode/monitoring/migrations/0019_notification_check_def_link.py
  geonode/monitoring/migrations/0021_auto_20180301_0932.py
  geonode/monitoring/migrations/0025_auto_20190813_0808.py
  geonode/monitoring/migrations/0026_auto_20190821_0736.py
  geonode/monitoring/migrations/0028_auto_20190830_1018.py
  geonode/people/migrations/0025_auto_20170924_0932_squashed_0028_auto_20180606_1543.py
  geonode/people/migrations/0026_auto_20171120_0730.py
  geonode/people/migrations/0028_auto_20180606_1543.py
  geonode/people/migrations/24_initial.py
  geonode/qgis_server/migrations/0001_initial.py
  geonode/services/migrations/0025_harvestjob.py
  geonode/services/migrations/0026_auto_20171130_0600_squashed_0041_auto_20190404_0820.py
  geonode/services/migrations/0030_auto_20171212_0518.py
  geonode/services/migrations/0035_auto_20180327_0846.py
  geonode/services/migrations/0036_auto_20180331_1039.py
  geonode/services/migrations/24_initial.py
  geonode/themes/migrations/0001_initial.py
  geonode/themes/migrations/0002_auto_20181015_1208.py
  geonode/themes/migrations/0002_auto_20181015_1208_squashed_0003_remove_geonodethemecustomization_identifier.py
  geonode/themes/migrations/0003_auto_20190503_1742.py
  geonode/themes/migrations/0004_auto_20190503_1817.py
  geonode/themes/migrations/0005_auto_20190510_1335.py
  geonode/themes/migrations/0006_geonodethemecustomization_body_text_color.py
  geonode/themes/migrations/0007_auto_20190510_1545.py
  geonode/themes/migrations/0008_auto_20191122_1714.py
  geonode/themes/migrations/0009_geonodethemecustomization_footer_bg_color.py
  geonode/upload/migrations/24_initial.py
Labels: cla-signed, python-3

#5373 [Issue #4276] Upgrade services for Python 2.7/3 compatibility
  geonode/services/management/commands/importservice.py
  geonode/services/models.py
  geonode/services/serviceprocessors/base.py
  geonode/services/serviceprocessors/handler.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/test_selenium.py
  geonode/services/tests.py
  geonode/services/views.py
Labels: cla-signed, python-3

#5376 [Issue #4276] Upgrade geonode for Python 2.7/3 compatibility
  geonode/decorators.py
  geonode/middleware.py
  geonode/settings.py
  geonode/utils.py
Labels: cla-signed, python-3

#5370 [Issue #4276] Upgrade proxy for Python 2.7/3 compatibility
  geonode/proxy/templatetags/proxy_lib_tags.py
  geonode/proxy/tests.py
  geonode/proxy/views.py
Labels: cla-signed, python-3

#5372 [Issue #4276] Upgrade security for Python 2.7/3 compatibility
  geonode/security/middleware.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/security/views.py
Labels: cla-signed, python-3

#5374 [Issue #4276] Upgrade tests for Python 2.7/3 compatibility
  geonode/tests/bdd/conftest.py
  geonode/tests/bdd/e2e/conftest.py
  geonode/tests/bdd/e2e/fixtures/browser.py
  geonode/tests/csw.py
  geonode/tests/integration.py
  geonode/tests/smoke.py
  geonode/tests/suite/runner.py
  geonode/tests/utils.py
  package/debian/control
  requirements.txt
Labels: cla-signed, python-3

#5397 Revert "[Issue #4276] Upgrade tests for Python 2.7/3 compatibility"
  geonode/tests/bdd/conftest.py
  geonode/tests/bdd/e2e/conftest.py
  geonode/tests/bdd/e2e/fixtures/browser.py
  geonode/tests/csw.py
  geonode/tests/integration.py
  geonode/tests/smoke.py
  geonode/tests/suite/runner.py
  geonode/tests/utils.py
  package/debian/control
  requirements.txt
Labels: cla-signed

#5394 [Fixes #5392][Performance] Put meaningful generic thumbs if thumbnail generation fails some some reason
  geonode/base/models.py
  geonode/catalogue/views.py
  geonode/documents/admin.py
Labels: backport 2.10.x, cla-signed, performance

#5382 [Issue #4276] update geonode/people
  geonode/people/forms.py
  geonode/people/languages.py
  geonode/people/management/commands/setupsociallogins.py
  geonode/people/migrations/0025_auto_20170924_0932.py
  geonode/people/migrations/0025_auto_20170924_0932_squashed_0028_auto_20180606_1543.py
  geonode/people/migrations/0026_auto_20171120_0730.py
  geonode/people/migrations/0027_auto_20180414_2120.py
  geonode/people/migrations/0028_auto_20180606_1543.py
  geonode/people/migrations/24_initial.py
  geonode/people/models.py
  geonode/people/tests.py
  geonode/people/timezones.py
  geonode/people/utils.py
Labels: cla-signed

#5390 [Issue #4276] update geonode/base
  geonode/base/admin.py
  geonode/base/autocomplete_light_registry.py
  geonode/base/forms.py
  geonode/base/management/commands/backup.py
  geonode/base/management/commands/fixsitename.py
  geonode/base/management/commands/helpers.py
  geonode/base/management/commands/load_thesaurus.py
  geonode/base/management/commands/migrate_baseurl.py
  geonode/base/management/commands/migrate_layers.py
  geonode/base/management/commands/migrate_notifications.py
  geonode/base/management/commands/restore.py
  geonode/base/management/commands/set_all_layers_alternate.py
  geonode/base/management/commands/set_all_layers_metadata.py
  geonode/base/management/commands/set_all_layers_public.py
  geonode/base/management/commands/updategeoip.py
  geonode/base/migrations/0027_auto_20170801_1228.py
  geonode/base/migrations/0027_auto_20170801_1228_squashed_0037_auto_20190222_1347.py
  geonode/base/migrations/0028_curatedthumbnail.py
  geonode/base/migrations/0028_resourcebase_is_approved.py
  geonode/base/migrations/0029_auto_20171114_0341.py
  geonode/base/migrations/0029_resourcebase_last_updated.py
  geonode/base/migrations/0030_auto_20180309_0833.py
  geonode/base/migrations/0030_resourcebase_created.py
  geonode/base/migrations/0031_auto_20180309_0837.py
  geonode/base/migrations/0032_auto_20180329_1844.py
  geonode/base/migrations/0033_auto_20180330_0951.py
  geonode/base/migrations/0034_auto_20180606_1543.py
  geonode/base/migrations/0035_resourcebase_dirty_state.py
  geonode/base/migrations/0036_auto_20190129_1433.py
  geonode/base/migrations/0037_auto_20190222_1347.py
  geonode/base/migrations/24_initial.py
  geonode/base/migrations/24_to_26.py
  geonode/base/migrations/26_to_27.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/base/tests.py
  geonode/base/utils.py
Labels: cla-signed, python-3

#5356 [Fixes #5365] Setup code moved to geonode-selenium container
  .travis.yml
Labels: backport 2.10.x, cla-signed

#5405 [Issue #4276] Upgrade poster and geonode/tests for Python 2.7/3 compatibility
  geonode/tests/bdd/conftest.py
  geonode/tests/bdd/e2e/conftest.py
  geonode/tests/bdd/e2e/fixtures/browser.py
  geonode/tests/csw.py
  geonode/tests/integration.py
  geonode/tests/smoke.py
  geonode/tests/suite/runner.py
  geonode/tests/utils.py
  geonode/upload/tests/integration.py
  package/debian/control
  requirements.txt
Labels: cla-signed, python-3

#5425 [Regression][Fixes #5420] Cannot upload rasters on SPCGeoNode
  .travis.yml
  geonode/settings.py
Labels: backport 2.10.x, cla-signed, regression

#5430 [Fixes #5429] Layer feature info templates are not used inside maps
  .travis.yml
  docs/install/core/index.rst
  docs/install/project/index.rst
  geonode/geoserver/helpers.py
  geonode/geoserver/views.py
  geonode/maps/models.py
  geonode/maps/tests.py
  geonode/utils.py
  scripts/spcgeonode/django/Dockerfile
Labels: backport 2.10.x, cla-signed
