Repository GeoNode/geonode, pull requests merged in 2020-08, with the labels that each got.

#6302 [Fixes #6301] GeoNode Custom Theme
  geonode/settings.py
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
  geonode/templates/index.html
  geonode/themes/admin.py
  geonode/themes/context_processors.py
  geonode/themes/migrations/0011_auto_20200727_1451.py
  geonode/themes/models.py
  requirements.txt
Labels: backport 3.x, cla-signed

#6333 [Fixes #6332] In home page show only ISO categories currently assigned to some dataset
  geonode/base/templates/base/iso_categories.html
  geonode/base/templatetags/base_tags.py
  geonode/base/tests.py
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
  geonode/templates/index.html
Labels: backport 3.x, cla-signed

#6304 [Fixes #6303] GeoServer fails to startup after adding multiple admin users
  scripts/spcgeonode/geoserver/docker-entrypoint.sh
Labels: backport 3.x, cla-signed

#6336 - Bump GeoServer to version 2.17.2
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose.async.yml
  docker-compose.yml
  geonode/security/tests.py
  scripts/docker/env/development/geoserver.env
  scripts/docker/env/production/geoserver.env
  scripts/spcgeonode/geoserver/Dockerfile
Labels: backport 3.x, cla-signed, dependencies, security

#6338 Deps djangorestframework 3.8.2
  requirements.txt
Labels: backport 3.x, cla-signed, dependencies

#6361 [Fixes #6360] Allow only admins to edit/create keywords
  geonode/base/forms.py
  geonode/decorators.py
  geonode/documents/tests.py
  geonode/documents/views.py
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/maps/tests.py
  geonode/maps/views.py
Labels: backport 3.x, cla-signed

#6375 [Fixes #6373] Fix Polish translation
  geonode/locale/pl/LC_MESSAGES/django.mo
  geonode/locale/pl/LC_MESSAGES/django.po
  geonode/locale/pl/LC_MESSAGES/djangojs.mo
  geonode/locale/pl/LC_MESSAGES/djangojs.po
Labels: backport 3.x, cla-signed, translations

#6390 [Fixes #6388] Error when installing core GeoNode into virtual environ…
  setup.py
Labels: backport 3.x, cla-signed, dependencies
