Repository GeoNode/geonode, pull requests merged in 2020-02, with the labels that each got.

#5590 [Fixes #5584] Added dutch sorted languages
  geonode/settings.py
Labels: cla-signed

#5588 [Fixes #5587] Set permissions for current user when DEFAULT_ANONYMOUS…
  geonode/templates/_permissions_form_js.html
Labels: cla-signed

#5578 [Fixes #5577] Vector layer does NOT have geometry or any attributes
  geonode/geoserver/helpers.py
  geonode/layers/utils.py
Labels: cla-signed

#5565 [Fixes #5562] Formatting issues at Develop documentation
  docs/devel/workshops/index.rst
Labels: backport 2.10.x, cla-signed

#5586 Fixes: #5585 pg_dump is failing because of version missmatch
  scripts/spcgeonode/pgdumper/Dockerfile
Labels: backport 2.10.x, cla-signed

#5553 [Fixes #5564] WMS/GeoNode Service store unpickable objects on request.session
  geonode/services/serviceprocessors/base.py
  geonode/services/serviceprocessors/handler.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/views.py
Labels: cla-signed

#5582 [Fixes #4346] searching by extent
  geonode/base/templatetags/base_tags.py
  geonode/upload/utils.py
Labels: cla-signed

#5567 [Fix #5576] Fix set thumbnail method under editing tools
  geonode/compat.py
Labels: cla-signed

#5559 [Fixes #5558] Adding duplicate services throws a ValidationError
  geonode/services/forms.py
  geonode/services/tests.py
Labels: cla-signed

#5601 Add import path for pip 20.0+, retain backup hack pip session in case…
  setup.py
Labels: cla-signed, dependencies

#5598 [Fixes #5437] API endpoints reveal too much information - 2.10.x
  docs/basic/settings/index.rst
  geonode/api/api.py
  geonode/api/authorization.py
  geonode/api/tests.py
  geonode/groups/tests.py
  geonode/settings.py
Labels: cla-signed

#5602 [Fixes #5437] API endpoints reveal too much information
  docs/basic/settings/index.rst
  geonode/api/api.py
  geonode/api/authorization.py
  geonode/api/tests.py
  geonode/groups/tests.py
  geonode/settings.py
Labels: cla-signed

#5616 Upgrade to Django 2.2.10
  requirements.txt
Labels: cla-signed, dependencies, security

#5617 Upgrade to Django 1.11.28
  requirements.txt
Labels: cla-signed, dependencies, security

#5631 Bump bootstrap from 3.4.0 to 3.4.1 in /geonode/static
  geonode/static/package.json
Labels: backport 2.10.x, cla-signed, dependencies, in progress, security

#5632 Bump bootstrap from 3.4.0 to 3.4.1 in /geonode/static
  geonode/static/package.json
Labels: cla-signed, dependencies, in progress, security

#5600 - Bump to GeoServer 2.16.2
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose.async.yml
  docker-compose.yml
  docs/install/core/index.rst
  docs/install/project/index.rst
  geonode/geoserver/helpers.py
  geonode/monitoring/service_handlers.py
  geonode/security/tests.py
  package/geoserver/rpm/SPECS/geoserver.spec
  requirements.txt
  scripts/docker/env/development/geoserver.env
  scripts/docker/env/production/geoserver.env
  scripts/spcgeonode/geoserver/Dockerfile
Labels: cla-signed

#5633 [Fixes #5520] Change assertTrue to assertEqual to verify response content type value.
  geonode/documents/renderers.py
  geonode/geoserver/helpers.py
  geonode/layers/views.py
  geonode/security/tests.py
Labels: cla-signed

#5634 [Fixes #5599] set_layers_permissions duplicate assignment
  geonode/layers/management/commands/set_layers_permissions.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/security/models.py
Labels: backport 2.10.x, cla-signed

#5640 [Fixes #5593] Users Avatar and Groups Logo appear as broken img
  geonode/groups/models.py
  geonode/groups/templates/groups/_group_list_item.html
  geonode/groups/templates/groups/_group_profile_list_item.html
  geonode/groups/templates/groups/group_detail.html
  geonode/groups/templatetags/groups_tags.py
  geonode/people/templates/people/profile_detail.html
  geonode/templates/search/_group_snippet.html
  requirements.txt
Labels: backport 2.10.x, cla-signed

#5647 [Fixes #5646] Set skip_authorization for older setups
  scripts/spcgeonode/django/initialize.py
Labels: backport 2.10.x, cla-signed

#5650 [Fixes #5646] Set skip_authorization for older setups
  scripts/spcgeonode/django/initialize.py
Labels: cla-signed

#5649 [Fixes #5648] '^rest/workspaces/(?P<workspace>\w+)/styles' URL is redundant and wrong
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/urls.py
Labels: backport 2.10.x, cla-signed

#5664 [Fixes #5656] Typo in on_delete at groups
  geonode/groups/models.py
Labels: backport 2.10.x, cla-signed

#5666 [FIXES #5639] Group membership is ignored for layer permissions
  AUTHORS
  geonode/groups/models.py
  geonode/groups/views.py
Labels: backport 2.10.x, cla-signed

#5672 Add import path for pip 20.0+, retain backup hack pip session in case…
  setup.py
Labels: cla-signed

#5683 [Fixes #5682] Thumbnails broken for RemoteServices using a invalid WMS GetCapabilities request
  geonode/base/models.py
  geonode/layers/utils.py
  geonode/security/utils.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
Labels: backport 2.10.x, cla-signed

#5681 Making ContactRole resource field required. Fixes #5566
  geonode/base/migrations/0034_auto_20200212_0410.py
  geonode/base/migrations/0035_auto_20200212_0428.py
  geonode/base/models.py
Labels: backport 2.10.x, cla-signed

#5684 [Backport to 2.10.x][Fixes #5682] Thumbnails broken for RemoteServices using a invalid WM…
  geonode/base/models.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/security/utils.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
Labels: cla-signed

#5701 [Backport to 2.10.x][Fixes #5699] Wrong resource number shown in group and group categori…
  .travis.yml
  Dockerfile
  docs/devel/installation/index.rst
  docs/install/core/index.rst
  docs/install/project/index.rst
  geonode/api/api.py
  geonode/api/resourcebase_api.py
  geonode/base/management/commands/updategeoip.py
  geonode/geoserver/views.py
  requirements.txt
  scripts/cloud/fabfile.py
  scripts/spcgeonode/django/Dockerfile
  tasks.py
Labels: cla-signed

#5700 [Fixes #5699] Wrong resource number shown in group and group categori…
  geonode/api/api.py
  geonode/api/resourcebase_api.py
  geonode/base/management/commands/updategeoip.py
  geonode/geoserver/views.py
Labels: cla-signed

#5720 Add pre-commit and black
  .pre-commit-config.yaml
  pyproject.toml
  requirements_dev.txt
Labels: cla-signed

#5739 Fix CI and improve pyproject.toml/setup.py
  .travis.yml
  pyproject.toml
  requirements.txt
  setup.py
Labels: cla-signed

#5744 [Fixes #5743] Add codecov to Selenium tests
  .travis.yml
Labels: cla-signed

#5766 Python 3 syntax fixes
  geonode/base/models.py
  geonode/documents/models.py
  geonode/favorite/models.py
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/groups/models.py
  geonode/layers/models.py
  geonode/maps/models.py
  geonode/monitoring/models.py
  geonode/people/migrations/0025_auto_20170924_0932_squashed_0028_auto_20180606_1543.py
  geonode/people/migrations/0026_auto_20171120_0730.py
  geonode/people/models.py
  geonode/people/profileextractors.py
  geonode/qgis_server/management/commands/import_qgis_styles.py
  geonode/services/models.py
  geonode/tests/suite/runner.py
  geonode/themes/models.py
  geonode/upload/models.py
Labels: cla-signed

#5768 - Set API_LOCKDOWN = False by default
  docs/basic/settings/index.rst
  geonode/api/tests.py
  geonode/settings.py
Labels: cla-signed
