Repository GeoNode/geonode, pull requests merged in 2020-01, with the labels that each got.

#5447 [Fixes #5419] Hierarchical keyword and [Fixes #5446] Binary files removed /lib
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
  geonode/static/gruntfile.js
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/jquery-ui.theme.css
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/static_dependencies.json
Labels: backport 2.10.x, cla-signed, frontend

#5465 [Fixes #5463] Change geolite2-city endpoint
  geonode/base/management/commands/updategeoip.py
Labels: backport 2.10.x, cla-signed

#5472 [Fixes #5463] Change geolite2-city endpoint
  geonode/base/management/commands/updategeoip.py
Labels: backport 2.10.x, cla-signed

#5469 [Fixes #5467] Gender neutral terminology
  geonode/templates/500.html
Labels: backport 2.10.x, cla-signed

#5470 [Fixes #5468] Correct 'Favoriten' in german Translation
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
Labels: backport 2.10.x, cla-signed

#5477 Add lucernae to CLA
  .clabot
Labels: cla-signed

#5474 [Fixes #5464] Update docs for Tomcat download
  docs/install/core/index.rst
Labels: backport 2.10.x, cla-signed, docs

#5417 [Fixes #5416] LIKE filter on layer download tab doesn't let setting a pattern value
  geonode/layers/templates/layers/layer_detail.html
Labels: backport 2.10.x, cla-signed

#5475 [Fixes #5476] Possible typo in SPCGeonode docker-compose.yml file
  scripts/spcgeonode/docker-compose.yml
Labels: backport 2.10.x, cla-signed

#5480 Backport 5474 to 2.10.x
  docs/install/core/index.rst
  geonode/layers/templates/layers/layer_detail.html
  geonode/maps/templates/maps/map_detail.html
Labels: cla-signed

#5481 [Backport to 2.10.x][Fixes #5416] LIKE filter on layer download tab doesn't let setting a pattern value
  geonode/layers/templates/layers/layer_detail.html
Labels: cla-signed

#5482 [Backport to 2.10.x] Fix environment variable references (#5475)
  scripts/spcgeonode/docker-compose.yml
Labels: cla-signed

#5491 Merge pull request #5490 from GeoNode/dependabot/pip/django-mapstore-adapter-1.0.16
  requirements.txt
Labels: cla-signed

#5492 [Fixes #5486] "resolve_object" get confused when present a remote layer with alternate similar to the local one
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
Labels: backport 2.10.x, cla-signed

#5496 [Backport 2.10.x][Fixes #5486] "resolve_object" get confused when present a remote lay…
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
Labels: cla-signed

#5494 [Fixes #5493] User permissions not synched when DEFAULT_ANONYMOUS_VIEW_PERMISSION is True
  .travis.yml
  geonode/api/tests.py
  geonode/geoserver/helpers.py
  geonode/geoserver/signals.py
  geonode/geoserver/tests/integration.py
  geonode/geoserver/views.py
  geonode/people/migrations/0026_auto_20200109_1600.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/settings.py
  geonode/tests/integration.py
  geonode/upload/tests/test_settings.py
  pavement.py
  scripts/docker/env/production/geoserver.env
Labels: backport 2.10.x, cla-signed

#5498 [Fixes #5497] W*S on QGis not authenticating
  geonode/geoserver/tests/test_helpers.py
  geonode/geoserver/views.py
Labels: backport 2.10.x, cla-signed

#5499 [Backport 2.10.x][Fixes #5493] User permissions not synched when DEFAULT_ANONYMOUS_VIEW_PERMISSION is True
  .travis.yml
  geonode/api/tests.py
  geonode/geoserver/helpers.py
  geonode/geoserver/signals.py
  geonode/geoserver/tests/integration.py
  geonode/geoserver/views.py
  geonode/people/migrations/0026_auto_20200109_1600.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/settings.py
  geonode/tests/integration.py
  geonode/upload/tests/test_settings.py
  pavement.py
  scripts/docker/env/production/geoserver.env
Labels: cla-signed

#5500 [Backport 2.10.x][Fixes #5497] W*S on QGis not authenticating
  geonode/geoserver/tests/test_helpers.py
  geonode/geoserver/views.py
Labels: cla-signed

#5505 [Fixes #5504] Map Thumbnails Broken
  geonode/layers/utils.py
  geonode/local_settings.py.geoserver.sample
  geonode/maps/tests.py
  geonode/security/utils.py
  geonode/settings.py
  geonode/utils.py
  package/support/geonode.local_settings
  requirements.txt
Labels: backport 2.10.x, cla-signed

#5506 [Fixes #5504] Map Thumbnails Broken
  geonode/layers/utils.py
  geonode/local_settings.py.geoserver.sample
  geonode/maps/tests.py
  geonode/security/utils.py
  geonode/settings.py
  geonode/utils.py
  package/support/geonode.local_settings
  requirements.txt
Labels: cla-signed

#5507 - Bump to GeoServer 2.15.4
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose.async.yml
  docker-compose.yml
  docs/install/core/index.rst
  docs/install/project/index.rst
  geonode/local_settings.py.geoserver.sample
  geonode/settings.py
  scripts/spcgeonode/geoserver/Dockerfile
Labels: backport 2.10.x, cla-signed

#5524 [Backport 5507 to 2.10.x] - Bump to GeoServer 2.15.4
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose.async.yml
  docker-compose.yml
  docs/install/core/index.rst
  docs/install/project/index.rst
  geonode/local_settings.py.geoserver.sample
  geonode/settings.py
  scripts/spcgeonode/geoserver/Dockerfile
Labels: cla-signed

#5516 Update JETTY_RUNNER_URL to secure HTTPS equivalent
  dev_config.yml
Labels: backport 2.10.x, cla-signed

#5533 Adding documentation for Develop section
  docs/devel/index.rst
  docs/devel/installation/index.rst
  docs/devel/installation/install_gdal_for_development.rst
  docs/devel/running/index.rst
  docs/devel/workshops/index.rst
Labels: backport 2.10.x, docs

#5528 Fix mixed content when logged in
  docs/install/core/index.rst
Labels: backport 2.10.x, docs

#5534 fix typo in docs/devel/installation/index.rst
  docs/devel/installation/index.rst
Labels: backport 2.10.x, cla-signed, docs

#5538 Fix elasticsearch versions
  docker-compose.async.yml
  requirements.txt
Labels: cla-signed, dependencies

#5561 [Fixes #5560] Cannot upload XML layer metadata
  geonode/layers/metadata.py
  geonode/layers/views.py
Labels: cla-signed

#5539 [Issue #5555] Improve speed of terminating geoserver
  pavement.py
Labels: cla-signed, feature

#5541 [Fixes #5554] Fixed blank page when deleting announcements
  geonode/templates/announcements/announcement_confirm_delete.html
Labels: cla-signed

#5540 [Fixes #5542] Fixes Developing documentation
  docs/devel/installation/img/geonode-gui.png
  docs/devel/installation/img/server-is-ready.png
  docs/devel/installation/index.rst
  docs/devel/workshops/img/doi.png
  docs/devel/workshops/img/explore-my-layers.png
  docs/devel/workshops/img/geocollection-menu.png
  docs/devel/workshops/img/geocollections-admin.png
  docs/devel/workshops/img/geocollections-details.png
  docs/devel/workshops/img/geonode-is-awesome.png
  docs/devel/workshops/img/geonode-project-gui.png
  docs/devel/workshops/img/logged-in-geonode.png
  docs/devel/workshops/img/red-background.png
  docs/devel/workshops/index.rst
Labels: backport 2.10.x, cla-signed, docs

#5557 [Fixes #5556] Fixes permission logic for workshop documentation
  docs/devel/workshops/img/view-permission.png
  docs/devel/workshops/index.rst
Labels: backport 2.10.x, cla-signed

#5583 Add travislbrundage to clabot
  .clabot
Labels: cla-signed
