Repository GeoNode/geonode, pull requests merged in 2020-05, with the labels that each got.

#6049 [Fixes #6048][SPCGeoNode] HTTPS_PORT not considered by envsubst
  scripts/spcgeonode/docker-compose.yml
  scripts/spcgeonode/nginx/docker-entrypoint.sh
  scripts/spcgeonode/nginx/nginx.conf.envsubst
  scripts/spcgeonode/nginx/nginx.https.available.conf.envsubst
Labels: cla-signed

#6051 pt_pt translation update
  geonode/locale/pt/LC_MESSAGES/django.mo
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/djangojs.mo
  geonode/locale/pt/LC_MESSAGES/djangojs.po
Labels: cla-signed

#6054 [Fixes #6027] Use osm source as default source type for geoext
  geonode/maps/tests.py
  geonode/utils.py
Labels: cla-signed

#6053 [Fixes #6052][Backup/Restore] Improve the restore of folders on the base of backup filter settings
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
  geonode/br/management/commands/utils/utils.py
  geonode/br/tests/test_restore.py
Labels: cla-signed

#6060 [Backport to 2.10.x][Fixes #6052][Backup/Restore] Improve the restore…
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
  geonode/br/management/commands/utils/utils.py
  geonode/br/tests/test_restore.py
Labels: cla-signed

#6070 [Fixes #6068] download filter dropdown shows wrong attributenames / [Fixes #6069] download filter values are not properly filled with unique values
  geonode/layers/models.py
  geonode/layers/templates/layers/layer_detail.html
Labels: cla-signed

#6078 - Travis fix
  geonode/security/tests.py
Labels: cla-signed

#6082 Update gnip.md
  .github/ISSUE_TEMPLATE/gnip.md
Labels: cla-signed

#6087 [FIX #6086] extend group slug length
  geonode/groups/forms.py
  geonode/groups/migrations/0034_auto_20200512_1431.py
  geonode/groups/models.py
Labels: cla-signed

#6089 [Fixes #6088] WCS download links are wrong for WCS 2.0.1
  geonode/geoserver/ows.py
  geonode/geoserver/tests/test_server.py
Labels: cla-signed

#6090 [Fixes #6080] Error Upload KML extension
  geonode/upload/utils.py
Labels: cla-signed

#6092 [FIX #6091] remove empty results dropdown
  geonode/static/geonode/js/search/autocomplete.js
Labels: cla-signed

#6094 [Fixes #6093] Trying to add more than one member to a Group, results adding only the last one
  geonode/groups/forms.py
Labels: cla-signed

#6096 [FIX #6095] Scroll page after load/load new resources
  geonode/static/geonode/js/search/search.js
  geonode/templates/base.html
  geonode/templates/search/_pagination.html
Labels: cla-signed

#6098 [FIX #6097] Abort autocomplete request (message create)
  geonode/static/geonode/js/messages/message_recipients_autocomplete.js
  geonode/static/geonode/js/messages/message_recipients_autocomplete_es5.js
  geonode/static/geonode/js/messages/message_recipients_autocomplete_es5.js.map
Labels: cla-signed

#6100 [Fixes #6099] Move triggering of notifications out of notification_sender signals for ResourceBase
  geonode/base/models.py
  geonode/base/views.py
  geonode/documents/tests.py
  geonode/documents/views.py
  geonode/geoserver/helpers.py
  geonode/geoserver/views.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/maps/models.py
  geonode/maps/views.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/social/signals.py
  geonode/tests/integration.py
  geonode/upload/upload.py
Labels: cla-signed

#6107 [Minor] Format syntax
  geonode/api/resourcebase_api.py
  geonode/base/populate_test_data.py
  geonode/catalogue/backends/generic.py
  geonode/layers/models.py
  geonode/maps/models.py
  geonode/maps/utils.py
  geonode/monitoring/models.py
  geonode/monitoring/utils.py
  geonode/monitoring/views.py
  geonode/proxy/templatetags/proxy_lib_tags.py
  geonode/proxy/tests.py
  geonode/proxy/views.py
  geonode/qgis_server/helpers.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/utils.py
Labels: backport 3.x, cla-signed, enhancement

#6108 [Hardening] Allowing huge zip files everywhere
  geonode/layers/forms.py
  geonode/layers/utils.py
  geonode/qgis_server/views.py
  geonode/upload/files.py
  geonode/upload/tests/__init__.py
  geonode/upload/tests/integration.py
  geonode/upload/upload.py
  geonode/upload/upload_validators.py
  geonode/upload/utils.py
  geonode/utils.py
Labels: backport 2.10.x, cla-signed

#6120 Backports to 3.x
  requirements.txt
Labels: cla-signed

#6123 Fixes #6122 Update spanish translation
  geonode/locale/es/LC_MESSAGES/django.mo
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/djangojs.mo
  geonode/locale/es/LC_MESSAGES/djangojs.po
Labels: backport 2.10.x, backport 3.x, cla-signed

#6130 [Translation] Finish pt_pt translations
  geonode/locale/pt/LC_MESSAGES/django.mo
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/djangojs.mo
  geonode/locale/pt/LC_MESSAGES/djangojs.po
Labels: cla-signed, translations
