Repository GeoNode/geonode, pull requests merged in 2020-12, with the labels that each got.

#6688 [Fixes: #6687] Update lxml
  requirements.txt
Labels: backport 3.x, cla-signed, security

#6686 [Fixes #6685] GNIP-79: GeoNode REST APIs (v2)
  .gitignore
  .travis.yml
  geonode/api/urls.py
  geonode/base/api/__init__.py
  geonode/base/api/filters.py
  geonode/base/api/pagination.py
  geonode/base/api/permissions.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/urls.py
  geonode/base/api/views.py
  geonode/base/bbox_utils.py
  geonode/base/migrations/0049_resourcebase_resource_type.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/base/urls.py
  geonode/documents/api/__init__.py
  geonode/documents/api/permissions.py
  geonode/documents/api/serializers.py
  geonode/documents/api/tests.py
  geonode/documents/api/urls.py
  geonode/documents/api/views.py
  geonode/documents/urls.py
  geonode/layers/api/__init__.py
  geonode/layers/api/permissions.py
  geonode/layers/api/serializers.py
  geonode/layers/api/tests.py
  geonode/layers/api/urls.py
  geonode/layers/api/views.py
  geonode/layers/tests.py
  geonode/layers/urls.py
  geonode/maps/api/__init__.py
  geonode/maps/api/permissions.py
  geonode/maps/api/serializers.py
  geonode/maps/api/tests.py
  geonode/maps/api/urls.py
  geonode/maps/api/views.py
  geonode/maps/urls.py
  geonode/qgis_server/views.py
  geonode/security/utils.py
  geonode/settings.py
  geonode/static/build.sh
  geonode/static/geonode/js/crop_widget/crop_widget_es5.js.map
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/tagify.css
  geonode/static/lib/js/angular-sanitize.min.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/lib/js/openlayers-plugins.min.js
  geonode/static/lib/js/tagify.min.js
  geonode/static/package.json
  geonode/templates/metadata_detail.html
  geonode/urls.py
  geonode/version.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#6708 [Fixes: #6707] Update German Translation
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
  geonode/locale/de/LC_MESSAGES/djangojs.mo
  geonode/locale/de/LC_MESSAGES/djangojs.po
Labels: backport 3.x, cla-signed, translations

#6718 [Fixes #6717] Infinite GetMap requests on Thumbnail creation
  geonode/geoserver/helpers.py
Labels: backport 3.x, cla-signed

#6716 [Fixes #6715] Improve Upload (Importer) speed and code quality
  geonode/api/resourcebase_api.py
  geonode/base/forms.py
  geonode/client/hooksets.py
  geonode/documents/views.py
  geonode/geoserver/tasks.py
  geonode/layers/tasks.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/messaging/consumer.py
  geonode/monitoring/management/commands/render_metrics.py
  geonode/monitoring/management/commands/updategeoip.py
  geonode/monitoring/middleware.py
  geonode/proxy/views.py
  geonode/qgis_server/views.py
  geonode/security/models.py
  geonode/security/utils.py
  geonode/settings.py
  geonode/upload/tests/__init__.py
  geonode/upload/tests/integration.py
  geonode/upload/upload.py
  geonode/upload/views.py
  geonode/utils.py
  scripts/misc/create_full_geonode_db.py
Labels: cla-signed

#6759 [Fixes #6758] Bump base Image for Django Docker
  Dockerfile
Labels: backport 3.x, cla-signed, security

#6746 [Fixes #6742] request download permission not shown
  geonode/layers/templates/layers/layer_detail.html
Labels: cla-signed
