Repository GeoNode/geonode, pull requests merged in 2020-10, with the labels that each got.

#6510 [Fixes: #6509] Broken diacritics in Geoserver style
  geonode/geoserver/helpers.py
Labels: backport 3.x, cla-signed

#6513 [Fixes #6511] Missing features in filter in layer download view
  geonode/layers/templates/layers/layer_detail.html
Labels: backport 3.x, cla-signed

#6515 Fixes: #6509 specialchars in sld for zip files
  geonode/upload/upload.py
Labels: backport 3.x, cla-signed

#6526 [Fixes: #6519] Bump jquery to 3.5.1
  geonode/static/geonode/js/messages/message_recipients_autocomplete_es5.js
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/bootstrap-multiselect.css
  geonode/static/lib/css/bootstrap-select.css
  geonode/static/lib/css/bootstrap-table.css
  geonode/static/lib/css/cropper.css
  geonode/static/lib/css/tagify.css
  geonode/static/lib/js/angular-sanitize.min.js
  geonode/static/lib/js/angular.js
  geonode/static/lib/js/angular.min.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/bootstrap-multiselect.js
  geonode/static/lib/js/bootstrap-select.js
  geonode/static/lib/js/bootstrap-table.js
  geonode/static/lib/js/clipboard.js
  geonode/static/lib/js/clipboard.min.js
  geonode/static/lib/js/cropper.js
  geonode/static/lib/js/handlebars.js
  geonode/static/lib/js/handlebars.min.js
  geonode/static/lib/js/jquery.js
  geonode/static/lib/js/jquery.min.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/lib/js/leaflet.js
  geonode/static/lib/js/moment-timezone-with-data.js
  geonode/static/lib/js/openlayers-plugins.min.js
  geonode/static/lib/js/tagify.min.js
  geonode/static/lib/js/underscore.js
  geonode/static/package.json
Labels: backport 3.x, cla-signed, dependencies

#6517 [Fixes #6525] changed order of layers and services in fixtures-list.
  geonode/br/management/commands/restore.py
  geonode/br/management/commands/settings_docker_sample.ini
  geonode/br/management/commands/settings_sample.ini
Labels: backport 3.x, cla-signed

#6064 [Issue #6079] Enable spatial data stores for Django database
  .gitignore
  .travis.yml
  docker-compose.async.yml
  docker-compose.yml
  geonode/api/resourcebase_api.py
  geonode/base/bbox_utils.py
  geonode/base/forms.py
  geonode/base/migrations/0044_resourcebase_bbox_polygon.py
  geonode/base/migrations/0045_auto_20200507_0445.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/base/templatetags/base_tags.py
  geonode/catalogue/templates/geonode_metadata_full.html
  geonode/catalogue/views.py
  geonode/client/templates/leaflet/maps/map_embed.html
  geonode/documents/models.py
  geonode/documents/views.py
  geonode/favorite/tests.py
  geonode/geoserver/createlayer/utils.py
  geonode/geoserver/helpers.py
  geonode/geoserver/signals.py
  geonode/geoserver/tests/test_server.py
  geonode/layers/migrations/0028_auto_20200323_1945.py
  geonode/layers/migrations/0033_merge_20200618_2150.py
  geonode/layers/models.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/maps/templates/maps/map_leaflet.html
  geonode/maps/tests.py
  geonode/qgis_server/signals.py
  geonode/security/tests.py
  geonode/security/views.py
  geonode/serializer.py
  geonode/services/tests.py
  geonode/settings.py
  geonode/tests/integration.py
  geonode/tests/utils.py
  geonode/utils.py
  requirements.txt
  scripts/docker/env/development/django.env
  scripts/spcgeonode/docker-compose.yml
  scripts/spcgeonode/postgis/Dockerfile
  scripts/spcgeonode/postgis/initdb-geonode.sh
  tasks.py
Labels: backport 3.x, cla-signed

#6561 updated de translations: geo limit texts and cart [#6131]
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
Labels: backport 3.x, cla-signed

#6563 fix italian translations
  geonode/locale/en/LC_MESSAGES/django.mo
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/templates/_permissions_form.html
  geonode/templates/index.html
Labels: backport 3.x, cla-signed

#6552 [ISSUE #6551] Minor review of the current advanced resource workflow implementation…
  geonode/api/api.py
  geonode/api/tests.py
  geonode/base/models.py
  geonode/base/templatetags/base_tags.py
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/base/views.py
  geonode/documents/views.py
  geonode/geoserver/createlayer/utils.py
  geonode/geoserver/createlayer/views.py
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/locale/en/LC_MESSAGES/django.mo
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/en/LC_MESSAGES/djangojs.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/djangojs.po
  geonode/maps/views.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/settings.py
  geonode/social/views.py
  geonode/templates/search/_search_content.html
  geonode/templates/search/_type_filters.html
  geonode/upload/upload.py
  geonode/utils.py
  requirements.txt
  setup.cfg
Labels: backport 3.x, cla-signed

#6566 [Fixes #6447] Layer is not replaced
  geonode/base/models.py
  geonode/geoserver/signals.py
  geonode/geoserver/tests/integration.py
  geonode/geoserver/tests/test_helpers.py
  geonode/layers/models.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/tests/integration.py
  geonode/upload/upload.py
  setup.cfg
Labels: backport 3.x, cla-signed

#6584 [Backport to 3.x][Fixes #6447] Layer is not replaced (#6566)
  .travis.yml
  geonode/geoserver/signals.py
  geonode/geoserver/tests/integration.py
  geonode/geoserver/tests/test_helpers.py
  geonode/layers/models.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/tests/integration.py
  geonode/upload/upload.py
  scripts/spcgeonode/docker-compose.yml
  setup.cfg
Labels: cla-signed

#6570 [Fixes #6569][Admin set bulk metadata action] Error 502 when assigning metadata in bulk to all layers from Django admin
  geonode/base/admin.py
Labels: backport 3.x, cla-signed
