Repository GeoNode/geonode, pull requests merged in 2020-03, with the labels that each got.

#5798 [Fixes #5795] utils get_object_or_404 raises exception if query retur…
  geonode/layers/views.py
Labels: cla-signed

#5767 flake8 updates
  pavement.py
  scripts/backup-restore/backup.py
  scripts/backup-restore/gn20_to_24.py
  scripts/backup-restore/gn24_to_24.py
  scripts/backup-restore/helpers.py
  scripts/backup-restore/migrate_layers.py
  scripts/backup-restore/restore.py
  scripts/cloud/demo_site.py
  scripts/cloud/ec2.py
  scripts/cloud/fabfile.py
  scripts/misc/create_full_geonode_db.py
  scripts/spcgeonode/django/initialize.py
Labels: cla-signed

#5797 [Fixes #5796] Add a "DOI" field to the metadata fieldset
  geonode/base/migrations/0036_resourcebase_doi.py
  geonode/base/models.py
  geonode/base/templates/base/_resourcebase_contact_snippet.html
  geonode/base/templates/base/_resourcebase_info_panel.html
  geonode/catalogue/templates/geonode_metadata_full.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
  geonode/templates/metadata_detail.html
  geonode/templates/search/_general_filters.html
Labels: cla-signed

#5811 [Fixes #5809] Use "get_user_model" everywhere in order to allow full pluggable AUTH_USER_MODEL
  geonode/api/tests.py
  geonode/base/forms.py
  geonode/base/management/commands/fixoauthuri.py
  geonode/base/populate_test_data.py
  geonode/catalogue/views.py
  geonode/geoserver/createlayer/utils.py
  geonode/geoserver/management/commands/find_geoserver_broken_layers.py
  geonode/geoserver/signals.py
  geonode/monitoring/tests/integration.py
  geonode/notifications_helper.py
  geonode/people/admin.py
  geonode/people/forms.py
  geonode/people/models.py
  geonode/people/search_indexes.py
  geonode/people/views.py
  geonode/security/tests.py
  geonode/security/views.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/settings.py
  geonode/social/apps.py
  geonode/social/tests.py
  geonode/tests/bdd/e2e/test_login.py
  geonode/upload/tests/integration.py
  scripts/misc/create_full_geonode_db.py
  scripts/spcgeonode/django/initialize.py
Labels: cla-signed

#5813 [Fixes #5812] Error on document removal
  geonode/base/migrations/0037_auto_20200305_1520.py
  geonode/base/models.py
  geonode/documents/migrations/0030_auto_20200305_1520.py
  geonode/documents/models.py
  geonode/groups/migrations/0031_auto_20200305_1522.py
  geonode/groups/models.py
  geonode/monitoring/migrations/0030_auto_20200305_1520.py
  geonode/monitoring/models.py
  geonode/qgis_server/models.py
Labels: cla-signed

#5816 [Fixes #5821] Backup/restore procedure update
  geonode/base/management/commands/backup.py
  geonode/base/management/commands/restore.py
  geonode/base/management/commands/settings.ini
  geonode/layers/models.py
  geonode/utils.py
Labels: cla-signed

#5817 Fixes 5806, 5805 Hide Version & i18n to Whitelist
  geonode/settings.py
  geonode/templates/500.html
  geonode/templates/base.html
Labels: backport 2.10.x, cla-signed

#5818 [Fixes #5819] Thumbnail edit before posting
  geonode/documents/templates/layouts/doc_panels.html
  geonode/static/geonode/css/crop_widget.css
  geonode/static/geonode/js/crop_widget/crop_widget.js
  geonode/static/geonode/js/crop_widget/crop_widget_es5.js
  geonode/static/geonode/js/crop_widget/crop_widget_es5.js.map
  geonode/static/geonode/less/crop_widget.less
  geonode/static/gruntfile.js
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/js/assets.min.js
  geonode/static/package.json
  geonode/static/static_dependencies.json
Labels: cla-signed

#5823 [Fixes #5822] Increase group title length
  geonode/groups/migrations/0031_auto_20200304_1434.py
  geonode/groups/migrations/0032_merge_20200306_1153.py
  geonode/groups/models.py
Labels: cla-signed

#5829 [Fixes #5828] Groups filtering is not working as expected
  geonode/documents/templates/layouts/doc_panels.html
  geonode/static/geonode/js/search/search.js
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/cropper.css
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/clipboard.js
  geonode/static/lib/js/clipboard.min.js
  geonode/static/lib/js/cropper.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/templates/search/_search_user_content.html
Labels: cla-signed

#5826 [Backport to 2.10.x][Fixes #5816] backup and restore update
  geonode/base/management/commands/backup.py
  geonode/base/management/commands/restore.py
  geonode/base/management/commands/settings.ini
  geonode/layers/models.py
  geonode/utils.py
Labels: cla-signed

#5825 [Fixes #5824] Remove set button from documents editing tool
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/urls.py
  geonode/documents/views.py
Labels: cla-signed

#5847 [Fixes #5555] Improved waiting time in start_django and start
  pavement.py
Labels: cla-signed

#5860 [Fixes #5858] Add direct link do "Upload new Document" to Profile page
  geonode/people/templates/people/profile_detail.html
Labels: cla-signed

#5869 [Fixes #5868] GeoNode core docker not setting correctly HTTP protocol and port
  manage.sh
  scripts/docker/env/development/geoserver.env
  scripts/docker/env/production/geoserver.env
  tasks.py
  uwsgi.ini
Labels: cla-signed

#5873 [Fixes #5866] Restore errors
  geonode/base/management/commands/helpers.py
Labels: cla-signed

#5876 [Fixes #5875] GeoNode requirement Python >= 3.6
  .travis.yml
  setup.py
Labels: cla-signed, dependencies

#5877 [Backport to 2.10.x][Fixes #5866] Restore errors
  geonode/base/management/commands/helpers.py
Labels: cla-signed

#5883 - Typo JS: remove jquery-ui.theme.css comment making cache busting to fail
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/jquery-ui.theme.css
Labels: cla-signed, frontend, javascript, minor

#5897 [Fixes #5896] Create MD5 hash file for backup zip
  geonode/base/management/commands/backup.py
  geonode/base/management/commands/helpers.py
Labels: cla-signed

#5894 [Fixes #5893] delete_resources management command
  geonode/base/management/commands/delete_resources.py
  geonode/base/tests.py
Labels: cla-signed

#5895 [Fixes #5836] styling of inbox icons
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/tagify.css
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/clipboard.js
  geonode/static/lib/js/clipboard.min.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/lib/js/tagify.min.js
Labels: cla-signed, frontend

#5900 [Fixes #5899] Check backup archive MD5 on restore
  geonode/base/management/commands/restore.py
Labels: cla-signed

#5851 [Fixes #5849] Read Only and Maintenance modes
  .travis.yml
  geonode/base/admin.py
  geonode/base/fixtures/group_test_data.json
  geonode/base/middleware.py
  geonode/base/migrations/0038_configuration.py
  geonode/base/migrations/0039_auto_20200321_1338.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/base/templates/base/maintenance.html
  geonode/base/templates/base/read_only_violation.html
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/catalogue/metadataxsl/views.py
  geonode/client/templates/leaflet/maps/map_list.html
  geonode/context_processors.py
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/templates/documents/document_list.html
  geonode/favorite/templates/favorite/_favorite.html
  geonode/geoserver/tests/integration.py
  geonode/geoserver/tests/test_server.py
  geonode/groups/migrations/0033_auto_20200321_1349.py
  geonode/groups/models.py
  geonode/groups/templates/groups/category_list.html
  geonode/groups/templates/groups/group_list.html
  geonode/groups/tests.py
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list.html
  geonode/layers/templates/layers/layer_metadata_upload.html
  geonode/layers/templates/layers/layer_replace.html
  geonode/layers/templates/layers/layer_style_upload.html
  geonode/layers/tests.py
  geonode/local_settings.py.geoserver.sample
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_list.html
  geonode/maps/tests.py
  geonode/maps/tests_populate_maplayers.py
  geonode/people/templates/people/profile_detail.html
  geonode/proxy/tests.py
  geonode/qgis_server/migrations/0006_auto_20200321_1349.py
  geonode/qgis_server/models.py
  geonode/security/tests.py
  geonode/services/templates/services/service_list.html
  geonode/settings.py
  geonode/singleton.py
  geonode/social/tests.py
  geonode/templates/500.html
  geonode/templates/announcements/announcement_list.html
  geonode/templates/base.html
  geonode/templates/user_messages/inbox.html
  geonode/tests/base.py
  geonode/tests/integration.py
  geonode/upload/migrations/0026_auto_20200321_1349.py
  geonode/upload/models.py
  geonode/utils.py
  pavement.py
  scripts/misc/create_dbs_travis.sh
  scripts/misc/geoserver_server_setup.sh
Labels: cla-signed

#5881 [Fixes #5680] Update groups to allow managers to promote regular memb…
  geonode/groups/models.py
  geonode/groups/templates/groups/group_members.html
  geonode/groups/tests.py
  geonode/groups/urls.py
  geonode/groups/views.py
  geonode/locale/en/LC_MESSAGES/django.po
Labels: cla-signed

#5903 [Fixes #5901] move backup restore to a separate application
  geonode/base/admin.py
  geonode/base/management/commands/helpers.py
  geonode/base/management/commands/migrate_layers.py
  geonode/base/migrations/0038_delete_backup.py
  geonode/base/migrations/0040_merge_20200321_2245.py
  geonode/base/models.py
  geonode/base/translation.py
  geonode/br/__init__.py
  geonode/br/management/__init__.py
  geonode/br/management/commands/__init__.py
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
  geonode/br/management/commands/settings.ini
  geonode/br/management/commands/utils/__init__.py
  geonode/br/management/commands/utils/utils.py
  geonode/br/tests/__init__.py
  geonode/settings.py
  pavement.py
Labels: cla-signed

#5915 [Fixes 5914] message notification
  geonode/invitations/views.py
  geonode/messaging/__init__.py
  geonode/messaging/notifications.py
  geonode/people/adapters.py
  geonode/people/models.py
  geonode/templates/user_messages/email/email_new_message_message.txt
  geonode/templates/user_messages/email/email_new_message_subject.txt
  geonode/tests/test_message_notifications.py
Labels: cla-signed

#5911 [Fixes #5910] Hide local registration form
  geonode/people/views.py
  geonode/settings.py
  geonode/templates/account/signup.html
  geonode/urls.py
Labels: cla-signed

#5923 [Fixes #5922] Send notification about restore procedure
  geonode/br/management/commands/restore.py
  geonode/br/tasks.py
Labels: cla-signed

#5930 [Fixes #5929] Restore notification email is not sent on success
  geonode/br/management/commands/restore.py
Labels: cla-signed

#5932 [Fixes #5931] Add filtering to usergroups
  geonode/api/api.py
  geonode/api/authorization.py
  geonode/base/fixtures/group_test_data.json
  geonode/groups/views.py
  geonode/tests/test_rest_api.py
Labels: cla-signed

#5937 [Fixes #5936] Backup/Restore with Read-Only mode
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
  geonode/br/tests/__init__.py
  geonode/br/tests/test_backup.py
  geonode/br/tests/test_restore.py
Labels: cla-signed

#5920 [Fixes #5912] Extend resource search api with abstract and purpose fields
  geonode/api/resourcebase_api.py
  geonode/settings.py
  geonode/static/geonode/js/search/search.js
  geonode/templates/base.html
  geonode/templates/index.html
  geonode/templates/search/_text_filter.html
  geonode/tests/test_search.py
Labels: cla-signed

#5934 [Fixes #5933] Filtering logic error on GroupCategoryResource
  geonode/api/api.py
  geonode/groups/tests.py
  geonode/templates/search/_search_user_content.html
Labels: backport 2.10.x, cla-signed

#5938 [Fixes #5667] visual glitch on download formats modal
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
  geonode/static/lib/css/assets.min.css
Labels: cla-signed

#5941 [Fixes #5940] GeoLimits must be stored as native CRS for Raster-type layers
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed
