Repository GeoNode/geonode, pull requests merged in 2020-06, with the labels that each got.

#6155 Fixes #6153 Configure gravatar fallback image
  geonode/settings.py
  scripts/docker/env/development/django.env
  scripts/docker/env/production/django.env
Labels: cla-signed

#6167 - Bump six to 1.15.0
  requirements.txt
Labels: backport 3.x, cla-signed, dependencies

#6183 Fixes #6182 Fixes #6180 RTL template
  geonode/locale/ar/LC_MESSAGES/django.mo
  geonode/locale/ar/LC_MESSAGES/django.po
  geonode/static/geonode/css/geonode-rtl.css
  geonode/static/geonode/css/geonode-rtl.min.css
  geonode/static/geonode/less/geonode-rtl.less
  geonode/static/gruntfile.js
  geonode/templates/base.html
Labels: backport 3.x, cla-signed

#6194 [Fixes #6193] Geonode's "data_dt_filter" backup filter does not apply when a directory to be backed up contains files at it's root.
  geonode/tests/test_utils.py
  geonode/utils.py
Labels: backport 2.10.x, backport 3.x, cla-signed

#6197 - Bump django-mapstore-adapter to version 2.0.4.2
  requirements.txt
Labels: backport 3.x, cla-signed, dependencies
