Repository GeoNode/geonode, pull requests merged in 2020-04, with the labels that each got.

#5943 [Fixes #5942] Sorting is not working on group view
  geonode/groups/templates/groups/_group_profile_list_item.html
  geonode/groups/templates/groups/group_list.html
  geonode/templates/search/_group_snippet.html
Labels: cla-signed

#5945 [Fixes #5944] B/R general fixes
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
Labels: cla-signed

#5946 Fixes #5882 Mapstore fails with version 3.0.0
  geonode/version.py
Labels: cla-signed

#5958 [Issue #5835] GNIP-74 Improvements: toggle GWC cache instead of removing it
  geonode/security/tests.py
  geonode/security/utils.py
  pyproject.toml
Labels: cla-signed

#5961 [Fixes #5960] align ad add id for radiobuttons
  geonode/layers/templates/upload/layer_upload_time.html
  geonode/static/geonode/js/upload/time.js
Labels: cla-signed

#5959 [Fixes #5927] use pinax module to send notifications for message
  geonode/messaging/__init__.py
  geonode/messaging/models.py
  geonode/messaging/notifications.py
  geonode/templates/pinax/notifications/message_received/full.txt
  geonode/templates/pinax/notifications/message_received/short.txt
  geonode/tests/test_message_notifications.py
Labels: cla-signed

#5964 [Fixes #5963] B/R fixes 2
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/utils/utils.py
Labels: cla-signed

#5962 - Alignining Travis and scripts configuration to "master"
  .travis.yml
  AUTHORS
  Dockerfile
  geonode/base/fixtures/group_test_data.json
  geonode/base/populate_test_data.py
  geonode/geoserver/tests/integration.py
  geonode/geoserver/tests/test_helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/groups/migrations/0029_auto_20200406_1123.py
  geonode/groups/models.py
  geonode/groups/tests.py
  geonode/layers/tests.py
  geonode/proxy/tests.py
  geonode/security/tests.py
  geonode/social/tests.py
  geonode/tests/base.py
  geonode/tests/integration.py
  geonode/tests/suite/runner.py
  geonode/utils.py
  pavement.py
  requirements.txt
  scripts/docker/env/development/geoserver.env
  scripts/docker/env/production/geoserver.env
  scripts/misc/create_dbs_travis.sh
  scripts/misc/create_full_geonode_db.py
  scripts/misc/geoserver_server_setup.sh
  scripts/spcgeonode/django/Dockerfile
  scripts/spcgeonode/django/initialize.py
  scripts/spcgeonode/docker-compose.override.yml
  scripts/spcgeonode/docker-compose.yml
  scripts/spcgeonode/geoserver/Dockerfile
  tasks.py
Labels: cla-signed

#5974 [Fixes #5975] Geoserver backup sometime fails when running in Docker
  geonode/br/management/__init__.py
  geonode/br/management/commands/__init__.py
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
  geonode/br/management/commands/settings.ini
  geonode/br/migrations/__init__.py
Labels: cla-signed

#5977 [Fixes #5976] B/R settings.ini mandatory argument
  geonode/br/management/commands/settings.ini
  geonode/br/management/commands/settings_docker_sample.ini
  geonode/br/management/commands/settings_sample.ini
  geonode/br/management/commands/utils/utils.py
  geonode/br/tests/test_backup.py
  geonode/br/tests/test_restore.py
Labels: cla-signed

#5982 [Fixes #5981] B/R revert looped GS backup
  geonode/br/management/commands/backup.py
Labels: cla-signed

#5989 [Backport to 2.10.x][Fixes #5849] Read Only and Maintenance modes
  geonode/base/admin.py
  geonode/base/middleware.py
  geonode/base/migrations/0037_configuration.py
  geonode/base/models.py
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/base/templates/base/maintenance.html
  geonode/base/templates/base/read_only_violation.html
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/client/templates/leaflet/maps/map_list.html
  geonode/context_processors.py
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/templates/documents/document_list.html
  geonode/favorite/templates/favorite/_favorite.html
  geonode/groups/templates/groups/category_list.html
  geonode/groups/templates/groups/group_list.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list.html
  geonode/layers/templates/layers/layer_metadata_upload.html
  geonode/layers/templates/layers/layer_replace.html
  geonode/layers/templates/layers/layer_style_upload.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_list.html
  geonode/people/templates/people/profile_detail.html
  geonode/services/templates/services/service_list.html
  geonode/settings.py
  geonode/singleton.py
  geonode/templates/500.html
  geonode/templates/announcements/announcement_list.html
  geonode/templates/base.html
  geonode/templates/user_messages/inbox.html
Labels: cla-signed

#5988 [Fixes #5987] Resources metadata editor and layout broken if poc and/…
  geonode/base/models.py
  geonode/base/tests.py
  geonode/documents/views.py
  geonode/layers/views.py
  geonode/maps/views.py
Labels: cla-signed

#5984 [Fixes #5983] [Monitoring] Collect metrics jobs pile up and cause exhaustion of memory
  geonode/monitoring/management/commands/collect_metrics.py
  geonode/monitoring/tasks.py
  geonode/monitoring/tests/integration.py
  geonode/monitoring/utils.py
  geonode/settings.py
  geonode/tasks/tasks.py
Labels: cla-signed

#5992 [Backport to 2.10.x][Fixes #5981] B/R revert looped GS backup
  geonode/br/management/commands/__init__.py
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
  geonode/br/management/commands/settings.ini
  geonode/br/management/commands/settings_docker_sample.ini
  geonode/br/management/commands/settings_sample.ini
  geonode/br/management/commands/utils/utils.py
  geonode/br/migrations/__init__.py
  geonode/br/tests/__init__.py
  geonode/br/tests/test_backup.py
  geonode/br/tests/test_restore.py
Labels: cla-signed

#5994 [Fixes #5993] Unexpected behavior of resource created under different RESOURCE_PUBLISHING setting
  geonode/base/management/commands/migrate_baseurl.py
  geonode/base/models.py
  geonode/documents/forms.py
  geonode/documents/models.py
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/tests.py
  geonode/documents/views.py
  geonode/geoserver/helpers.py
  geonode/geoserver/signals.py
  geonode/geoserver/tests/integration.py
  geonode/groups/models.py
  geonode/layers/forms.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/maps/models.py
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/messaging/producer.py
  geonode/monitoring/tests/integration.py
  geonode/proxy/views.py
  geonode/security/models.py
  geonode/security/utils.py
  geonode/security/views.py
  geonode/settings.py
  geonode/social/signals.py
  geonode/utils.py
Labels: cla-signed

#6002 [FIX #6001] Limit comment notifications
  geonode/notifications_helper.py
  geonode/social/signals.py
  geonode/templates/pinax/notifications/email_body.txt
Labels: cla-signed

#6017 - Bump django-mapstore-adapter to 2.0.3
  requirements.txt
Labels: cla-signed, dependencies

#6020 [Fixes #6019] three pg_dumper containers with SPC override.yml compos…
  scripts/spcgeonode/docker-compose.override.yml
Labels: cla-signed

#6024 [Translation][Django.po] Initial revision on pt-pt content
  geonode/locale/pt/LC_MESSAGES/django.mo
  geonode/locale/pt/LC_MESSAGES/django.po
Labels: cla-signed, translations

#6035 [Fixes #6034][Backup/Restore Mgmt Commands] Implement option to exclude geoserver raster and vector data from backup and restore
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
  geonode/br/management/commands/settings_docker_sample.ini
  geonode/br/management/commands/settings_sample.ini
  geonode/br/management/commands/utils/utils.py
  geonode/utils.py
Labels: cla-signed

#6036 [Backport to 2.10.x][Fixes #6034][Backup/Restore Mgmt Commands] Implement option to exclu…
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
  geonode/br/management/commands/settings_docker_sample.ini
  geonode/br/management/commands/settings_sample.ini
  geonode/br/management/commands/utils/utils.py
  geonode/utils.py
Labels: cla-signed

#6038 [6037] Fix double click to remove message
  geonode/base/templatetags/user_messages.py
  geonode/groups/templates/groups/group_members.html
  geonode/messaging/views.py
  geonode/templates/user_messages/_message_snippet.html
  geonode/templates/user_messages/inbox.html
Labels: cla-signed

#6041 [Fixes #6025][Fixes #6040] Error on click 'Create Layer'
  geonode/geoserver/createlayer/utils.py
  geonode/geoserver/createlayer/views.py
Labels: cla-signed
