Repository GeoNode/geonode, pull requests merged in 2020-07, with the labels that each got.

#6202 Fixes: 6201 Large amount of requests ending in a 502
  requirements.txt
Labels: backport 3.x, cla-signed

#6207 Update README.md
  README.md
Labels: cla-signed

#6209 - Bump GeoServer to version 2.17.1
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose.async.yml
  docker-compose.yml
  geonode/utils.py
  scripts/spcgeonode/geoserver/Dockerfile
Labels: backport 3.x, cla-signed, dependencies

#6224 FIX [6223] Prevent integrity errors on singleton model
  geonode/singleton.py
Labels: backport 3.x, cla-signed

#6222 [Fixes #6208] Add more parameters for SPCGeoNode scripts
  scripts/spcgeonode/django/initialize.py
  scripts/spcgeonode/geoserver/docker-entrypoint.sh
Labels: backport 3.x, cla-signed, docker

#6205 [Fixes #6131; Fixes: #6204] Add missing strings and French translation
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/base/templates/base/thumbnail_upload.html
  geonode/favorite/templates/favorite/_favorite.html
  geonode/favorite/templates/favorite/favorite_list.html
  geonode/locale/fr/LC_MESSAGES/django.mo
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/maps/views.py
  geonode/security/views.py
  geonode/static/geonode/js/search/cart.js
  geonode/static/geonode/js/templates/cart.html
  geonode/templates/500.html
  geonode/templates/_permissions_form.html
  geonode/templates/base.html
  geonode/templates/index.html
  geonode/templates/metadata_form_js.html
  geonode/templates/search/_search_content.html
  geonode/templates/search/_search_user_content.html
  geonode/templates/search/_text_filter.html
Labels: backport 3.x, cla-signed, translations

#6262 [Fixes #6261] Limit "maps using this layer" to maps the user has permission to see
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/tests.py
  geonode/layers/views.py
Labels: backport 3.x, cla-signed

#6206 Fixes: "Large amount of requests ending in a 502"
  geonode/geoserver/helpers.py
  geonode/geoserver/signals.py
  geonode/geoserver/tasks.py
  geonode/layers/views.py
  geonode/tests/integration.py
  geonode/upload/tests/integration.py
Labels: backport 3.x, cla-signed, major

#6274 [Fixes #6273] Improve GeoNode OpenID SP Protocol in order to be able …
  geonode/geoserver/views.py
  geonode/security/oauth2_grant_types.py
  geonode/security/oauth2_servers.py
  geonode/security/oauth2_validators.py
  geonode/settings.py
Labels: backport 3.x, cla-signed

#6281 [Fixes #5721] Upload a Thumbnail broken when CACHE BUSTING is enabled
  geonode/base/models.py
  geonode/base/tests.py
Labels: backport 3.x, cla-signed

#6282 Assorted warnings fixes
  geonode/br/management/commands/utils/utils.py
  geonode/layers/views.py
  geonode/upload/models.py
Labels: backport 3.x

#6307 [Fixes #6305] Error in wms.py module
  geonode/services/serviceprocessors/wms.py
Labels: backport 3.x, cla-signed
