Repository GeoNode/geonode, pull requests merged in 2021-12, with the labels that each got.

#8457 8456 harvester status not reset under certain normal circumstances
  geonode/harvesting/tasks.py
Labels: cla-signed

#8449 [Fixes #8420] Hide Connected social accounts link from profile if no social provider + app is configured
  geonode/context_processors.py
  geonode/people/templates/people/profile_detail.html
Labels: cla-signed

#8450 [Backport 3.2.x][Fixes #8420] Hide Connected social accounts link from profile if no social provider + app is configured
  geonode/context_processors.py
  geonode/people/templates/people/profile_detail.html
Labels: cla-signed

#8455 [Fixes #8454] Rating average available only in English
  geonode/documents/templates/documents/document_detail.html
Labels: cla-signed

#8469 [Backport to 3.2.x][Fixes #8454] Rating average available only in English (#8455)
  geonode/documents/templates/documents/document_detail.html
Labels: cla-signed

#8470 [Fixes #8461] WCS getCoverage links have wrong params
  geonode/geoserver/ows.py
  geonode/geoserver/tests/test_server.py
  geonode/harvesting/harvesters/geonodeharvester.py
  geonode/harvesting/harvesters/wms.py
  geonode/harvesting/tests/test_utils.py
  geonode/harvesting/utils.py
  geonode/utils.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8471 [Backport to 3.3.x][Fixes #8461] WCS getCoverage links have wrong params
  geonode/geoserver/ows.py
  geonode/geoserver/tests/test_server.py
  geonode/utils.py
Labels: cla-signed

#8472 [Backport to 3.2.x][Fixes #8461] WCS getCoverage links have wrong params
  geonode/geoserver/ows.py
  geonode/geoserver/tests/test_server.py
  geonode/utils.py
Labels: cla-signed

#8476 [Fixes #8459] Create a New Group button should be hidden to non-super users
  geonode/groups/templates/groups/category_list.html
  geonode/groups/templates/groups/group_list.html
Labels: cla-signed

#8475 [Fixes #8474] Regression on geoapp API POST and PUT requests
  geonode/base/api/serializers.py
  geonode/geoapps/api/serializers.py
  geonode/geoapps/api/tests.py
  geonode/resource/utils.py
Labels: cla-signed

#8477 [Backport to 3.2.x][Fixes #8459] Create a New Group button should be hidden to non-super…
  geonode/groups/templates/groups/category_list.html
  geonode/groups/templates/groups/group_list.html
Labels: cla-signed

#8478 [Backport to 3.3.x][Fixes #8459] Create a New Group button should be hidden to non-super…
  geonode/groups/templates/groups/category_list.html
  geonode/groups/templates/groups/group_list.html
Labels: cla-signed

#8473 [3.3.x][Fixes #8429]GeoApps have empty uuid
  geonode/base/models.py
  geonode/geoapps/api/tests.py
  geonode/geoapps/tests.py
Labels: cla-signed, backport 3.2.x

#8482 [Bckport to 3.2.x][Fixes #8429]GeoApps have empty uuid (#8473)
  geonode/base/models.py
  geonode/geoapps/api/tests.py
  geonode/geoapps/tests.py
Labels: cla-signed

#8068 [Fixes #8058] GeoStory: missing actions in user profile page
  geonode/api/resourcebase_api.py
  geonode/context_processors.py
  geonode/people/templates/people/_profile_filters.html
  geonode/people/templates/people/profile_detail.html
  geonode/static/geonode/js/search/search.js
  geonode/utils.py
Labels: cla-signed

#8397 [Fixes #8376] Fix letsencrypt certificate handling
  scripts/docker/letsencrypt/Dockerfile
  scripts/docker/letsencrypt/docker-entrypoint.sh
Labels: cla-signed

#8497 [Fixes #8495] GeoApp update API must obtain the resource_type without the client having to pass it
  geonode/geoapps/api/serializers.py
  geonode/geoapps/api/tests.py
Labels: cla-signed

#8493 [Fixes #8445] Error on setting Datasets batch permissions in admin
  geonode/base/admin.py
  geonode/base/forms.py
  geonode/base/templates/base/batch_permissions.html
  geonode/layers/admin.py
Labels: cla-signed

#8490 [Fixes #8430] Make create_thumbnail use Map's own bbox
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
Labels: cla-signed

#8479 [Fixes #8398] All users can add featured content to homepage
  geonode/base/forms.py
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/tests.py
  geonode/documents/views.py
  geonode/geoapps/templates/apps/app_metadata_advanced.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoapps/views.py
  geonode/layers/templates/datasets/dataset_metadata_advanced.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/maps/views.py
Labels: cla-signed

#8498 Fix typo in Authorizaton header: Berarer -> Bearer
  geonode/thumbs/utils.py
Labels: 3.2.x, 3.3.x, master

#8492 fix harvesting session saving errors
  geonode/harvesting/models.py
Labels: cla-signed

#8417 [Fixes #8403] Drop GXP* classes from Map / MapLayer models and views
  geonode/api/resourcebase_api.py
  geonode/base/migrations/0061_auto_20211117_1238.py
  geonode/base/migrations/0061_merge_0060_auto_20210512_1658_0060_resourcebase_state.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/base/tests.py
  geonode/client/templatetags/client_lib_tags.py
  geonode/harvesting/harvesters/geonodeharvester.py
  geonode/harvesting/resourcedescriptor.py
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/maps/api/hook.py
  geonode/maps/api/serializers.py
  geonode/maps/api/tests.py
  geonode/maps/forms.py
  geonode/maps/migrations/0033_convert_map_blob.py
  geonode/maps/migrations/0040_remove_maplayer_legacy_fields.py
  geonode/maps/migrations/0041_remove_map_legacy_fields.py
  geonode/maps/migrations/0042_remove_maplayer_styles.py
  geonode/maps/migrations/24_initial.py
  geonode/maps/models.py
  geonode/maps/tests.py
  geonode/maps/tests_populate_maplayers.py
  geonode/maps/urls.py
  geonode/maps/utils/layers.py
  geonode/maps/views.py
  geonode/resource/tests.py
  geonode/resource/utils.py
  geonode/services/migrations/0046_auto_20210903_1427.py
  geonode/services/migrations/0046_service_extra_queryparams.py
  geonode/services/migrations/0048_service_harvester.py
  geonode/thumbs/tests/fixtures/map.json
  geonode/thumbs/tests/fixtures/map_dataset.json
  geonode/thumbs/tests/test_integration.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
  geonode/upload/migrations/0031_auto_20210527_1520.py
  geonode/upload/migrations/0031_upload_resume_url.py
  geonode/utils.py
Labels: cla-signed

#8503 [Fixes #8494] Add ratings API v2 endpoint
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#8462 [3.3.x][Fixes #8458] Direct download timeout with big files
  geonode/proxy/tests.py
  geonode/proxy/views.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#8506 [master][Fixes #8458] Direct download timeout with big files
  geonode/proxy/tests.py
  geonode/proxy/views.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#8526 [Backport to 3.2.x][Fixes #8524] Missing "anonymous group" permissions within GeoFence r…
  geonode/security/models.py
  geonode/security/utils.py
Labels: cla-signed

#8525 [Backport to 3.3.x][Fixes #8524] Missing "anonymous group" permissions within GeoFence r…
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#8532 [Fixes #8531] Review MapStore settings.py varaibles
  geonode/local_settings.py.geoserver.sample
  geonode/maps/api/tests.py
  geonode/settings.py
Labels: cla-signed

#8523 [Fixes #8522] Extend the upload API to accept compact permissions
  geonode/resource/manager.py
  geonode/security/permissions.py
  geonode/security/tests.py
Labels: cla-signed

#8527 [Fixes #8524] Missing "anonymous group" permissions within GeoFence rules
  geonode/geoserver/security.py
  geonode/resource/manager.py
  geonode/security/tests.py
Labels: cla-signed

#8529 [Fixes #8504] Implement maps / dataset relationships endpoints
  geonode/api/resourcebase_api.py
  geonode/client/templates/ol/maps/map_ol3.html
  geonode/geoserver/views.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/models.py
  geonode/layers/templates/datasets/dataset_granule_remove.html
  geonode/maps/api/serializers.py
  geonode/maps/api/tests.py
  geonode/maps/api/views.py
  geonode/maps/models.py
  geonode/maps/templates/maps/wmc.xml
  geonode/resource/manager.py
  geonode/thumbs/tests/test_integration.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#8535 [Fixes #8534] Include links inside resources API v2 response
  geonode/base/api/serializers.py
Labels: cla-signed

#8537 [Backport 3.2.x][Fixes #8534] Include links inside resources API v2 response
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
Labels: cla-signed

#8536 [Backport 3.3.x][Fixes #8534] Include links inside resources API v2 response
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
Labels: cla-signed

#8538 [Fixes #8425] Space in sitename not escaped in invitation mail body
  geonode/templates/account/email/email_confirmation_message.txt
  geonode/templates/account/email/email_confirmation_subject.txt
  geonode/templates/account/email/invite_user.txt
  geonode/templates/account/email/invite_user_subject.txt
  geonode/templates/account/email/password_reset_key.txt
  geonode/templates/invitations/email/email_invite_message.html
  geonode/templates/invitations/email/email_invite_message.txt
  geonode/templates/invitations/email/email_invite_subject.txt
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8543 Fix view_in_or_basicauth decorator not working in the context of the REST API
  geonode/decorators.py
  geonode/upload/views.py
Labels: cla-signed
