Repository GeoNode/geonode, pull requests merged in 2021-04, with the labels that each got.

#7225 [Fixes #7214] Sorting Thesauri
  geonode/base/fixtures/test_thesaurus.json
  geonode/base/forms.py
  geonode/base/migrations/0058_thesaurus_order.py
  geonode/base/models.py
  geonode/base/tests.py
  geonode/context_processors.py
Labels: backport 3.2.x, cla-signed

#7246 [Backport to 3.2.x][Fixes #7214] Sorting Thesauri (#7225)
  geonode/base/fixtures/test_thesaurus.json
  geonode/base/forms.py
  geonode/base/migrations/0058_thesaurus_order.py
  geonode/base/models.py
  geonode/base/tests.py
  geonode/context_processors.py
Labels: cla-signed

#7240 [Fixes #7224] Harmonize/improve metadata editing pages
  geonode/documents/forms.py
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/documents/views.py
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/layers/views.py
  geonode/maps/forms.py
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/maps/views.py
  geonode/templates/metadata_base.html
  geonode/templates/metadata_form_js.html
Labels: backport 3.2.x, cla-signed

#7247 [Backport to 3.2.x][Fixes #7224] Harmonize/improve metadata editing pages (#7240)
  geonode/documents/forms.py
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/documents/views.py
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/layers/views.py
  geonode/maps/forms.py
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/maps/views.py
  geonode/templates/metadata_base.html
  geonode/templates/metadata_form_js.html
Labels: cla-signed

#7243 [Resolves #6995] Increase UI block coverage in geonode
  geonode/context_processors.py
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/templates/metadata_form_js.html
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7248 [Backport to 3.2.x][Resolves #6995] Increase UI block coverage in geonode (#7243)
  geonode/context_processors.py
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/templates/metadata_form_js.html
Labels: cla-signed

#7130 [FIXES #7126] multi word iso category strings will not get translated
  geonode/custom_translations.py
  geonode/locale/af/LC_MESSAGES/django.po
  geonode/locale/al/LC_MESSAGES/django.po
  geonode/locale/am/LC_MESSAGES/django.po
  geonode/locale/ar/LC_MESSAGES/django.po
  geonode/locale/bg_BG/LC_MESSAGES/django.po
  geonode/locale/bn/LC_MESSAGES/django.po
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
  geonode/locale/el/LC_MESSAGES/django.po
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/fa/LC_MESSAGES/django.po
  geonode/locale/fa_IR/LC_MESSAGES/django.po
  geonode/locale/fi/LC_MESSAGES/django.po
  geonode/locale/fil/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.mo
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/djangojs.mo
  geonode/locale/hu/LC_MESSAGES/django.po
  geonode/locale/id/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/locale/ja/LC_MESSAGES/django.po
  geonode/locale/ka/LC_MESSAGES/django.po
  geonode/locale/km/LC_MESSAGES/django.po
  geonode/locale/ko/LC_MESSAGES/django.po
  geonode/locale/lt/LC_MESSAGES/django.po
  geonode/locale/ne/LC_MESSAGES/django.po
  geonode/locale/nl_NL/LC_MESSAGES/django.po
  geonode/locale/no/LC_MESSAGES/django.po
  geonode/locale/pl/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/locale/ro/LC_MESSAGES/django.po
  geonode/locale/ru/LC_MESSAGES/django.po
  geonode/locale/si/LC_MESSAGES/django.po
  geonode/locale/sk/LC_MESSAGES/django.po
  geonode/locale/sq/LC_MESSAGES/django.po
  geonode/locale/sv/LC_MESSAGES/django.po
  geonode/locale/sw/LC_MESSAGES/django.po
  geonode/locale/ta/LC_MESSAGES/django.po
  geonode/locale/th/LC_MESSAGES/django.po
  geonode/locale/tl/LC_MESSAGES/django.po
  geonode/locale/uk/LC_MESSAGES/django.po
  geonode/locale/vi/LC_MESSAGES/django.po
  geonode/locale/zh/LC_MESSAGES/django.po
Labels: backport 3.1.x, backport 3.2.x, cla-signed, translations

#7253 [Fixes #7236] Issues with layer style legends displayed when more tha…
  geonode/geoserver/helpers.py
  geonode/geoserver/views.py
  geonode/layers/templates/layers/layer_detail.html
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7257 [Backport to 3.1.x][Fixes #7236] Issues with layer style legends displayed when more tha…
  geonode/geoserver/helpers.py
  geonode/geoserver/views.py
  geonode/layers/templates/layers/layer_detail.html
Labels: cla-signed

#7249 [Fixes #7245] Text filter is broken
  geonode/api/resourcebase_api.py
  geonode/api/tests.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7255 [Fixes #7254] Map Legend
  geonode/geoserver/views.py
  geonode/layers/views.py
  geonode/maps/models.py
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7261 [Backport to 3.2.x][Fixes #7254] Map Legend (#7255)
  geonode/geoserver/views.py
  geonode/layers/views.py
  geonode/maps/models.py
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
Labels: cla-signed

#7262 [Backport to 3.2.x][Fixes #7254] Map Legend (#7255)
  geonode/geoserver/views.py
  geonode/layers/views.py
  geonode/maps/models.py
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
Labels: cla-signed

#7287 [Backport to 3.2.x] Bump pytest-django from 4.1.0 to 4.2.0 (#7271)
  requirements.txt
Labels: cla-signed

#7270 [Fixes #7269] Reduce information returned to users to only what is strictly required and accessible
  geonode/api/api.py
  geonode/api/tests.py
  geonode/people/templates/people/profile_detail.html
  geonode/people/tests.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/templates/search/_general_filters.html
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7296 [Backport to 3.1.x][Fixes #7269] Reduce information returned to users to only what is s…
  geonode/api/api.py
  geonode/api/tests.py
  geonode/people/templates/people/profile_detail.html
  geonode/people/tests.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/templates/search/_general_filters.html
Labels: cla-signed

#7295 [Backport to 3.2.x][Fixes #7269] Reduce information returned to users to only what is s…
  geonode/api/api.py
  geonode/api/tests.py
  geonode/people/templates/people/profile_detail.html
  geonode/people/tests.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/templates/search/_general_filters.html
Labels: cla-signed

#7290 [Fixes: #7289] Missleading message on upload
  geonode/layers/templates/upload/layer_upload.html
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
  geonode/locale/en/LC_MESSAGES/django.mo
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/django.mo
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: backport 3.2.x, cla-signed

#7286 [Fixes #7279] Keyword parsing improvements
  geonode/api/api.py
  geonode/base/fixtures/test_xml.xml
  geonode/geoserver/tasks.py
  geonode/layers/metadata.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/upload/models.py
  geonode/upload/tests/test_utils.py
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/urls.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7300 [Backport to 3.2.x][Fixes #7279] Keyword parsing improvements (#7286)
  geonode/api/api.py
  geonode/base/fixtures/test_xml.xml
  geonode/geoserver/tasks.py
  geonode/layers/metadata.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/upload/models.py
  geonode/upload/tests/test_utils.py
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/urls.py
Labels: cla-signed

#7299 [Fixes #7292] Thumbnail failure when data bbox extends beyond the are a of use of EPSG:3857
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
Labels: backport 3.2.x, cla-signed

#7302 [Backport to 3.2.x][Fixes #7292] Thumbnail failure when data bbox extends beyond the are…
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
Labels: cla-signed

#7293 [Fixes #7288] Layer saving cleanup
  geonode/geoserver/tasks.py
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/upload/views.py
Labels: backport 3.2.x, cla-signed

#7305 [Backport to 3.2.x][Fixes #7288] Layer saving cleanup (#7293)
  geonode/geoserver/tasks.py
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/upload/views.py
Labels: cla-signed

#7304 [Fixes #7303] Missing user search bar in geolimits
  geonode/templates/_permissions_form.html
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7307 [Backport to 3.2.x][Fixes #7303] Missing user search bar in geolimits
  geonode/templates/_permissions_form.html
Labels: cla-signed

#7308 [Backport to 3.1.x][Fixes #7303] Missing user search bar in geolimits
  geonode/templates/_permissions_form.html
Labels: cla-signed

#7309 [Fixes #7263] Metadata parsing and storing
  geonode/base/fixtures/test_xml.xml
  geonode/layers/metadata.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/tests/integration.py
  geonode/upload/tests/test_utils.py
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/upload/views.py
Labels: backport 3.2.x, cla-signed

#7318 [Backport to 3.2.x][Fixes #7263] Metadata parsing and storing (#7309)
  geonode/base/fixtures/test_xml.xml
  geonode/layers/metadata.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/tests/integration.py
  geonode/upload/tests/test_utils.py
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/upload/views.py
Labels: cla-signed

#7313 [Fixes #7312] Replace EPSG:900913 with EPSG:3857 inside metadata wizard's thumbnail widget
  geonode/client/templates/ol/layers/layer_ol2_map.html
  geonode/client/templates/ol/maps/map_ol2.html
Labels: backport 3.1.x, backport 3.2.x, cla-signed, enhancement

#7310 [Fixes #7292] Thumbnail failure when data bbox extends beyond the are a of use of EPSG:3857
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
  geonode/thumbs/background.py
  geonode/thumbs/tests/test_integration.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
Labels: backport 3.2.x, cla-signed

#7321 [Backport to 3.2.x][Fixes #7292] Thumbnail failure when data bbox extends beyond the are…
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
  geonode/thumbs/background.py
  geonode/thumbs/tests/test_integration.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
Labels: cla-signed

#7315 [Fixes #7311] Missing cache in layers loaded on geonode
  geonode/layers/views.py
  geonode/maps/views.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7323 [Backport to 3.2.x][Fixes #7311] Missing cache in layers loaded on geonode
  geonode/layers/views.py
  geonode/maps/views.py
Labels: cla-signed

#7324 [Backport to 3.1.x][Fixes #7311] Missing cache in layers loaded on geonode
  geonode/layers/views.py
  geonode/maps/views.py
Labels: cla-signed

#7337 Developers page broken
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: backport 3.2.x, cla-signed

#7339 [Backport to 3.2.x][Fixes #7338] Italian translation of developers page broken
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: cla-signed

#7340 [Backport to 3.1.x][Fixes #7338] Italian translation of developers page broken
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: cla-signed

#7345 [Fixes #7336] Thumbnail generation fails for remote services
  geonode/thumbs/thumbnails.py
Labels: backport 3.2.x, cla-signed

#7350 [Backport to 3.2.x][Fixes #7336] Thumbnail generation fails for remote services (#7345)
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#7326 [Fixes #7325] Limit resource/{pk}/get_perms | set_perms to resource owner and admins
  geonode/base/api/permissions.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: backport 3.2.x, cla-signed

#7352 [Backport to 3.2.x][Fixes #7325] Limit resource/{pk}/get_perms | set_perms to resource owner and admins
  geonode/base/api/permissions.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#7353 [Backport to 3.2.x][Fixes #7327] Return permissions for the authenticated user inside the resource and user response
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/models.py
  geonode/geoapps/api/tests.py
  geonode/people/models.py
  geonode/security/models.py
Labels: cla-signed

#7356 [Resolves #7354] Html body class translate
  geonode/base/templates/base/batch_edit.html
  geonode/base/templates/base/batch_permissions.html
  geonode/base/templates/base/thumbnail_upload.html
  geonode/base/templates/base/user_and_group_permissions.html
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/templates/documents/document_metadata.html
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/geoapps/templates/apps/app_base.html
  geonode/geoapps/templates/apps/app_list_default.html
  geonode/geoapps/templates/apps/app_metadata.html
  geonode/geoapps/templates/apps/app_metadata_advanced.html
  geonode/groups/templates/groups/category_list.html
  geonode/groups/templates/groups/group_base.html
  geonode/groups/templates/groups/group_create.html
  geonode/groups/templates/groups/group_detail.html
  geonode/groups/templates/groups/group_list.html
  geonode/groups/templates/groups/group_remove.html
  geonode/groups/templates/groups/group_update.html
  geonode/layers/templates/layers/layer_append.html
  geonode/layers/templates/layers/layer_base.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/layers/templates/layers/layer_metadata.html
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/layers/templates/layers/layer_metadata_upload.html
  geonode/layers/templates/layers/layer_replace.html
  geonode/layers/templates/layers/layer_style_edit.html
  geonode/layers/templates/layers/layer_style_manage.html
  geonode/layers/templates/layers/layer_style_upload.html
  geonode/layers/templates/upload/layer_upload.html
  geonode/layers/templates/upload/layer_upload_base.html
  geonode/layers/templates/upload/layer_upload_metadata_base.html
  geonode/maps/templates/maps/map_base.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_list_default.html
  geonode/maps/templates/maps/map_metadata.html
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/people/templates/people/profile_detail.html
  geonode/people/templates/people/profile_edit.html
  geonode/services/templates/services/services_base.html
  geonode/templates/metadata_base.html
  geonode/templates/metadata_detail.html
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7360 [Backport to 3.1.x][Resolves #7354] Html body class translate (#7356)
  geonode/base/templates/base/batch_edit.html
  geonode/base/templates/base/batch_permissions.html
  geonode/base/templates/base/thumbnail_upload.html
  geonode/base/templates/base/user_and_group_permissions.html
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/templates/documents/document_metadata.html
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/groups/templates/groups/category_list.html
  geonode/groups/templates/groups/group_base.html
  geonode/groups/templates/groups/group_create.html
  geonode/groups/templates/groups/group_detail.html
  geonode/groups/templates/groups/group_list.html
  geonode/groups/templates/groups/group_remove.html
  geonode/groups/templates/groups/group_update.html
  geonode/layers/templates/layers/layer_base.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/layers/templates/layers/layer_metadata.html
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/layers/templates/layers/layer_metadata_upload.html
  geonode/layers/templates/layers/layer_replace.html
  geonode/layers/templates/layers/layer_style_edit.html
  geonode/layers/templates/layers/layer_style_manage.html
  geonode/layers/templates/layers/layer_style_upload.html
  geonode/layers/templates/upload/layer_upload.html
  geonode/layers/templates/upload/layer_upload_base.html
  geonode/layers/templates/upload/layer_upload_metadata_base.html
  geonode/maps/templates/maps/map_base.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_list_default.html
  geonode/maps/templates/maps/map_metadata.html
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/people/templates/people/profile_detail.html
  geonode/people/templates/people/profile_edit.html
  geonode/services/templates/services/services_base.html
  geonode/templates/metadata_base.html
  geonode/templates/metadata_detail.html
Labels: cla-signed

#7361 [Backport to 3.2.x][Resolves #7354] Html body class translate (#7356)
  geonode/base/templates/base/batch_edit.html
  geonode/base/templates/base/batch_permissions.html
  geonode/base/templates/base/thumbnail_upload.html
  geonode/base/templates/base/user_and_group_permissions.html
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/templates/documents/document_metadata.html
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/geoapps/templates/apps/app_base.html
  geonode/geoapps/templates/apps/app_list_default.html
  geonode/geoapps/templates/apps/app_metadata.html
  geonode/geoapps/templates/apps/app_metadata_advanced.html
  geonode/groups/templates/groups/category_list.html
  geonode/groups/templates/groups/group_base.html
  geonode/groups/templates/groups/group_create.html
  geonode/groups/templates/groups/group_detail.html
  geonode/groups/templates/groups/group_list.html
  geonode/groups/templates/groups/group_remove.html
  geonode/groups/templates/groups/group_update.html
  geonode/layers/templates/layers/layer_append.html
  geonode/layers/templates/layers/layer_base.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/layers/templates/layers/layer_metadata.html
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/layers/templates/layers/layer_metadata_upload.html
  geonode/layers/templates/layers/layer_replace.html
  geonode/layers/templates/layers/layer_style_edit.html
  geonode/layers/templates/layers/layer_style_manage.html
  geonode/layers/templates/layers/layer_style_upload.html
  geonode/layers/templates/upload/layer_upload.html
  geonode/layers/templates/upload/layer_upload_base.html
  geonode/layers/templates/upload/layer_upload_metadata_base.html
  geonode/maps/templates/maps/map_base.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_list_default.html
  geonode/maps/templates/maps/map_metadata.html
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/people/templates/people/profile_detail.html
  geonode/people/templates/people/profile_edit.html
  geonode/services/templates/services/services_base.html
  geonode/templates/metadata_base.html
  geonode/templates/metadata_detail.html
Labels: cla-signed

#7359 [Fixes #7358] Allow GWC to refresh the gridsets bounds dynamically in…
  geonode/base/api/tests.py
  geonode/security/models.py
  geonode/security/utils.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7370 [Fixes #7369] Thumbnail error for arcgis layers
  geonode/services/serviceprocessors/arcgis.py
Labels: backport 3.2.x, cla-signed

#7357 Fixes #7342 Migration breaks layers
  geonode/base/migrations/0045_auto_20200507_0445.py
Labels: backport 3.2.x, cla-signed

#7372 [Backport to 3.2.x] Fixes #7342 Migration breaks layers (#7357)
  geonode/base/migrations/0045_auto_20200507_0445.py
Labels: cla-signed

#7368 [Fixes #7367] Error when Map Legend tries to read the name of the default style for a layer
  geonode/maps/models.py
Labels: backport 3.2.x, cla-signed

#7374 [Backport to 3.2.x][Fixes #7367] Error when Map Legend tries to read the name of the default style for a layer
  geonode/maps/models.py
Labels: cla-signed

#7381 [Fixes #7380] Create resources buttons are enabled for Anonymous users
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/client/templates/leaflet/maps/map_list.html
  geonode/documents/templates/documents/document_list.html
  geonode/geoapps/templates/apps/app_list_default.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_list_default.html
  geonode/people/templates/people/profile_detail.html
  geonode/services/templates/services/service_list.html
  geonode/templates/500.html
  geonode/templates/search/_search_content.html
Labels: cla-signed

#7388 [port master][Fixes #7380] Create resources buttons are enabled for Anonymous users
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/documents/templates/documents/document_list.html
  geonode/geoapps/templates/apps/app_list_default.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_list_default.html
  geonode/people/templates/people/profile_detail.html
  geonode/services/templates/services/service_list.html
  geonode/templates/500.html
  geonode/templates/search/_search_content.html
Labels: cla-signed

#7363 [Fixes #7362] GDAL upgrade to issue wtih postgres 12 and higher
  Dockerfile
Labels: backport 3.2.x, dependencies, docker

#7397 [Fixes #7393] Geoapp filters return values from the first geostory only
  geonode/api/api.py
Labels: backport 3.2.x, cla-signed

#7396 [Backport Resolves #7392] Fix upload/replace/append layer
  geonode/layers/utils.py
  geonode/upload/utils.py
Labels: cla-signed

#7394 [Fixes #7391] MapLegend shows wrong legend instead od the selected (default) style
  geonode/maps/models.py
Labels: backport 3.2.x, cla-signed

#7401 [Fixes #7338] remove translation for python
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: cla-signed

#7399 [Fixes #6995] Extend block template in metadata_detail
  geonode/templates/metadata_detail.html
Labels: backport 3.2.x, cla-signed

#7406 [Fixes #7398] Truncated tooltips in advanced edit
  geonode/templates/metadata_form_js.html
Labels: cla-signed

#7407 [Backport 3.2.x] [Fixes #7398] Truncated tooltips in advanced edit
  geonode/templates/metadata_form_js.html
Labels: cla-signed

#7405 [Fixes #7390] Fix parsing of style title from UserStyle.Title element
  geonode/geoserver/helpers.py
  geonode/geoserver/views.py
Labels: backport 3.2.x, cla-signed

#7410 [Fixes #7409] Map legend must use style title if available
  geonode/maps/models.py
Labels: backport 3.2.x, cla-signed

#7411 [Backport to 3.2.x][Fixes #7409] Map legend must use style title if available
  geonode/maps/models.py
Labels: cla-signed

#7414 [Fixes #7267] Legend graphics will not render UTF-8 characters (eg. äöü)
  geonode/proxy/views.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7415 [Backport to 3.2.x][Fixes #7267] Legend graphics will not render UTF-8 characters (eg. ä…
  geonode/proxy/views.py
Labels: cla-signed

#7416 [Backport to 3.1.x][Fixes #7267] Legend graphics will not render UTF-8 characters (eg. ä…
  geonode/proxy/views.py
Labels: cla-signed

#7376 [Resolves #7375][Backport 3.2.x] Export thesauri
  geonode/base/management/commands/dump_thesaurus.py
Labels: cla-signed

#7421 [Fixes #7419] make mandatory fields more controllable and include optional UI_REQU…
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/views.py
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/views.py
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/maps/views.py
  geonode/settings.py
  geonode/templates/metadata_form_js.html
Labels: backport 3.2.x, cla-signed

#7420 [Fixes #7412] Move doi and attribution fields in a lower position
  geonode/base/models.py
Labels: backport 3.2.x, cla-signed

#7424 [Resolves #7377] Thesauri in metadata details
  geonode/base/templates/base/_resourcebase_info_panel.html
  geonode/base/templatetags/thesaurus.py
  geonode/base/tests.py
  geonode/templates/metadata_detail.html
Labels: backport 3.2.x, cla-signed

#7425 [Backport #7377] Thesauri in metadata details
  geonode/base/models.py
  geonode/base/templates/base/_resourcebase_info_panel.html
  geonode/base/templatetags/thesaurus.py
  geonode/base/tests.py
  geonode/documents/views.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/settings.py
  geonode/templates/metadata_detail.html
Labels: cla-signed

#7426 Fix flake8 format for master branch
  geonode/base/models.py
  geonode/base/templatetags/thesaurus.py
  geonode/documents/views.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/settings.py
Labels: cla-signed
