Repository GeoNode/geonode, pull requests merged in 2021-03, with the labels that each got.

#6711 [Fixes #6704] UUID will not be used on XML upload
  .circleci/config.yml
  geonode/geoserver/tasks.py
  geonode/geoserver/upload.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/tests/data/hydrodata/same_uuid_a.cpg
  geonode/tests/data/hydrodata/same_uuid_a.dbf
  geonode/tests/data/hydrodata/same_uuid_a.prj
  geonode/tests/data/hydrodata/same_uuid_a.qpj
  geonode/tests/data/hydrodata/same_uuid_a.shp
  geonode/tests/data/hydrodata/same_uuid_a.shx
  geonode/tests/data/hydrodata/same_uuid_a.xml
  geonode/tests/data/hydrodata/same_uuid_b.cpg
  geonode/tests/data/hydrodata/same_uuid_b.dbf
  geonode/tests/data/hydrodata/same_uuid_b.gfs
  geonode/tests/data/hydrodata/same_uuid_b.prj
  geonode/tests/data/hydrodata/same_uuid_b.qpj
  geonode/tests/data/hydrodata/same_uuid_b.shp
  geonode/tests/data/hydrodata/same_uuid_b.shx
  geonode/tests/data/hydrodata/same_uuid_b.xml
  geonode/tests/utils.py
  geonode/upload/tests/data/same_uuid_a.zip
  geonode/upload/tests/data/same_uuid_b.zip
  geonode/upload/tests/integration.py
  geonode/upload/upload.py
  geonode/upload/views.py
Labels: cla-signed, enhancement

#7011 [Fixes #6995] add block tags in geonode template
  geonode/layers/templates/layouts/panels.html
  geonode/templates/search/_search_content.html
  geonode/templates/search/search_scripts.html
Labels: cla-signed

#7014 [FIXES #6830] Geoserver menu entry leads to login-dialog / GeoWebCach…
  pavement.py
Labels: cla-signed, regression

#7018 [Fixes #7017] BBOXes in metadata detail are always expressed in 4326
  geonode/base/api/serializers.py
  geonode/base/bbox_utils.py
  geonode/base/migrations/0055_auto_20210302_1109.py
  geonode/base/migrations/0056_resourcebase_ll_bbox_polygon.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/geoserver/tasks.py
  geonode/layers/utils.py
  geonode/utils.py
Labels: cla-signed

#7013 [Fixes #7012]: CSW prefiltering
  geonode/catalogue/tests.py
  geonode/catalogue/views.py
Labels: cla-signed, feature

#7023 [Fixes #6995] Extending Geonode Template
  geonode/templates/metadata_form_js.html
Labels: cla-signed, feature

#7000 Bump GeoServer to version 2.18.2
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose-test.yml
  docker-compose.yml
  scripts/spcgeonode/geoserver/Dockerfile
Labels: cla-signed, dependencies, docker, spc-docker

#7021 [Fixes #7020] Remove stale templates and hooksets implementations fro…
  geonode/client/hooksets.py
  geonode/client/templates/leaflet/layers/layer_leaflet_map.html
  geonode/client/templates/leaflet/layers/layer_map.html
  geonode/client/templates/leaflet/maps/map_base.html
  geonode/client/templates/leaflet/maps/map_detail.html
  geonode/client/templates/leaflet/maps/map_edit.html
  geonode/client/templates/leaflet/maps/map_embed.html
  geonode/client/templates/leaflet/maps/map_embed_widget.html
  geonode/client/templates/leaflet/maps/map_list.html
  geonode/client/templates/leaflet/maps/map_view.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/views.py
  geonode/local_settings.py.geoserver.sample
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_leaflet.html
  geonode/settings.py
  geonode/static/build.sh
  geonode/static/gruntfile.js
  geonode/static/lib/css/L.Control.Opacity.css
  geonode/static/lib/css/L.Control.Pan.css
  geonode/static/lib/css/Leaflet.NavBar.css
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/leaflet-measure.css
  geonode/static/lib/css/leaflet-plugins.min.css
  geonode/static/lib/css/leaflet.css
  geonode/static/lib/css/leaflet.fullscreen.css
  geonode/static/lib/css/tagify.css
  geonode/static/lib/js/L.Control.Locate.min.js
  geonode/static/lib/js/L.Control.Opacity.js
  geonode/static/lib/js/L.Control.Pan.js
  geonode/static/lib/js/Leaflet.fullscreen.min.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/leaflet-measure.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/lib/js/leaflet.js
  geonode/static/lib/js/openlayers-plugins.min.js
  geonode/static/lib/js/tagify.min.js
  geonode/static/package.json
  geonode/static/static_dependencies.json
  geonode/templates/metadata_base.html
  package/debian/control
  package/support/geonode.local_settings
  requirements.txt
  setup.cfg
Labels: cla-signed

#7038 [Fixes: #7033] Mandatory fields in editor
  geonode/context_processors.py
  geonode/layers/templates/layouts/panels.html
  geonode/templates/metadata_form_js.html
Labels: backport 3.2.x, cla-signed

#7035 [Fixes: #7034] Metadata UI freezes on empty mandatory fields
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/templates/metadata_base.html
  geonode/templates/metadata_form_js.html
Labels: backport 3.2.x, cla-signed

#7036 [Backport to 3.2.x][Fixes: #7034] Metadata UI freezes on empty mandatory fields
  geonode/layers/templates/layers/layer_metadata_advanced.html
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/templates/metadata_base.html
  geonode/templates/metadata_form_js.html
Labels: cla-signed

#7052 [FIXES #7024] Metadata-Text and -HTML don't show for Layers with slas…
  geonode/layers/templates/layers/layer_detail.html
Labels: cla-signed

#7047 [Fixes: #6925] Thesauri improvements
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/views.py
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/views.py
Labels: backport 3.2.x, cla-signed

#7048 [Backport to 3.2.x][Fixes: #6925] Thesauri improvements
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/views.py
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/views.py
Labels: cla-signed

#7049 [Fixes #7033] fix header tab classes
  geonode/templates/metadata_form_js.html
Labels: backport 3.2.x, cla-signed

#7050 [Backport to 3.2.x][Fixes #7033] fix header tab classes
  geonode/templates/metadata_form_js.html
Labels: cla-signed

#7055 [Backport to 3.2.x][Fixes: #6925] Thesauri improvements
  geonode/api/api.py
  geonode/api/tests.py
  geonode/templates/search/_t_keywords_filter.html
Labels: cla-signed

#7056 [Fixes: #6925] Thesauri improvements
  geonode/api/api.py
  geonode/api/tests.py
  geonode/templates/search/_t_keywords_filter.html
Labels: cla-signed

#7058 [Fixes #7051] GeoServer will create three styles instead of one
  geonode/geoserver/helpers.py
  geonode/geoserver/tasks.py
  geonode/security/tests.py
  geonode/tests/integration.py
Labels: backport 3.2.x, cla-signed

#7059 [Backport to 3.2.x][Fixes #7051] GeoServer will create three styles instead of one
  geonode/geoserver/helpers.py
  geonode/geoserver/tasks.py
  geonode/security/tests.py
  geonode/tests/integration.py
Labels: cla-signed

#7070 [Fixes #7062] Bump to postgresql-client-13
  Dockerfile
  docker-compose-test.yml
  docker-compose.yml
  scripts/spcgeonode/docker-compose.yml
Labels: backport 3.1.x, backport 3.2.x, backport 3.x

#7071 [Fixes #7034] Metadata UI freezes on empty mandatory fields
  geonode/templates/metadata_form_js.html
Labels: backport 3.2.x, cla-signed

#7072 [Backport 3.2.x][Fixes #7034] Metadata UI freezes on empty mandatory fields
  geonode/templates/metadata_form_js.html
Labels: cla-signed

#7077 [Fixes #7075] LOCKDOWN mode with custom login view
  geonode/security/middleware.py
  geonode/security/tests.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7078 [Backport to 3.2.x][Fixes #7075] LOCKDOWN mode with custom login view (#7077)
  geonode/security/middleware.py
  geonode/security/tests.py
Labels: cla-signed

#7079 [Backport to 3.1.x][Fixes #7075] LOCKDOWN mode with custom login view (#7077)
  geonode/security/middleware.py
  geonode/security/tests.py
Labels: cla-signed

#7088 [Fixes #6995] Extending Geonode Template
  geonode/layers/templates/layers/layer_metadata_advanced.html
Labels: backport 3.2.x, cla-signed

#7086 [Fixes #7067] Totals of results inside the facets filters don't match the total value shown in the resource list when abstract and prupose filters are set
  geonode/base/templatetags/base_tags.py
  geonode/base/tests.py
Labels: backport 3.1.x, backport 3.2.x

#7091 Add Slovak language translation
  geonode/locale/sk/LC_MESSAGES/django.mo
  geonode/locale/sk/LC_MESSAGES/django.po
Labels: backport 3.2.x, translations

#7093 [Fixes #7092] Inconsistent spacing of form fields between layer and map advanced metadata
  geonode/layers/templates/layers/layer_metadata_advanced.html
Labels: backport 3.2.x, cla-signed

#7099 [Fixes #7097] Allow XSL customization
  geonode/catalogue/metadataxsl/views.py
Labels: backport 3.2.x, cla-signed

#7100 [Backport to 3.2.x][Fixes #7097] Allow XSL customization
  geonode/catalogue/metadataxsl/views.py
Labels: cla-signed

#7069 [Fixes #7068] mixed case TopicCategories are mangled during layer upload
  geonode/geoserver/tasks.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/tests/data/kml/Thuenen_BD_BT1_NewCategory.kml
  geonode/tests/data/kml/Thuenen_BD_BT1_NewCategory.xml
  geonode/tests/data/kml/Thuenen_BD_BT1_NoCategory.kml
  geonode/tests/data/kml/Thuenen_BD_BT1_NoCategory.xml
  geonode/tests/data/kml/Thuenen_BD_BT1_planningCadastre.kml
  geonode/tests/data/kml/Thuenen_BD_BT1_planningCadastre.xml
  geonode/tests/data/kml/Thuenen_BD_BT1_structure.kml
  geonode/tests/data/kml/Thuenen_BD_BT1_structure.xml
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7103 [Fixes #7102] All new Styles seem to be called Default Styler, not their actual name
  geonode/geoserver/helpers.py
Labels: backport 3.1.x, backport 3.2.x

#7076 [Fixes #7057] ResourceBase for metadata-only resources
  geonode/api/api.py
  geonode/api/resourcebase_api.py
  geonode/api/tests.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/migrations/0057_resourcebase_metadata_only.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/maps/tests.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/templates/metadata_form_js.html
Labels: cla-signed, feature

#7110 [Fixes: #7095] Mandatory fields handling
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
  geonode/templates/metadata_form_js.html
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7111 [Fixes #7094] Facet titles alignment
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7106 [Fixes: #7105] Remove HTML tags from visualization
  geonode/base/models.py
  geonode/base/tests.py
  geonode/catalogue/templates/geonode_metadata_full.html
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7116 [Backport to 3.1.x #7105] Remove HTML tags from metadata detail
  geonode/base/models.py
  geonode/base/tests.py
  geonode/catalogue/templates/geonode_metadata_full.html
Labels: cla-signed

#7117 [Backport to 3.2.x #7105] Remove HTML tags from metadata detail
  geonode/base/models.py
  geonode/base/tests.py
  geonode/catalogue/templates/geonode_metadata_full.html
Labels: cla-signed

#7120 [Fixes #7118] CSW prefiltering URLs
  geonode/catalogue/views.py
Labels: backport 3.2.x, cla-signed

#7121 [Backport to 3.2.x][Fixes #7118] CSW prefiltering URLs
  geonode/catalogue/views.py
Labels: cla-signed

#7115 [Fixes #7114] Thumbnail upload issue
  geonode/thumbs/thumbnails.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7132 [Backport to 3.2.x][Fixes #7114] Thumbnail upload issue (#7115)
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#7133 [Backport to 3.1.x][Fixes #7114] Thumbnail upload issue (#7115)
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#7134 [Backport #7057] ResourceBase for metadata-only resources
  geonode/api/api.py
  geonode/api/resourcebase_api.py
  geonode/api/tests.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/migrations/0057_resourcebase_metadata_only.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/maps/tests.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#7127 [Fixes #7101] Error in preview
  .gitignore
  geonode/base/fixtures/test_thesaurus.json
  geonode/base/forms.py
  geonode/base/tests.py
  geonode/context_processors.py
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/templates/metadata_base.html
  geonode/templates/metadata_form_js.html
Labels: backport 3.2.x, cla-signed

#7131 [Fixes #7129] Clearing the region filter the list of contents is not reset
  geonode/static/geonode/js/search/search.js
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7137 [Backport 3.1.x] fix region search function (#7131)
  geonode/static/geonode/js/search/search.js
Labels: cla-signed

#7138 [Backport #7101] Error in preview
  geonode/base/fixtures/test_thesaurus.json
  geonode/base/forms.py
  geonode/base/tests.py
  geonode/context_processors.py
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/templates/metadata_base.html
  geonode/templates/metadata_form_js.html
Labels: cla-signed

#7119 [Fixes #7104] Use link to resource instead of download for the documents preview
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/tests.py
  geonode/documents/urls.py
  geonode/documents/utils.py
  geonode/documents/views.py
Labels: backport 3.2.x, backport 3.x, cla-signed

#7140 [Backport to 3.2.x #7104] Use link to resource instead of download for the documents preview
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/tests.py
  geonode/documents/urls.py
  geonode/documents/utils.py
  geonode/documents/views.py
Labels: cla-signed

#7149 [Backport to 3.1.x #7104] Use link to resource instead of download for the documents preview
  geonode/documents/templates/documents/document_detail.html
  geonode/documents/tests.py
  geonode/documents/urls.py
  geonode/documents/utils.py
  geonode/documents/views.py
Labels: cla-signed

#7151 [Fixes #7135][Advanced Workflow] Non admin user cannot change permission
  geonode/base/templatetags/base_tags.py
  geonode/base/tests.py
  geonode/documents/templates/documents/document_thumb_upload.html
  geonode/documents/templates/documents/document_upload.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoserver/createlayer/templates/createlayer/layer_create.html
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/layers/templates/layers/layer_metadata_upload.html
  geonode/layers/templates/layers/layer_replace.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/templates/upload/layer_upload.html
  geonode/maps/templates/layouts/map_panels.html
  geonode/security/utils.py
  geonode/themes/tests.py
  geonode/upload/upload.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7153 [Backport to 3.1.x][Fixes #7135][Advanced Workflow] Non admin user cannot change permission
  geonode/__init__.py
  geonode/base/templatetags/base_tags.py
  geonode/base/tests.py
  geonode/documents/templates/documents/document_thumb_upload.html
  geonode/documents/templates/documents/document_upload.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoserver/createlayer/templates/createlayer/layer_create.html
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/layers/templates/layers/layer_metadata_upload.html
  geonode/layers/templates/layers/layer_replace.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/templates/upload/layer_upload.html
  geonode/maps/templates/layouts/map_panels.html
  geonode/security/utils.py
  geonode/themes/tests.py
  geonode/upload/upload.py
Labels: cla-signed

#7165 [Fixes #7164] restore does not delete table in uppercase/camelcase
  geonode/br/management/commands/utils/utils.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7166 [Backport 3.2.x ][Fixes #7164] restore does not delete table in uppercase/camelcase
  geonode/br/management/commands/utils/utils.py
Labels: cla-signed

#7167 [Backport 3.1.x][Fixes #7164] restore does not delete table in uppercase/camelcase
  geonode/br/management/commands/utils/utils.py
Labels: cla-signed

#7168 [Fixes #7164] BK_BEST_EFFORT always true
  geonode/br/management/commands/restore.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7169 [Backport 3.2.x][Fixes #7164] change BK_BEST_EFFORT to true
  geonode/br/management/commands/restore.py
Labels: cla-signed

#7155 [Fixes #7150] Upload RDF thesaurus via web
  geonode/base/admin.py
  geonode/base/forms.py
  geonode/base/templates/admin/thesauri/change_list.html
  geonode/base/templates/admin/thesauri/upload_form.html
Labels: backport 3.2.x, cla-signed

#7156 [Backport Fixes #7150] Thesaurus from web
  geonode/base/admin.py
  geonode/base/forms.py
  geonode/base/templates/admin/thesauri/change_list.html
  geonode/base/templates/admin/thesauri/upload_form.html
Labels: cla-signed

#7162 [Fixes #7160] Review CSW filtering in pycsw_plugin
  geonode/catalogue/backends/pycsw_plugin.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7161 [Fixes #7157] CSW metadata includes accessToken and invalid attributes
  geonode/catalogue/views.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7174 [Fixes #7173] Improve the "get_visibile_reources" method: replace for…
  geonode/security/tests.py
  geonode/security/utils.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7179 [Backport to 3.2.x][Fixes #7173] Improve the "get_visibile_reources" method: replace for…
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#7180 [Backport to 3.1.x][Fixes #7173] Improve the "get_visibile_reources" method: replace for…
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#7175 [Backport to 3.2.x][Fixes #7160] Review CSW filtering in pycsw_plugin (#7162)
  geonode/catalogue/backends/pycsw_plugin.py
Labels: cla-signed

#7176 [Backport to 3.2.x][Fixes #7157] CSW metadata includes accessToken and invalid attribute…
  geonode/catalogue/views.py
Labels: cla-signed

#7177 [Backport to 3.1.x][Fixes #7160] Review CSW filtering in pycsw_plugin (#7162)
  geonode/catalogue/backends/pycsw_plugin.py
Labels: cla-signed

#7178 [Backport to 3.1.x][Fixes #7157] CSW metadata includes accessToken and invalid attribute…
  geonode/catalogue/views.py
Labels: cla-signed

#7184 [Fixes #7183] Remote services do not associate correctly the GeoNode …
  geonode/layers/models.py
  geonode/services/admin.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/tasks.py
  geonode/services/tests.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7192 [Backport to 3.2.x][Fixes #7183] Remote services do not associate correctly the GeoNode Layer to HarvestJob
  geonode/layers/models.py
  geonode/services/admin.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/tasks.py
  geonode/services/tests.py
Labels: cla-signed

#7193 [Backport to 3.1.x][Fixes #7183] Remote services do not associate correctly the GeoNode Layer to HarvestJob
  geonode/layers/models.py
  geonode/services/admin.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/tasks.py
  geonode/services/tests.py
Labels: cla-signed

#7171 [Fixes #7109] Disable edit permissions globally when read-only mode is active
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/views.py
  geonode/security/models.py
  geonode/security/tests.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7198 [Fixes #7197] Missing parenthesis in feature_edit_check
  geonode/geoserver/views.py
Labels: backport 3.1.x, backport 3.2.x, cla-signed

#7205 [Backport to 3.2.x] add resource base permissions (#7202)
  geonode/security/models.py
Labels: cla-signed

#7206 [Backport to 3.1.x] add resource base permissions (#7202)
  geonode/security/models.py
Labels: cla-signed

#7195 [Fixes #7194] Append data to an existing layer
  geonode/base/populate_test_data.py
  geonode/layers/templates/layers/layer_append.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/tests.py
  geonode/layers/urls.py
  geonode/layers/utils.py
  geonode/layers/views.py
Labels: backport 3.2.x, cla-signed

#7207 [Backport to 3.2.x][Fixes #7194] Append data to an existing layer (#7195)
  geonode/base/populate_test_data.py
  geonode/layers/templates/layers/layer_append.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/tests.py
  geonode/layers/urls.py
  geonode/layers/utils.py
  geonode/layers/views.py
Labels: cla-signed

#7209 [Fixes #7208] Help strings in advanced metadata template appear truncated
  geonode/templates/metadata_base.html
Labels: cla-signed
