Repository GeoNode/geonode, pull requests merged in 2021-01, with the labels that each got.

#6776 [Fixes #6774] EXIF data will not get read
  geonode/documents/exif/utils.py
  geonode/documents/models.py
  geonode/documents/views.py
Labels: cla-signed

#6775 [Fixes #6779] Improve GeoApps REST serializer
  geonode/geoapps/api/serializers.py
Labels: enhancement

#6781 [FIXES #6773] Request Download button will fail to sent notification
  geonode/security/views.py
Labels: cla-signed

#6783 [FIXES #6782] Approval notifications will not get send
  geonode/notifications_helper.py
Labels: cla-signed

#6785 [Fixes #6784] Style Manage view won't take into account styles from "…
  geonode/geoserver/views.py
Labels: cla-signed

#6787 [Fixes ##6772] Remove Open Data Link
  geonode/templates/developer.html
Labels: backport 3.x, cla-signed

#6818 [Fixes #6817] Displaying document 'image/tiff' is broken because bro…
  geonode/documents/enumerations.py
  geonode/documents/tests.py
Labels: cla-signed

#6816 [Fixes #6780] uploading a shapefile with paver setup (and spc) does n…
  .env_dev
  geonode/geoserver/tasks.py
  geonode/layers/templates/layers/layer_remove.html
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/local_settings.py.geoserver.sample
  geonode/monitoring/utils.py
  geonode/services/tasks.py
  geonode/tasks/tasks.py
  geonode/tests/csw.py
  package/support/geonode.local_settings
  scripts/spcgeonode/django/Dockerfile
  scripts/spcgeonode/django/docker-entrypoint.sh
  scripts/spcgeonode/docker-compose.override.yml
  scripts/spcgeonode/docker-compose.yml
Labels: cla-signed

#6831 Updated .clabot for Catalyst Academy students
  .clabot
Labels: cla-signed

#6842 [Fixes #6714] Fixing typo: 'Pubblication' to 'Publication'
  geonode/base/templates/base/_resourcebase_info_panel.html
  geonode/locale/af/LC_MESSAGES/django.po
  geonode/locale/al/LC_MESSAGES/django.po
  geonode/locale/am/LC_MESSAGES/django.po
  geonode/locale/ar/LC_MESSAGES/django.po
  geonode/locale/bg_BG/LC_MESSAGES/django.po
  geonode/locale/bn/LC_MESSAGES/django.po
  geonode/locale/de/LC_MESSAGES/django.po
  geonode/locale/el/LC_MESSAGES/django.po
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/fa/LC_MESSAGES/django.po
  geonode/locale/fa_IR/LC_MESSAGES/django.po
  geonode/locale/fi/LC_MESSAGES/django.po
  geonode/locale/fil/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/hu/LC_MESSAGES/django.po
  geonode/locale/id/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/locale/ja/LC_MESSAGES/django.po
  geonode/locale/ka/LC_MESSAGES/django.po
  geonode/locale/km/LC_MESSAGES/django.po
  geonode/locale/ko/LC_MESSAGES/django.po
  geonode/locale/lt/LC_MESSAGES/django.po
  geonode/locale/ne/LC_MESSAGES/django.po
  geonode/locale/nl_NL/LC_MESSAGES/django.po
  geonode/locale/no/LC_MESSAGES/django.po
  geonode/locale/pl/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/locale/ro/LC_MESSAGES/django.po
  geonode/locale/ru/LC_MESSAGES/django.po
  geonode/locale/si/LC_MESSAGES/django.po
  geonode/locale/sq/LC_MESSAGES/django.po
  geonode/locale/sv/LC_MESSAGES/django.po
  geonode/locale/sw/LC_MESSAGES/django.po
  geonode/locale/ta/LC_MESSAGES/django.po
  geonode/locale/th/LC_MESSAGES/django.po
  geonode/locale/tl/LC_MESSAGES/django.po
  geonode/locale/uk/LC_MESSAGES/django.po
  geonode/locale/vi/LC_MESSAGES/django.po
  geonode/locale/zh/LC_MESSAGES/django.po
Labels: cla-signed

#6873 [Fixes #6872] Ghost message on Metadata Wizard page
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
Labels: cla-signed

#6870 [Fixes #6867] HTML mode for GetFeatureInfo results template missing i…
  geonode/layers/templates/layers/layer_metadata_advanced.html
Labels: cla-signed

#6875 [Fixes #6874] Search filter string is not reset per search box is cle…
  geonode/static/geonode/js/search/search.js
Labels: cla-signed

#6868 [Fixes #6865] Embedding a map/geo-app on an IFRAME may fail due to X-…
  scripts/docker/nginx/geonode.conf.envsubst
  scripts/misc/nginx_integration.conf
  scripts/spcgeonode/nginx/spcgeonode.conf
Labels: cla-signed

#6858 Revert "Updated .clabot for Catalyst Academy students (#6831)"
  .clabot
Labels: cla-signed

#6847 [Issue #6843] Simplify logic blocks
  geonode/layers/management/commands/importlayers.py
  geonode/layers/utils.py
  geonode/upload/utils.py
  geonode/utils.py
Labels: backport 3.x, cla-signed

#6871 [Fixes #6856] Inconsistent behavior between document and layer upload…
  geonode/documents/tests.py
  geonode/documents/views.py
Labels: cla-signed

#6853 [Issue #6843] Remove use of some magic numbers
  geonode/utils.py
Labels: cla-signed

#6836 [Issue #6843] Remove redundant enumerate calls
  geonode/base/models.py
  geonode/layers/views.py
  geonode/proxy/templatetags/proxy_lib_tags.py
  geonode/security/utils.py
  geonode/utils.py
Labels: cla-signed

#6869 [Fixes #6866] What is the effect of assigning permissions to styles?
  geonode/layers/templates/layers/layer_style_upload.html
  geonode/layers/tests.py
Labels: cla-signed

#6878 [Fixes #6877] Notification settings for monitoring must be hidden to …
  geonode/base/templatetags/user_messages.py
  geonode/base/tests.py
  geonode/settings.py
  geonode/templates/pinax/notifications/notice_settings.html
Labels: cla-signed

#6884 [Fixes #6883] Monitoring & Analytics integrated client run a infinite…
  geonode/monitoring/frontend/monitoring/src/components/molecules/average-cpu/index.js
  geonode/monitoring/frontend/monitoring/src/components/molecules/average-memory/index.js
  geonode/monitoring/frontend/monitoring/src/components/molecules/average-response-time/index.js
  geonode/monitoring/frontend/monitoring/src/components/molecules/max-response-time/index.js
  geonode/monitoring/frontend/monitoring/src/components/molecules/total-requests/index.js
  geonode/monitoring/frontend/package.json
  geonode/monitoring/static/monitoring/bundle.js
Labels: backport 3.x, cla-signed

#6889 [Fixes #6888] Map and Layer thumbnail views do not correctly manage r…
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/settings.py
  test.sh
Labels: backport 3.x, cla-signed

#6854 [Issue #6843] Remove redundant method override
  geonode/base/tests.py
Labels: cla-signed

#6850 [Issue #6843] Change relevant print statements to logger
  geonode/base/management/commands/migrate_baseurl.py
  geonode/base/management/commands/set_all_layers_alternate.py
  geonode/base/management/commands/set_all_layers_metadata.py
  geonode/base/management/commands/set_all_layers_public.py
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
  geonode/br/management/commands/utils/utils.py
  geonode/qgis_server/helpers.py
  geonode/qgis_server/management/commands/import_qgis_styles.py
  geonode/qgis_server/views.py
  geonode/services/management/commands/importservice.py
  pavement.py
  scripts/cloud/ec2.py
  scripts/cloud/fabfile.py
  tasks.py
Labels: cla-signed

#6840 [Issue #6843] Close open file descriptors
  geonode/br/management/commands/backup.py
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/upload.py
  geonode/geoserver/views.py
  geonode/layers/views.py
  geonode/monitoring/tests/integration.py
  geonode/proxy/views.py
  geonode/tests/integration.py
  geonode/tests/utils.py
  geonode/upload/utils.py
  scripts/cloud/ec2.py
Labels: cla-signed

#6837 [Issue #6843] Replace body of Layer.display_type with a conditional
  geonode/layers/models.py
Labels: cla-signed

#6835 [Issue #6843] Replaced lists with sets for in-line lookups
  geonode/api/resourcebase_api.py
  geonode/base/management/commands/delete_resources.py
  geonode/base/management/commands/helpers.py
  geonode/base/utils.py
  geonode/br/management/commands/utils/utils.py
  geonode/catalogue/backends/pycsw_plugin.py
  geonode/documents/exif/utils.py
  geonode/geoserver/helpers.py
  geonode/layers/utils.py
  geonode/security/utils.py
  geonode/tests/csw.py
  geonode/tests/integration.py
  geonode/utils.py
  pavement.py
Labels: cla-signed

#6838 [Issue #6843] Use generators as parameters to compatible functions
  geonode/base/admin.py
  geonode/base/models.py
  geonode/base/templatetags/base_tags.py
  geonode/documents/tests.py
  geonode/layers/models.py
  geonode/layers/tests.py
  geonode/maps/models.py
  geonode/maps/tests.py
  geonode/monitoring/service_handlers.py
  geonode/monitoring/tests/integration.py
  geonode/people/tests.py
  geonode/qgis_server/helpers.py
  geonode/qgis_server/tests/test_views.py
  geonode/upload/upload_validators.py
  geonode/utils.py
Labels: cla-signed

#6844 [Issue #6843] Replace encode-decode instances with utility function
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
Labels: cla-signed

#6845 [Issue #6843] Fetch dictionary keys with dict.get(...) where appropriate to provide default value
  geonode/base/templatetags/base_tags.py
  geonode/geoserver/helpers.py
  geonode/layers/utils.py
  geonode/maps/tests.py
  geonode/utils.py
Labels: cla-signed

#6890 [Fixes #6886] Swap static files finders
  geonode/settings.py
Labels: backport 3.x, cla-signed

#6898 [Fixes #6897] [Backport to 3.x] Async generation of thumbs in order t…
  docker-compose.development.yml
  docker-compose.yml
  geonode/geoserver/signals.py
  geonode/geoserver/tasks.py
  pavement.py
  requirements.txt
  scripts/spcgeonode/docker-compose.override.yml
  scripts/spcgeonode/docker-compose.yml
  setup.cfg
Labels: cla-signed

#6893 [Fixes: #6891] Update Axios
  geonode/monitoring/frontend/package.json
  geonode/monitoring/static/monitoring/bundle.js
Labels: cla-signed, security

#6896 [Fixes #6895] Correcly catching thumbnail async task errors
  geonode/geoserver/tasks.py
  geonode/geoserver/tests/test_server.py
  geonode/layers/utils.py
Labels: cla-signed

#6894 [Fixes #6899] Customize metadata template
  geonode/catalogue/metadataxsl/views.py
  geonode/catalogue/models.py
  geonode/catalogue/templates/catalogue/transaction_insert.xml
  geonode/catalogue/templates/catalogue/transaction_update.xml
  geonode/catalogue/templates/catalogue/transaction_update_gn.xml
  geonode/context_processors.py
  geonode/settings.py
Labels: cla-signed, feature
