Repository GeoNode/geonode, pull requests merged in 2021-09, with the labels that each got.

#8029 [Fixes #8003] Update Spanish Translation
  geonode/locale/es/LC_MESSAGES/django.mo
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/djangojs.mo
  geonode/locale/es/LC_MESSAGES/djangojs.po
Labels: cla-signed, backport 3.2.x

#8031 [Backport to 3.3.x][Fixes #8003] Update Spanish Translation (#8029)
  geonode/locale/es/LC_MESSAGES/django.mo
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/djangojs.mo
  geonode/locale/es/LC_MESSAGES/djangojs.po
Labels: cla-signed

#8028 [Fixes #8026] Implement support for TMS thumbnail backgrounds
  geonode/harvesting/harvesters/geonode.py
  geonode/settings.py
  geonode/thumbs/background.py
  geonode/thumbs/tests/expected_results/background/tms_outcome1.png
  geonode/thumbs/tests/expected_results/background/tms_outcome2.png
  geonode/thumbs/tests/expected_results/background/tms_outcome3.png
  geonode/thumbs/tests/expected_results/background/tms_outcome4.png
  geonode/thumbs/tests/test_integration.py
Labels: cla-signed, backport 3.3.x

#8032 [Backport to 3.3.x][Fixes #8026] Implement support for TMS thumbnail backgrounds (#8028)
  geonode/settings.py
  geonode/thumbs/background.py
  geonode/thumbs/tests/expected_results/background/tms_outcome1.png
  geonode/thumbs/tests/expected_results/background/tms_outcome2.png
  geonode/thumbs/tests/expected_results/background/tms_outcome3.png
  geonode/thumbs/tests/expected_results/background/tms_outcome4.png
  geonode/thumbs/tests/test_integration.py
Labels: cla-signed

#8023 [3.3.x][Fixes #8005] Create an abstract GeoNode hook for the layer export
  geonode/client/hooksets.py
Labels: cla-signed

#8034 [Fixes #8033] Get user permission on ResourceBase model always returns the full set of perms despite the 'subtype': rasters can edit styles
  geonode/layers/tests.py
  geonode/security/models.py
  geonode/security/permissions.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#8036 Change location of invokeadmin task.
  .env
  entrypoint.sh
Labels: docker

#8002 [Backport3.3.x][Fixes #7999] Set bulk permissions from resources list pages
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/security/tests.py
  geonode/security/views.py
  geonode/static/geonode/js/search/cart.js
  geonode/templates/_bulk_permissions_form.html
  geonode/templates/_update_permissions_modal.html
  geonode/templates/search/_search_content.html
Labels: cla-signed

#8039 [Fixes #6631] Remote Service does not use GetMap url as given in capabilities-document
  geonode/services/migrations/0046_service_extra_queryparams.py
  geonode/services/migrations/0047_service_operations.py
  geonode/services/models.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/base.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/tasks.py
  geonode/services/tests.py
  geonode/services/views.py
  geonode/settings.py
  geonode/thumbs/utils.py
  geonode/utils.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8038 [Fixes #7927] Docker 3.3.x GeoNode core theme is not changing
  geonode/templates/base.html
Labels: cla-signed, backport 3.2.x

#8040 [Backport to 3.3.x][Fixes #6631] Remote Service does not use GetMap url as given in capabilities-document
  geonode/layers/models.py
  geonode/services/migrations/0046_auto_20210903_1427.py
  geonode/services/models.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/base.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/tasks.py
  geonode/services/tests.py
  geonode/services/views.py
  geonode/thumbs/tests/test_integration.py
  geonode/thumbs/tests/test_unit.py
  geonode/utils.py
Labels: cla-signed, backport 3.2.x

#8054 [Fixes #8053] Emebed page for documents
  geonode/documents/templates/documents/document_embed.html
  geonode/documents/urls.py
  geonode/documents/utils.py
  geonode/documents/views.py
Labels: feature, cla-signed, frontend

#7827 [Fixes #7826] Implement tests for harvesters
  geonode/harvesting/api/serializers.py
  geonode/harvesting/config.py
  geonode/harvesting/harvesters/base.py
  geonode/harvesting/migrations/0029_dynamic_harvester_type_choices.py
  geonode/harvesting/models.py
  geonode/harvesting/tests/__init__.py
  geonode/harvesting/tests/factories.py
  geonode/harvesting/tests/harvesters/__init__.py
  geonode/harvesting/tests/harvesters/base.py
  geonode/harvesting/tests/harvesters/geonode.py
  geonode/harvesting/tests/harvesters/test_harvester.py
  geonode/harvesting/tests/test_admin.py
  geonode/harvesting/tests/test_api_serializers.py
  geonode/harvesting/tests/test_api_views.py
  geonode/harvesting/tests/test_config.py
  geonode/harvesting/tests/test_models.py
  geonode/harvesting/tests/test_tasks.py
  geonode/harvesting/tests/test_utils.py
  geonode/harvesting/utils.py
  geonode/templates/admin/base_site.html
Labels: cla-signed

#8063 [3.3.x][Fixes #8051] Wrong URL inside Admin profile -> GeoServer Tab.
  geonode/people/templates/people/profile_detail.html
  geonode/templates/500.html
Labels: cla-signed

#8065 [Fixes #8051] Wrong URL inside Admin profile -> GeoServer Tab.
  geonode/people/templates/people/profile_detail.html
  geonode/templates/500.html
Labels: cla-signed

#8066 [Backport 3.2.x] [Fixes #8051] Wrong URL inside Admin profile -> GeoServer Tab.
  geonode/people/templates/people/profile_detail.html
  geonode/templates/500.html
Labels: cla-signed

#8074 [Fixes #8071] Add migration to upgrade preexisting remote services
  geonode/services/migrations/0047_service_operations.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8070 [Fixes #8069] Upload step without _ASYNC_UPLOAD set throws an error if the request is None
  geonode/upload/utils.py
Labels: cla-signed

#8075 [Backport to 3.3.x][Fixes #8071] Add migration to upgrade preexisting…
  geonode/services/migrations/0046_auto_20210903_1427.py
Labels: cla-signed

#8076 [Backport to 3.2.x][Fixes #8071] Add migration to upgrade preexisting…
  geonode/services/migrations/0046_auto_20210903_1427.py
Labels: cla-signed

#8096 [Fixes #8082] Despite several layers are not available for public acc…
  geonode/catalogue/metadataxsl/tests.py
  geonode/catalogue/metadataxsl/views.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8086 [Fixes #8083] Remote Services "_resolve_dataset" does not work proper…
  geonode/layers/views.py
  geonode/services/tests.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8087 [Backport to 3.2.x][Fixes #8083] Remote Services "_resolve_layer" doe…
  geonode/layers/views.py
  geonode/services/tests.py
Labels: cla-signed

#8088 [Backport to 3.3.x][Fixes #8083] Remote Services "_resolve_layer" doe…
  geonode/layers/views.py
  geonode/services/tests.py
Labels: cla-signed

#8100 [Fixes #8099] fix service url for remote service handler
  geonode/services/tasks.py
Labels: backport 3.2.x

#8117 [Fixes #8116] Add a call to RM.update inside sync_geonode_layers command
  geonode/geoserver/management/commands/sync_geonode_datasets.py
Labels: cla-signed

#8089 [Backport to 3.3.x][Fixes #8061] Fix preserve_tables conditional chec…
  geonode/br/management/commands/utils/utils.py
Labels: cla-signed

#8090 [Backport to 3.3.x][Fixes #8061] Fix preserve_tables conditional chec…
  geonode/br/management/commands/utils/utils.py
Labels: cla-signed

#8092 [Backport to 3.3.x][Fixes #7928] Geonode Project 3.2x Backup Failure—…
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
Labels: cla-signed

#8084 [Fixes #428] After a document upload the user is redirected to the legacy page
  geonode/documents/views.py
Labels: cla-signed

#8102 [Fixes #8101] Fixes to documents embed
  geonode/base/populate_test_data.py
  geonode/documents/models.py
  geonode/documents/tests.py
  geonode/documents/utils.py
  geonode/documents/views.py
Labels: cla-signed

#8123 [master][Fixes #8112] Dump and restore Geofence rules in case of requests or …
  geonode/geoserver/manager.py
  geonode/geoserver/security.py
  geonode/resource/manager.py
Labels: cla-signed

#8128 Revert "[master][Fixes #8112] Dump and restore Geofence rules in case of requests or …"
  geonode/geoserver/manager.py
  geonode/geoserver/security.py
  geonode/resource/manager.py
Labels: cla-signed

#8113 [3.3.x][Fixes #8112] Dump and restore Geofence rules in case of requests or transaction failures
  geonode/layers/models.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed, backport 3.2.x

#8130 [Backport to 3.2.x][Fixes #8112] Dump and restore Geofence rules in case of reque…
  geonode/layers/models.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#8134 Revert "[3.3.x][Fixes #8112] Dump and restore Geofence rules in case …
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#8135 [3.3.x] 3.3.x updated to geoserver 2.19.x
  docker-compose.yml
Labels: dependencies

#8138 [Fixes #8124] By removing anyone from initial perms won't allow to ad…
  geonode/security/permissions.py
  geonode/security/tests.py
Labels: cla-signed

#8137 [Fixes #8125] [3.x] Initial upload GeoFence permissions do not match the selected ones
  geonode/security/models.py
  geonode/security/tests.py
Labels: cla-signed, backport 3.2.x

#8155 [Fixes #8154] GeoNode tries to retrieve Geofence rules for Geoserver …
  geonode/security/utils.py
Labels: cla-signed

#8157 [Fixes #8156] Implement mobile detection
  geonode/settings.py
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 3.3.x

#8159 [3.3.x][Fixes #8156] Implement mobile detection
  geonode/settings.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#8052 [Fixes GeoNode#7976] Create app for management commands
  geonode/management_commands_http/__init__.py
  geonode/management_commands_http/admin.py
  geonode/management_commands_http/management/__init__.py
  geonode/management_commands_http/management/commands/__init__.py
  geonode/management_commands_http/management/commands/ping_mngmt_commands_http.py
  geonode/management_commands_http/migrations/0001_initial.py
  geonode/management_commands_http/migrations/__init__.py
  geonode/management_commands_http/models.py
  geonode/management_commands_http/serializers.py
  geonode/management_commands_http/tasks.py
  geonode/management_commands_http/tests.py
  geonode/management_commands_http/urls.py
  geonode/management_commands_http/utils/__init__.py
  geonode/management_commands_http/utils/commands.py
  geonode/management_commands_http/utils/job_runner.py
  geonode/management_commands_http/utils/jobs.py
  geonode/management_commands_http/views.py
  geonode/settings.py
  geonode/urls.py
Labels: cla-signed

#8162 [Fixes #8161] Disable some GeoNode features when viewed from mobile
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/documents/templates/documents/document_detail.html
  geonode/geoapps/templates/apps/app_detail.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/maps/templates/maps/map_detail.html
  geonode/templates/_actions.html
  geonode/templates/base.html
  geonode/templates/index.html
  geonode/templates/search/_pagination.html
  geonode/templates/search/_search_content.html
  geonode/templates/search/_text_filter.html
Labels: cla-signed, frontend

#8064 [3.3.x][Fixes #8058] GeoStory: missing actions in user profile page
  geonode/people/templates/people/_profile_filters.html
  geonode/people/templates/people/profile_detail.html
  geonode/static/geonode/js/search/search.js
Labels: cla-signed

#8067 [Backport 3.2.x][Fixes #8058] GeoStory: missing actions in user profile page
  geonode/people/templates/people/_profile_filters.html
  geonode/people/templates/people/profile_detail.html
  geonode/static/geonode/js/search/search.js
Labels: cla-signed

#8081 [Backport 3.3.x][Fixes #8057] GeoStory: missing tab in recent activities
  geonode/social/apps.py
  geonode/social/signals.py
  geonode/social/templates/social/activity_list.html
  geonode/social/templatetags/social_tags.py
  geonode/social/tests.py
  geonode/social/views.py
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
Labels: cla-signed

#8114 [3.3.x][Fixes #8059]GeoStory: missing "favorite" handling
  geonode/favorite/tests.py
  geonode/favorite/urls.py
  geonode/favorite/views.py
  geonode/geoapps/templates/apps/app_detail.html
  geonode/geoapps/views.py
Labels: cla-signed

#8121 [Backport 3.3.x][Fixes #8060] GeoStory: missing/bad labels
  geonode/geoapps/templates/apps/app_detail.html
  geonode/geoapps/templates/apps/app_metadata_advanced.html
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/templates/social_links.html
Labels: cla-signed

#8145 [Fixes #8136] Review advanced workflow
  .env_dev
  geonode/base/populate_test_data.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: major, cla-signed

#7947 [Fixes #7945] Ingest harvested layer data to geonode
  geonode/geoserver/manager.py
  geonode/harvesting/admin.py
  geonode/harvesting/api/serializers.py
  geonode/harvesting/config.py
  geonode/harvesting/harvesters/base.py
  geonode/harvesting/harvesters/geonodeharvester.py
  geonode/harvesting/migrations/0030_alter_harvester_num_harvestable_resources.py
  geonode/harvesting/migrations/0030_auto_20210917_1125.py
  geonode/harvesting/migrations/0031_remove_harvestingsession_total_records_found.py
  geonode/harvesting/migrations/0032_harvestingsession_session_details.py
  geonode/harvesting/migrations/0033_alter_harvestingsession_status.py
  geonode/harvesting/migrations/0034_harvester_unique name.py
  geonode/harvesting/migrations/0035_replace_geonode_harvester_module_name.py
  geonode/harvesting/migrations/0036_alter_harvester_harvester_type.py
  geonode/harvesting/models.py
  geonode/harvesting/tasks.py
  geonode/harvesting/tests/harvesters/geonode.py
  geonode/harvesting/tests/test_admin.py
  geonode/harvesting/tests/test_api_serializers.py
  geonode/harvesting/tests/test_api_views.py
  geonode/harvesting/tests/test_harvester_worker_geonode_legacy.py
  geonode/harvesting/tests/test_models.py
  geonode/harvesting/tests/test_tasks.py
Labels: cla-signed

#8181 [3.3.x][Fixes #8180] CSS improvements for mobile 3.3.x only
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/client/templates/leaflet/maps/map_list.html
  geonode/documents/templates/documents/document_list.html
  geonode/geoapps/templates/apps/app_list_default.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/maps/templates/maps/map_list_default.html
  geonode/people/templates/people/profile_detail.html
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
  geonode/static/geonode/less/mobile.less
  geonode/static/package.json
  geonode/templates/_actions.html
  geonode/templates/account/signup.html
  geonode/templates/base.html
  geonode/templates/index.html
  geonode/templates/search/_search_content.html
Labels: cla-signed

#8182 [Fixes #7976] Create app for management commands
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/management_commands_http/__init__.py
  geonode/management_commands_http/admin.py
  geonode/management_commands_http/filters.py
  geonode/management_commands_http/forms.py
  geonode/management_commands_http/management/__init__.py
  geonode/management_commands_http/management/commands/__init__.py
  geonode/management_commands_http/management/commands/ping_mngmt_commands_http.py
  geonode/management_commands_http/migrations/0001_initial.py
  geonode/management_commands_http/migrations/__init__.py
  geonode/management_commands_http/mixins.py
  geonode/management_commands_http/models.py
  geonode/management_commands_http/routers.py
  geonode/management_commands_http/serializers.py
  geonode/management_commands_http/tasks.py
  geonode/management_commands_http/tests.py
  geonode/management_commands_http/urls.py
  geonode/management_commands_http/utils/__init__.py
  geonode/management_commands_http/utils/commands.py
  geonode/management_commands_http/utils/job_runner.py
  geonode/management_commands_http/utils/jobs.py
  geonode/management_commands_http/views.py
  geonode/settings.py
  geonode/urls.py
Labels: cla-signed
