Repository GeoNode/geonode, pull requests merged in 2021-07, with the labels that each got.

#7745 [Fixes #7728] Enforce add_resourcebase permission control everywhere
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/documents/templates/documents/document_list.html
  geonode/geoapps/templates/apps/app_list_default.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_list_default.html
  geonode/people/templates/people/profile_detail.html
  geonode/services/templates/services/service_list.html
  geonode/templates/500.html
  geonode/templates/base.html
Labels: cla-signed

#7743 [Fixes #7741] Expose document link as embed_url inside API v2 response
  geonode/documents/api/tests.py
  geonode/documents/models.py
Labels: backport 3.2.x, cla-signed

#7748 [Backport to 3.2.x] [Fixes #7741] Expose document link as embed_url inside API v2 response
  geonode/documents/api/tests.py
  geonode/documents/models.py
Labels: cla-signed

#7749 [Fixes #7747] Metadata wizard: mandatory tag does not switch to green
  geonode/layers/templates/layers/layer_metadata.html
  geonode/settings.py
  geonode/templates/metadata_form_js.html
Labels: backport 3.2.x, cla-signed

#7773 [Fixes #7768 ]
  geonode/layers/templates/layers/layer_change_poc.html
  geonode/layers/views.py
Labels: cla-signed, enhancement

#7791 [Fixes #7787] Replace layer_thumbnail method with new API v2 endpoint
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/urls.py
  geonode/layers/views.py
  geonode/static/geonode/js/utils/thumbnail.js
  geonode/thumbs/tests/test_integration.py
  geonode/thumbs/thumbnails.py
Labels: backport 3.2.x, cla-signed

#7769 [Fixes #7767] Rename storetype into subtype
  geonode/api/resourcebase_api.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/migrations/0068_rename_storetype_resourcebase_subtype.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/base/templatetags/base_tags.py
  geonode/base/tests.py
  geonode/catalogue/templates/catalogue/full_metadata.xml
  geonode/documents/api/serializers.py
  geonode/documents/forms.py
  geonode/documents/templates/documents/document_list.html
  geonode/geoserver/createlayer/utils.py
  geonode/geoserver/helpers.py
  geonode/geoserver/manager.py
  geonode/geoserver/templates/geoserver/layer.xml
  geonode/geoserver/upload.py
  geonode/layers/admin.py
  geonode/layers/api/serializers.py
  geonode/layers/forms.py
  geonode/layers/models.py
  geonode/layers/search_indexes.py
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/resource/utils.py
  geonode/security/tests.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
  geonode/templates/_permissions_form.html
  geonode/thumbs/tests/fixtures/layer.json
  geonode/thumbs/tests/fixtures/map_layer.json
  geonode/thumbs/thumbnails.py
  geonode/upload/upload.py
  geonode/utils.py
Labels: cla-signed

#7790 [Backport][Fixes #7740] patch fix reverse urls
  geonode/base/views.py
  geonode/people/forms.py
Labels: cla-signed

#7775 [Forward #7773] Drop layer_change_poc unused method and template
  geonode/layers/templates/layers/layer_change_poc.html
  geonode/layers/views.py
  geonode/people/forms.py
Labels: backport 3.2.x, cla-signed, enhancement, targets master

#7800 [Fixes #7789]: Defer attributes_set property inside the API v2 datasets list endpoint
  geonode/layers/api/serializers.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
Labels: cla-signed

#7798 [Fixes #7794] Keep serializer consistent with the new ResourceBase.sutype
  geonode/base/api/serializers.py
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_helpers.py
  geonode/upload/upload.py
Labels: cla-signed

#7799 [Fixes #7757] Remove read only check inside templates
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/documents/templates/documents/document_list.html
  geonode/geoapps/templates/apps/app_list_default.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/templates/maps/map_list_default.html
  geonode/people/templates/people/profile_detail.html
  geonode/services/templates/services/service_list.html
  geonode/templates/500.html
  geonode/templates/base.html
Labels: backport 3.2.x, cla-signed

#7804 [Fixes #7803] Allow extensibility of classes of html and body tag inside the base.html temeplate
  geonode/templates/base.html
Labels: cla-signed

#7797 [Backport][Fixes #7787] Replace layer_thumbnail method with new API v2 endpoint #7791
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/urls.py
  geonode/layers/views.py
  geonode/static/geonode/js/utils/thumbnail.js
  geonode/thumbs/tests/test_integration.py
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#7810 [Fixes #7809][3.2.x] DEFAULT_MAP_CENTER_X/Y not properly parsed
  geonode/settings.py
Labels: cla-signed

#7811 [Backport to 3.2.x][Fixes #7735] Change _HierarchicalTagManager add()…
  .circleci/config.yml
  geonode/base/models.py
  geonode/layers/tests.py
  geonode/settings.py
Labels: cla-signed

#7808 [Fixes #7735] Editing layer metadata in admin interface throws an error
  .circleci/config.yml
  CHANGELOG.md
  geonode/base/models.py
  geonode/groups/tests.py
  geonode/layers/api/views.py
  geonode/layers/tests.py
  geonode/settings.py
  geonode/utils.py
  geonode/views.py
Labels: backport 3.2.x

#7814 [Fixes #7807] Refactoring of Themes model and cleanup of legacy template
  geonode/base/models.py
  geonode/templates/base.html
  geonode/templates/index.html
  geonode/themes/admin.py
  geonode/themes/context_processors.py
  geonode/themes/migrations/0012_auto_20210716_1102.py
  geonode/themes/models.py
Labels: cla-signed, targets master

#7816 [Fixes #7813] X_FRAME_OPTIONS="ALLOW-FROM ALL" is not valid
  .env
  .env_dev
  .env_local
  .env_test
Labels: backport 3.2.x, backport 3.3.x, cla-signed

#7758 [Fixes #7762] Add keyword to harvested resources
  geonode/harvesting/harvesters/base.py
Labels: cla-signed

#7840 [FIXES #7830] Introducing a "ResourceBase.sourcetype" indicating the dataset source: LOCAL, REMOTE, COPYREMOTE
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/enumerations.py
  geonode/base/migrations/0069_resourcebase_sourcetype.py
  geonode/base/migrations/0070_auto_20210720_1709.py
  geonode/base/models.py
  geonode/geoserver/helpers.py
  geonode/layers/migrations/0037_layer_ptype.py
  geonode/layers/models.py
  geonode/layers/tests.py
  geonode/maps/models.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/tests.py
  geonode/themes/migrations/0013_delete_partner.py
Labels: cla-signed

#7861 [Fixes #7860] Replace layer_thumbnail method for maps
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/templates/datasets/dataset_detail.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/urls.py
  geonode/maps/views.py
  geonode/thumbs/tests/test_integration.py
Labels: backport 3.2.x, backport 3.3.x, cla-signed

#7859 [Fixes #7857] Separate upload execution from client actions and polling
  geonode/base/admin.py
  geonode/documents/admin.py
  geonode/geoapps/admin.py
  geonode/geoserver/manager.py
  geonode/layers/admin.py
  geonode/maps/admin.py
  geonode/monitoring/__init__.py
  geonode/resource/manager.py
  geonode/services/apps.py
  geonode/services/tests.py
  geonode/settings.py
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/cropper.css
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/cropper.js
  geonode/static/lib/js/openlayers-plugins.min.js
  geonode/static/lib/js/tinymce.min.js
  geonode/upload/__init__.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/tests/test_upload_preprocessing.py
  geonode/upload/views.py
  pavement.py
Labels: backport 3.2.x, backport 3.3.x, cla-signed

#7755 [Fixes #7764] Implement GeoApp for Dashboards
  geonode/base/api/views.py
  geonode/geoapps/api/serializers.py
  geonode/geoapps/migrations/0005_auto_20210705_1121.py
  geonode/geoapps/models.py
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoapps/views.py
  geonode/settings.py
Labels: cla-signed

#7843 Allow copying remote documents to local GeoNode when performing harvesting
  geonode/harvesting/admin.py
  geonode/harvesting/config.py
  geonode/harvesting/harvesters/base.py
  geonode/harvesting/harvesters/geonode.py
  geonode/harvesting/tasks.py
Labels: cla-signed

#7760 [Fixes #7761] Harvested resource permissions assignment must follow the same logic as uploaded resources
  geonode/harvesting/api/serializers.py
  geonode/harvesting/harvesters/base.py
  geonode/harvesting/migrations/0022_alter_harvester_default_access_permissions.py
  geonode/harvesting/migrations/0027_remove_harvester_default_access_permissions.py
  geonode/harvesting/models.py
Labels: cla-signed

#7867 [Backport to 3.3.x][Fixes #7857] Separate upload execution from client actions and polling
  .circleci/config.yml
  .env
  .env_test
  CHANGELOG.md
  entrypoint.sh
  geonode/api/tests.py
  geonode/base/enumerations.py
  geonode/base/forms.py
  geonode/base/models.py
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/layers/api/views.py
  geonode/layers/tests.py
  geonode/monitoring/__init__.py
  geonode/services/apps.py
  geonode/settings.py
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/lib/js/openlayers-plugins.min.js
  geonode/upload/__init__.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/tests/test_upload_preprocessing.py
  geonode/upload/upload.py
  geonode/upload/views.py
  pavement.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#7868 [Backport to 3.2.x][Fixes #7857] Separate upload execution from client actions and polling
  .circleci/config.yml
  .env
  .env_test
  CHANGELOG.md
  entrypoint.sh
  geonode/api/tests.py
  geonode/base/enumerations.py
  geonode/base/forms.py
  geonode/base/models.py
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/layers/api/views.py
  geonode/layers/tests.py
  geonode/monitoring/__init__.py
  geonode/services/apps.py
  geonode/settings.py
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/leaflet-plugins.min.js
  geonode/static/lib/js/openlayers-plugins.min.js
  geonode/upload/__init__.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/tests/test_upload_preprocessing.py
  geonode/upload/upload.py
  geonode/upload/views.py
  pavement.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#7866 [Backport][Fixes #7860 ]Replace layer_thumbnail into 3.3.x
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/urls.py
  geonode/maps/views.py
  geonode/thumbs/tests/test_integration.py
Labels: cla-signed

#7865 [Backport][Fixes #7860 ]Replace layer_thumbnail into 3.2.x
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_detail.html
  geonode/maps/urls.py
  geonode/maps/views.py
  geonode/thumbs/tests/test_integration.py
Labels: cla-signed

#7839 [Fixes #7838] Make get_download_response manage remote documents
  geonode/documents/models.py
  geonode/documents/tests.py
Labels: cla-signed

#7874 [Fixes #7873] Fix geoapp migration
  geonode/geoapps/migrations/0006_geoapp_blob_migration.py
Labels: cla-signed

#7875 [Fixes #7872] Fix migrations from GNIP 89 which loose references to the original files for datasets and documents
  geonode/base/models.py
  geonode/documents/migrations/0032_remove_document_doc_file.py
  geonode/upload/migrations/0031_auto_20210527_1520.py
  geonode/upload/migrations/0032_auto_20210528_1556.py
  geonode/upload/migrations/0033_auto_20210531_1252.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#7879 [Backport 3.3.x][Fixes #7764] Implement GeoApp for Dashboards
  geonode/context_processors.py
  geonode/layers/tests.py
  geonode/settings.py
  geonode/utils.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#7886 Improve harvester error handling
  geonode/harvesting/harvesters/base.py
  geonode/harvesting/harvesters/geonode.py
  geonode/harvesting/tasks.py
Labels: cla-signed

#7890 Harvest metadata from resources coming from WMS harvester
  geonode/harvesting/harvesters/geonode.py
  geonode/harvesting/harvesters/wms.py
  geonode/harvesting/utils.py
Labels: cla-signed

#7856 Custom harvestable resource deletion
  geonode/harvesting/harvesters/base.py
  geonode/harvesting/models.py
Labels: cla-signed

#7892 [Fixes #7887] Duplicate row in upload UI with async flow active
  geonode/static/geonode/js/upload/upload.js
Labels: backport 3.2.x, backport 3.3.x, cla-signed
