Repository GeoNode/geonode, pull requests merged in 2021-08, with the labels that each got.

#7897 [Fixes #7896] Thumbnail creation fix and celery update
  celery_dev.sh
  geonode/base/models.py
  requirements.txt
Labels: cla-signed

#7899 [Backport to 3.2.x][Fixes #7895] File upload fails with 400 Bad Request
  celery-cmd
  celery.sh
  celery_dev.sh
  pavement.py
  requirements.txt
  scripts/spcgeonode/docker-compose.override.yml
  scripts/spcgeonode/docker-compose.yml
  setup.cfg
Labels: cla-signed

#7898 [Backport to 3.2.x][Fixes #7895] File upload fails with 400 Bad Request
  celery-cmd
  celery.sh
  celery_dev.sh
  pavement.py
  requirements.txt
  scripts/spcgeonode/docker-compose.override.yml
  scripts/spcgeonode/docker-compose.yml
  setup.cfg
Labels: cla-signed

#7912 [Fixes #7911] Map payload is not correclty handled
  geonode/maps/migrations/0033_convert_map_blob.py
Labels: cla-signed

#7806 [Fixes #7739] An empty map cannot be saved
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#7916 [Backport to 3.3.x][Fixes #7739] An empty map cannot be saved (#7806)
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#7917 [Backport to 3.2.x][Fixes #7739] An empty map cannot be saved (#7806)
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#7846 [Fixes #7835][Backport 3.2.x] The first time a map is saved thumbnail is created using the default style instead of the selected one
  geonode/layers/tests.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#7918 [Fixes #7914] save correct resource_type on metadata for geoapps
  geonode/geoapps/views.py
Labels: cla-signed

#7922 [Fixes #7921] Rename reference to MapstoreClient
  geonode/base/api/views.py
Labels: cla-signed

#7844 [Fixes #7835] The first time a map is saved thumbnail is created using the default style instead of the selected one
  geonode/thumbs/tests/fixtures/map_dataset.json
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#7924 [Fixes #7923] Implement Test Cases for the Resource Manager
  geonode/resource/manager.py
  geonode/resource/tests.py
Labels: cla-signed

#7855 [Fixes #7854] Trasnform detail_url to a property and return URL depending on the client
  geonode/base/migrations/0072_remove_resourcebase_detail_url.py
  geonode/base/models.py
  geonode/documents/models.py
  geonode/geoapps/migrations/0003_update_detail_url.py
  geonode/geoapps/models.py
  geonode/groups/tests.py
  geonode/layers/models.py
  geonode/maps/models.py
  geonode/resource/utils.py
  geonode/thumbs/tests/fixtures/resource_base.json
Labels: cla-signed

#7932 [Fixes #7931] Trying to set GeoLimits does not disable GWC cache
  geonode/geoserver/manager.py
  geonode/geoserver/security.py
  geonode/security/tests.py
Labels: cla-signed

#7973 [Fixes #7972] Query filters are not working on some api v2 endpoints
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#7975 [Fixes #7974] Thumbnails not created when uploading a new dataset
  geonode/base/models.py
Labels: cla-signed

#7961 [Backport 3.2.x][Fixes #7959] Unable to set permission using django admin
  geonode/base/templates/base/batch_permissions.html
  geonode/security/utils.py
Labels: cla-signed

#7960 [Fixes #7959] Unable to set permission using django admin
  geonode/base/templates/base/batch_permissions.html
Labels: cla-signed

#7881 [Fixes #7881] Add filtering for start_date, end_date, categories and keywords for geonode harvester
  geonode/harvesting/harvesters/geonode.py
Labels: cla-signed

#7889 [Fixes #7888] Show number of remote resources
  geonode/harvesting/admin.py
  geonode/harvesting/migrations/0028_harvester_num_harvestable_resources.py
  geonode/harvesting/models.py
  geonode/harvesting/tasks.py
Labels: cla-signed

#7942 [Fixes #7941] Fix index error
  geonode/harvesting/harvesters/wms.py
Labels: cla-signed

#7944 [Fixes #7943] Update WMS healthcheck
  geonode/harvesting/harvesters/wms.py
Labels: cla-signed

#7978 [Fixes #7958] OSM refuses to return tiles while generating thumbnails
  geonode/utils.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#7983 [Fixes #404] Add button to legacy template to switch to Advanced metadata
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
Labels: cla-signed

#7979 [Fixes #7970] The form account/login is redirecting automatically to account/signup
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#7981 [Backport 3.3.x][Fixes #7970] The form account/login is redirecting automatically to account/signup
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: cla-signed

#7980 [Backport 3.2.x][Fixes #7970] The form account/login is redirecting automatically to account/signup
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: cla-signed

#7993 [Backport to 3.3.x][Fixes #7957] RuntimeError not handled in sync_geo…
  geonode/geoserver/management/commands/sync_geonode_layers.py
  geonode/geoserver/management/commands/sync_geonode_maps.py
Labels: cla-signed, backport 3.2.x

#8000 [3.2.x][Fixes #7999] Set bulk permissions from resources list pages
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templates/layers/layer_list_default.html
  geonode/security/tests.py
  geonode/security/views.py
  geonode/static/geonode/js/search/cart.js
  geonode/templates/_bulk_permissions_form.html
  geonode/templates/_update_permissions_modal.html
  geonode/templates/search/_search_content.html
Labels: cla-signed

#8019 [Fixes #8018] FeatureInfoTemplate from REST API v2 not properly working
  geonode/layers/api/serializers.py
  geonode/layers/api/tests.py
Labels: cla-signed

#8022 [Fixes #8008] Remove WMS GetCapabilities link from map detail page
  geonode/maps/templates/maps/map_detail.html
Labels: cla-signed

#8027 [Fixes #8025] Get user permission on ResourceBase model always returns the full set of perms despite the 'subtype'
  geonode/security/models.py
  geonode/security/permissions.py
  geonode/security/tests.py
Labels: cla-signed
