Repository GeoNode/geonode, pull requests merged in 2021-02, with the labels that each got.

#6881 [Fixes #6880] Circle CI upload tests fail irregulary
  .circleci/config.yml
  geonode/upload/tests/integration.py
Labels: cla-signed

#6915 [Fixes #6914] Remove "add to basket" tool for documents and maps
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/templates/search/_search_content.html
Labels: backport 3.x, cla-signed

#6911 [Fixes #6910] meaningful filename for document download
  geonode/documents/views.py
Labels: backport 3.x, cla-signed

#6913 [Fixes #6916] gsimporter.api.NotFound caused by missing trailing slash at the end of GEOSERVER_LOCATION
  geonode/settings.py
  geonode/tests/smoke.py
Labels: cla-signed

#6923 [Fixes #6922][REST API v2] Expose the curated thumbnail URL if it has…
  .circleci/config.yml
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
Labels: cla-signed

#6930 [Fixes #6929] Do not overwrite existing thumbnails if the image is b…
  geonode/base/models.py
  geonode/base/tests.py
  geonode/base/thumb_utils.py
  geonode/documents/renderers.py
  geonode/geoserver/helpers.py
  geonode/geoserver/signals.py
  geonode/geoserver/tasks.py
  geonode/proxy/views.py
  geonode/utils.py
Labels: cla-signed

#6939 [Fixes #6938] Basic auth middleware
  geonode/base/auth.py
  geonode/security/middleware.py
  geonode/security/tests.py
Labels: backport 3.x

#6839 [Issue #6843] Remove six library
  geonode/base/forms.py
  geonode/base/management/commands/helpers.py
  geonode/base/populate_test_data.py
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/utils/utils.py
  geonode/client/hooks.py
  geonode/client/hooksets.py
  geonode/geoapps/api/serializers.py
  geonode/geoserver/helpers.py
  geonode/geoserver/tasks.py
  geonode/groups/templatetags/groups_tags.py
  geonode/groups/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/monitoring/__init__.py
  geonode/monitoring/collector.py
  geonode/monitoring/fields.py
  geonode/monitoring/management/commands/render_metrics.py
  geonode/monitoring/middleware.py
  geonode/monitoring/models.py
  geonode/monitoring/widgets.py
  geonode/people/management/commands/setupsociallogins.py
  geonode/people/utils.py
  geonode/proxy/views.py
  geonode/security/utils.py
  geonode/services/serviceprocessors/base.py
  geonode/social/tests.py
  geonode/upload/tests/integration.py
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/upload/views.py
  geonode/utils.py
  requirements.txt
  scripts/cloud/demo_site.py
  setup.cfg
Labels: cla-signed

#6943 [Issue #6942] Defer and preload assets to improve page loading times
  geonode/catalogue/templates/geonode_metadata_full.html
  geonode/templates/500.html
  geonode/templates/base.html
Labels: cla-signed

#6849 [Issue #6843] Replace use of python_image_resize with Pillow image.resize
  geonode/base/models.py
  geonode/geoserver/helpers.py
  requirements.txt
  setup.cfg
Labels: backport 3.x, cla-signed

#6846 [Issue #6843] Simplify long conditionals
  geonode/api/authorization.py
  geonode/base/models.py
  geonode/geoserver/createlayer/tests.py
Labels: backport 3.x, cla-signed

#6848 [Issue #6843] Split get/post/put handling
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/security/views.py
  geonode/services/views.py
Labels: backport 3.x, cla-signed

#6958 [Fixes #6957] Duplicated registered attributes in GeoNode - and Update sttributes can't fix it
  .circleci/config.yml
  geonode/geoserver/helpers.py
  geonode/messaging/notifications.py
  geonode/notifications_helper.py
  geonode/tests/test_message_notifications.py
  geonode/tests/test_search.py
  geonode/tests/test_utils.py
  geonode/tests/utils.py
Labels: cla-signed

#6956 [Fixes #6955][REST API v2] Expose 'embed urls' of the concrete resources
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/models.py
  geonode/documents/api/tests.py
  geonode/geoapps/api/tests.py
  geonode/geoapps/models.py
  geonode/layers/api/tests.py
  geonode/layers/models.py
  geonode/maps/api/tests.py
  geonode/maps/models.py
Labels: cla-signed

#6961 [Fixes #6960] Remove the "published" filter from CSW catalogue
  geonode/catalogue/backends/pycsw_local.py
  geonode/tests/csw.py
Labels: cla-signed

#6964 [Fixes #6963] Removal of GeoNetwork support
  geonode/catalogue/backends/generic.py
  geonode/catalogue/backends/geonetwork.py
  geonode/catalogue/templates/catalogue/transaction_update_gn.xml
  geonode/local_settings.py.geoserver.sample
  geonode/settings.py
  geonode/tests/csw.py
  geonode/tests/integration.py
  geonode/tests/smoke.py
  package/README
  package/support/geonode.local_settings
Labels: cla-signed

#6978 [Fixes #6977] Images inside resource abstract are not rendered correc…
  geonode/base/templates/base/_resourcebase_info_panel.html
  geonode/base/templates/base/_resourcebase_snippet.html
  geonode/templates/metadata_detail.html
Labels: backport 3.x, cla-signed

#6976 [Fixes #6975] GeoNode client catalogue must use the abstract stripped…
  geonode/catalogue/backends/pycsw_local_mappings.py
  geonode/catalogue/tests.py
Labels: backport 3.x, cla-signed

#6980 [Fixes #6979] Add resource raw metadata properties to the API v2 resp…
  geonode/base/api/serializers.py
  geonode/base/models.py
  geonode/base/tests.py
  geonode/geoserver/helpers.py
  geonode/layers/api/tests.py
Labels: cla-signed

#6986 [Fixes #6985] Remote service shows error messages in place of resourc…
  geonode/services/signals.py
  geonode/services/tasks.py
  geonode/services/views.py
Labels: backport 3.x, cla-signed

#6988 [Fixes #6984] ISO category translation not shown (german)
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
Labels: cla-signed

#6992 [Fixes #6991] User info endpoint returns 403 (forbidden) to authetica…
  geonode/base/api/permissions.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#6987 [Fixes #6925] Thesauri improvements
  geonode/base/fields.py
  geonode/base/fixtures/test_thesaurus.json
  geonode/base/forms.py
  geonode/base/templatetags/thesaurus.py
  geonode/base/tests.py
  geonode/base/views.py
  geonode/catalogue/templates/catalogue/full_metadata.xml
  geonode/templates/search/_t_keywords_filter.html
Labels: cla-signed

#6990 [Issue #6925] Thesaurus admin pages
  geonode/base/admin.py
  geonode/base/models.py
  geonode/layers/admin.py
Labels: cla-signed

#6997 [Fixes #6994] raw fields do not encode special chars correctly
  geonode/base/models.py
  geonode/base/tests.py
  geonode/layers/api/tests.py
Labels: backport 3.x, cla-signed

#6998 Assorted minor performance issues
  geonode/base/models.py
  geonode/base/thumb_utils.py
  geonode/geoserver/tasks.py
  geonode/layers/forms.py
  geonode/layers/utils.py
  geonode/proxy/views.py
  geonode/upload/utils.py
  geonode/upload/views.py
  geonode/utils.py
Labels: backport 3.x, cla-signed, minor, performance
