Repository GeoNode/geonode, pull requests merged in 2021-06, with the labels that each got.

#7624 [Fixes #7623] Set CSW default tile size 512px
  geonode/settings.py
Labels: backport 3.2.x, cla-signed

#7620 [Fixes: GeoNode#7618] Very slow upload on large instance
  geonode/utils.py
Labels: backport 3.2.x, cla-signed

#7626 [Backport to 3.2.x][Fixes: GeoNode#7618] Very slow upload on large instance (#7620)
  geonode/utils.py
Labels: cla-signed

#7621 [Resolves #7619] Align geostory and fix issue with the thesauri
  geonode/geoapps/forms.py
  geonode/geoapps/templates/apps/app_metadata.html
  geonode/geoapps/templates/apps/app_metadata_advanced.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoapps/views.py
Labels: backport 3.2.x, cla-signed

#7622 [Backport to 3.2.x][Resolves #7619] Align geostory and fix issue with the thesauri
  geonode/geoapps/forms.py
  geonode/geoapps/templates/apps/app_metadata.html
  geonode/geoapps/templates/apps/app_metadata_advanced.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoapps/views.py
Labels: cla-signed

#7627 [Fixes #7628] Add favorite filter in Resource api/v2 enpoint
  geonode/base/api/filters.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: backport 3.2.x, cla-signed

#7630 [Backport to 3.2.x][Fixes #7628] Add favorite filter in Resource api/v2 enpoint (#7627)
  geonode/base/api/filters.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#7642 [Fixes #7638] thumbnail widget inside the metadata wizard is broken
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
Labels: cla-signed

#7643 [Backport][Fixes #7638] thumbnail widget inside the metadata wizard is broken
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
Labels: cla-signed

#7646 [Backport][Fixes #7644] Api - filter favorite in /resources endpoint doesn't return all favorites item
  geonode/base/api/serializers.py
  geonode/favorite/models.py
  geonode/favorite/tests.py
Labels: cla-signed

#7645 [Fixes #7644] Api - filter favorite in /resources endpoint doesn't return all favorites item
  geonode/base/api/serializers.py
  geonode/favorite/models.py
  geonode/favorite/tests.py
Labels: backport 3.2.x, cla-signed

#7648 Portuguese BR Translation Update
  geonode/locale/pt_BR/LC_MESSAGES/django.mo
  geonode/locale/pt_BR/LC_MESSAGES/django.po
Labels: backport 3.2.x, cla-signed, translations

#7658 Revert "Bump sqlalchemy from 1.4.15 to 1.4.18"
  requirements.txt
Labels: cla-signed

#7659 Revert "[Backport 3.2.x] Bump sqlalchemy from 1.4.15 to 1.4.18"
  requirements.txt
Labels: cla-signed

#7661 Revert "Revert "Bump sqlalchemy from 1.4.15 to 1.4.18""
  requirements.txt
Labels: cla-signed

#7662 Revert "Revert "[Backport 3.2.x] Bump sqlalchemy from 1.4.15 to 1.4.18""
  requirements.txt
Labels: cla-signed

#7673 Remove jsonfield third-party dependencies
  geonode/geoapps/migrations/0001_initial.py
  geonode/geoapps/models.py
  geonode/monitoring/migrations/0001_monitoring_init.py
  geonode/monitoring/migrations/0008_monitoring_notifications_check.py
  geonode/monitoring/migrations/0019_notification_check_def_link.py
  geonode/monitoring/models.py
  package/debian/control
  requirements.txt
  setup.cfg
Labels: cla-signed

#7677 [Fixes #7676] Search by thesauri items fails
  geonode/base/views.py
Labels: backport 3.2.x, cla-signed

#7678 [Backport][Fixes #7676] Search by thesauri items fails
  geonode/base/views.py
Labels: cla-signed

#7680 [Fixes #7679] Abstract not truncated in resource list
  geonode/base/templates/base/_resourcebase_snippet.html
Labels: backport 3.2.x, cla-signed

#7681 [Backport][Fixes #7679] Abstract not truncated in resource list
  geonode/base/templates/base/_resourcebase_snippet.html
Labels: cla-signed

#7687 [Fixes #7675] Problem creating thumbnail
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
Labels: backport 3.2.x, cla-signed

#7691 [Fixes #7692] Layers caching problem
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: backport 3.2.x, cla-signed

#7695 [Backport 3.2.x][Fixes #7692] Layers caching problem
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#7697 [Fixes #7696] Wrong authorization for WMS service
  geonode/thumbs/utils.py
Labels: backport 3.2.x, cla-signed

#7705 [Fixes #7704] Geostories raise an error on save
  geonode/geoapps/views.py
Labels: cla-signed

#7701 [Fixes #7699] Automation to fix gridsets configurations for existing layers
  geonode/geoserver/management/commands/set_default_gridsets.py
Labels: backport 3.2.x, cla-signed

#7702 [Fixes #7693] UUID error when uploading layer metadata
  geonode/base/fixtures/test_sld.sld
  geonode/base/populate_test_data.py
  geonode/layers/metadata.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/upload/upload.py
Labels: backport 3.2.x, cla-signed

#7707 [Fixes #7706] Layers response is missing properties needed for the Ma…
  geonode/api/resourcebase_api.py
  geonode/base/api/serializers.py
Labels: cla-signed

#7721 [Fixes #7700] Wrong number formatting caused by i18n breaks metadata wizard widget
  geonode/client/templates/ol/maps/map_ol2.html
  geonode/client/templates/ol/maps/map_ol3.html
Labels: backport 3.2.x, cla-signed

#7720 [Fixes #7717] Temporary files created under static root are never rem…
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/upload.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/proxy/views.py
  geonode/tests/test_utils.py
  geonode/upload/tests/__init__.py
  geonode/utils.py
Labels: backport 3.2.x, cla-signed
