Repository GeoNode/geonode, pull requests merged in 2021-05, with the labels that each got.

#7457 [Fixes #7456] Update of a GeoApp metadata returns a JSON message instead of redirecting to the GeoApp page
  geonode/geoapps/views.py
Labels: cla-signed

#7458 [Backport to 3.2.x][Fixes #7456]Update of a GeoApp metadata returns a JSON message instead of redirecting to the GeoApp page
  geonode/geoapps/views.py
Labels: cla-signed

#7438 [Fixes #7428] Port Celery optimizations from geonode-project
  .env
  Dockerfile
  celery-cmd
  docker-compose-test.yml
  docker-compose.yml
Labels: backport 3.2.x, cla-signed

#7443 [Fixes #7442] Missing information for remote layers
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/tests.py
Labels: backport 3.2.x, cla-signed

#7466 [Backport to 3.2.x][Fixes #7442] Missing information for remote layers (#7443)
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/tests.py
Labels: cla-signed

#7445 [Fixes #7444] Refactor how resource permissions are set inside the mapstore client context
  geonode/documents/views.py
  geonode/geoapps/views.py
  geonode/layers/views.py
  geonode/maps/tests.py
  geonode/maps/views.py
Labels: backport 3.2.x, cla-signed

#7471 [Backport to 3.2.x][Fixes #7444] Refactor how resource permissions are set inside the mapstore client context
  geonode/documents/views.py
  geonode/geoapps/views.py
  geonode/layers/views.py
  geonode/maps/tests.py
  geonode/maps/views.py
Labels: cla-signed

#7472 Bump Django from 2.2.16 to 2.2.20
  requirements.txt
  setup.cfg
Labels: backport 3.2.x, cla-signed, dependencies

#7364 [Fixes #7355] Introduce the adoption of groups to define users permissions, and define add_resource permission for users
  geonode/base/api/tests.py
  geonode/base/fixtures/group_test_data.json
  geonode/base/populate_test_data.py
  geonode/documents/views.py
  geonode/geoapps/views.py
  geonode/groups/admin.py
  geonode/groups/models.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/people/admin.py
  geonode/people/migrations/0032_set_contributors_group.py
  geonode/people/models.py
  geonode/people/signals.py
  geonode/security/models.py
  geonode/security/permissions.py
  geonode/security/utils.py
  geonode/tests/test_rest_api.py
Labels: backport 3.2.x, cla-signed

#7451 [Backport 3.2.x][Fixes #7355] Introduce the adoption of groups to define users permissions, and define add_resource permission for users
  geonode/base/api/tests.py
  geonode/base/fixtures/group_test_data.json
  geonode/base/populate_test_data.py
  geonode/documents/views.py
  geonode/geoapps/views.py
  geonode/groups/admin.py
  geonode/groups/models.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/people/admin.py
  geonode/people/migrations/0032_set_contributors_group.py
  geonode/people/models.py
  geonode/people/signals.py
  geonode/security/models.py
  geonode/security/permissions.py
  geonode/security/utils.py
  geonode/tests/test_rest_api.py
Labels: cla-signed

#7439 [Fixes #7435] Include UUID handling in set_all_layer_metadata
  geonode/base/management/commands/set_all_layers_metadata.py
Labels: backport 3.2.x, cla-signed

#7468 [Backport Fixes #7435] Include UUID handling in set_all_layer_metadata
  geonode/base/management/commands/set_all_layers_metadata.py
Labels: cla-signed

#7452 [Fixes #7440] Migration for setting resource_type
  geonode/base/migrations/0059_fill_empty_resource_type.py
Labels: backport 3.2.x, cla-signed

#7455 [Backport Fixes #7440] Migration for setting resource_type
  geonode/base/migrations/0059_fill_empty_resource_type.py
Labels: cla-signed

#7453 [Resolves #7441] Handle configuration for CSW pre-filtering
  .circleci/config.yml
  geonode/base/populate_test_data.py
  geonode/catalogue/backends/pycsw_plugin.py
  geonode/catalogue/backends/tests.py
Labels: backport 3.2.x, cla-signed

#7454 [Backport Resolves #7441] Handle configuration for CSW pre-filtering
  .circleci/config.yml
  geonode/base/populate_test_data.py
  geonode/catalogue/backends/pycsw_plugin.py
  geonode/catalogue/backends/tests.py
Labels: cla-signed

#7474 [Fixes #7429] Null references in thesauri items
  geonode/api/tests.py
  geonode/base/fixtures/test_thesaurus.json
  geonode/base/models.py
  geonode/base/tests.py
Labels: backport 3.2.x, cla-signed

#7475 [Backport][Fixes #7429] Null references in thesauri items
  geonode/api/tests.py
  geonode/base/fixtures/test_thesaurus.json
  geonode/base/models.py
  geonode/base/tests.py
Labels: cla-signed

#7478 [Fixes #7477] Sorting dropdown is blank for Group Categories
  geonode/api/api.py
  geonode/templates/search/_sort_filters.html
Labels: backport 3.2.x, cla-signed

#7479 [Backport][Fixes #7477] Sorting dropdown is blank for Group Categories
  geonode/api/api.py
  geonode/templates/search/_sort_filters.html
Labels: cla-signed

#7469 [Fixes #7467] API returns some URLs as relative, others as absolute
  geonode/base/api/serializers.py
  geonode/base/utils.py
Labels: backport 3.2.x, cla-signed

#7470 [Backport 3.2.x][Fixes #7467] API returns some URLs as relative, others as absolute
  geonode/base/api/serializers.py
  geonode/base/utils.py
Labels: cla-signed

#7481 [Fixes #7480] Allow to exclude fields from the "Profile Edit" page
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/context_processors.py
  geonode/layers/tests.py
  geonode/people/templates/people/profile_edit.html
  geonode/settings.py
  requirements.txt
  setup.cfg
Labels: backport 3.2.x, cla-signed

#7483 [Fixes #7482] Implement API v2 endpoints to complete the support for filtering
  geonode/base/api/permissions.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/urls.py
  geonode/base/api/views.py
  geonode/base/utils.py
Labels: backport 3.2.x, cla-signed

#7487 [Backport to 3.2.x][Fixes #7482] Implement API v2 endpoints to complete the support for…
  geonode/base/api/permissions.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/urls.py
  geonode/base/api/views.py
  geonode/base/utils.py
Labels: cla-signed

#7491 [Fixes #7490] Keyword with "&" not correclty handled in resource preview
  geonode/base/templates/base/_resourcebase_info_panel.html
  geonode/templates/metadata_detail.html
Labels: backport 3.2.x, cla-signed

#7496 [Backport to 3.2.x][Fixes #7490] Keyword with "&" not correclty handled in resource prev…
  geonode/base/templates/base/_resourcebase_info_panel.html
  geonode/templates/metadata_detail.html
Labels: cla-signed

#7497 [Backport to 3.2.x][Fixes #7492] Add a modal loading mask while performing an update ope…
  geonode/static/geonode/css/base.css
  geonode/static/geonode/js/messages/message_recipients_autocomplete_es5.js
  geonode/static/geonode/less/base.less
  geonode/static/lib/css/assets.min.css
  geonode/static/lib/css/bootstrap-table.css
  geonode/static/lib/css/tagify.css
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/bootstrap-table.js
  geonode/static/lib/js/clipboard.js
  geonode/static/lib/js/clipboard.min.js
  geonode/static/lib/js/openlayers-plugins.min.js
  geonode/static/lib/js/tagify.min.js
  geonode/static/lib/js/text.js
  geonode/static/lib/js/tinymce.min.js
  geonode/static/lib/js/underscore.js
  geonode/templates/_permissions_form_js.html
  geonode/templates/base.html
Labels: cla-signed

#7495 [Fixes #7494] "set permissions" operations should be done inside an atomic transaction
  geonode/security/models.py
Labels: backport 3.2.x, cla-signed

#7485 [Fixes #7484] API v2 resource_types endpoint must return the count property
  geonode/base/api/permissions.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/utils.py
  geonode/security/utils.py
Labels: backport 3.2.x, cla-signed

#7506 [Backport to 3.2.x][Fixes #7484] API v2 resource_types endpoint must return the count p…
  geonode/base/api/permissions.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/utils.py
  geonode/security/utils.py
Labels: cla-signed

#7509 Bump geonode-oauth-toolkit to version 2.2.0
  geonode/settings.py
  geonode/urls.py
  requirements.txt
  setup.cfg
Labels: backport 3.2.x, cla-signed, dependencies

#7511 [Fixes #7510] SLD body returned by GeoNode API is malformed
  geonode/layers/api/serializers.py
Labels: backport 3.2.x, cla-signed

#7508 [Fixes #7507] Owners API V2 Returns users with no resources
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: backport 3.2.x, cla-signed

#7514 [Backport to 3.2.x] Bump geonode-oauth-toolkit to version 2.2.0 (#7509)
  geonode/settings.py
  geonode/urls.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#7476 [Fixes #7465] Fix some italian translations
  geonode/geoserver/createlayer/forms.py
  geonode/geoserver/createlayer/templates/createlayer/layer_create.html
  geonode/locale/af/LC_MESSAGES/django.po
  geonode/locale/al/LC_MESSAGES/django.po
  geonode/locale/am/LC_MESSAGES/django.po
  geonode/locale/ar/LC_MESSAGES/django.po
  geonode/locale/bg_BG/LC_MESSAGES/django.po
  geonode/locale/bn/LC_MESSAGES/django.po
  geonode/locale/de/LC_MESSAGES/django.po
  geonode/locale/el/LC_MESSAGES/django.po
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/fa/LC_MESSAGES/django.po
  geonode/locale/fa_IR/LC_MESSAGES/django.po
  geonode/locale/fi/LC_MESSAGES/django.po
  geonode/locale/fil/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/hu/LC_MESSAGES/django.po
  geonode/locale/id/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/locale/ja/LC_MESSAGES/django.po
  geonode/locale/ka/LC_MESSAGES/django.po
  geonode/locale/km/LC_MESSAGES/django.po
  geonode/locale/ko/LC_MESSAGES/django.po
  geonode/locale/lt/LC_MESSAGES/django.po
  geonode/locale/ne/LC_MESSAGES/django.po
  geonode/locale/nl_NL/LC_MESSAGES/django.po
  geonode/locale/no/LC_MESSAGES/django.po
  geonode/locale/pl/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/locale/ro/LC_MESSAGES/django.po
  geonode/locale/ru/LC_MESSAGES/django.po
  geonode/locale/si/LC_MESSAGES/django.po
  geonode/locale/sk/LC_MESSAGES/django.po
  geonode/locale/sq/LC_MESSAGES/django.po
  geonode/locale/sv/LC_MESSAGES/django.po
  geonode/locale/sw/LC_MESSAGES/django.po
  geonode/locale/ta/LC_MESSAGES/django.po
  geonode/locale/th/LC_MESSAGES/django.po
  geonode/locale/tl/LC_MESSAGES/django.po
  geonode/locale/uk/LC_MESSAGES/django.po
  geonode/locale/vi/LC_MESSAGES/django.po
  geonode/locale/zh/LC_MESSAGES/django.po
Labels: backport 3.2.x, cla-signed

#7527 [Fixes #7526] Layer SLD URLs refer to the internal GeoServer address instead of the public one
  geonode/layers/api/serializers.py
Labels: backport 3.2.x, cla-signed

#7544 [Backport 3.2.x][Fixes #7526] Layer SLD URLs refer to the internal GeoServer address instead of the public one
  geonode/layers/api/serializers.py
Labels: cla-signed

#7537 [Fixes #7536] Migration to update existing services with metadata_only=True
  geonode/services/migrations/0042_update_metadata_only.py
Labels: backport 3.2.x, cla-signed

#7546 [Backport 3.2.x][Fixes #7536] Migration to update existing services with metadata_only=True
  geonode/services/migrations/0042_update_metadata_only.py
Labels: cla-signed

#7558 [Fixes #7554] Django admin Services broken
  geonode/services/migrations/0043_auto_20210519_1308.py
  geonode/services/translation.py
Labels: backport 3.2.x, cla-signed

#7563 [Fixes #7557] Permissions set during the upload are lost
  geonode/geoapps/api/tests.py
  geonode/geoserver/tasks.py
  geonode/layers/tests.py
  geonode/security/utils.py
  geonode/tests/utils.py
  geonode/upload/tests/integration.py
Labels: backport 3.2.x, cla-signed

#7564 [Backport to 3.2.x][Fixes #7557] Permissions set during the upload are lost (#7563)
  geonode/geoapps/api/tests.py
  geonode/geoserver/tasks.py
  geonode/layers/tests.py
  geonode/security/utils.py
  geonode/tests/utils.py
  geonode/upload/tests/integration.py
Labels: cla-signed

#7561 [Fixes #7560] 'OAuth2Backend' validator interferes with DRF authentic…
  geonode/settings.py
Labels: backport 3.2.x, cla-signed

#7530 [Fixes #7529] GeoNode V2 API layers, maps and resources responses do not include URLs for each resource
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/documents/api/serializers.py
  geonode/geoapps/api/serializers.py
  geonode/layers/api/serializers.py
  geonode/maps/api/serializers.py
  geonode/upload/api/serializers.py
Labels: backport 3.2.x, cla-signed

#7553 [Fixes #7562] Change bootstrap-rtl css source to cloudflare
  geonode/templates/base.html
Labels: frontend

#7566 [Backport to 3.2.x][Fixes #7529] GeoNode V2 API layers, maps and resources responses do not include URLs for each resource
  .clabot
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/documents/api/serializers.py
  geonode/geoapps/api/serializers.py
  geonode/layers/api/serializers.py
  geonode/maps/api/serializers.py
  geonode/upload/api/serializers.py
Labels: cla-signed

#7567 [Backport to 3.2.x] Change bootstrap-rtl css source to cloudflare (#7553)
  geonode/templates/base.html
Labels: cla-signed

#7533 [Fixes #7525] Remove Geoserver keywords at layer creation time
  geonode/geoserver/tasks.py
  geonode/tests/integration.py
Labels: backport 3.2.x, cla-signed

#7569 [Backport to 3.2.x] [Fixes #7525] Remove Geoserver keywords at layer creation time
  geonode/geoserver/tasks.py
  geonode/tests/integration.py
Labels: cla-signed

#7581 [Fixes #7580]: Missing sld_version parameter inside legend requests
  geonode/base/utils.py
  geonode/geoserver/helpers.py
  geonode/utils.py
Labels: backport 3.2.x, cla-signed

#7585 [Backport to 3.2.x][Fixes #7580]: Missing sld_version parameter inside legend requests
  geonode/base/utils.py
  geonode/geoserver/helpers.py
  geonode/utils.py
Labels: cla-signed

#7586 [Backport to 3.2.x][Fixes #7532] Make resource owner mandatory (#7534)
  geonode/base/api/tests.py
  geonode/base/forms.py
  geonode/base/migrations/0060_auto_20210512_1658.py
  geonode/base/models.py
  geonode/base/tests.py
  geonode/geoserver/tests/integration.py
  geonode/geoserver/tests/test_helpers.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/people/models.py
  geonode/tests/base.py
  geonode/tests/integration.py
  geonode/tests/test_utils.py
  geonode/thumbs/tests/test_integration.py
Labels: cla-signed

#7572 [ Fixes #7571]: API v2 favorites
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: backport 3.2.x, cla-signed

#7595 [Backport to 3.2.x][Fixes #7571]: API v2 favorites
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#7593 [Fixes #7587]: Legend repeated twice in preview if style names are similar
  geonode/layers/templates/layers/layer_detail.html
  geonode/layers/templatetags/layer_tags.py
Labels: backport 3.2.x, cla-signed

#7601 [Fixes #7600] Replace "Register a new Service" with "Add Remote Service"
  geonode/services/templates/services/service_list.html
Labels: backport 3.2.x, cla-signed

#7602 [Backport] [Fixes #7600] Replace "Register a new Service" with "Add Remote Service"
  geonode/services/templates/services/service_list.html
Labels: cla-signed

#7604 [Fixes #7603] RemoteServices legend urls do not contain 'sld_service' param
  geonode/services/serviceprocessors/wms.py
  geonode/services/tests.py
  geonode/utils.py
Labels: backport 3.2.x, cla-signed
