Repository GeoNode/geonode, pull requests merged in 2022-01, with the labels that each got.

#8567 [Fixes #8565] Dataset Clone does not seem to be setting the GeoFence … …rules correctly
  geonode/geoserver/manager.py
  geonode/geoserver/security.py
  geonode/resource/manager.py
  geonode/resource/tests.py
Labels: cla-signed

#8580 [Fixes #8579] Dataset Clone should put private permissions by default
  geonode/resource/manager.py
Labels: cla-signed

#8586 [Fixes #8551] raster uploads require sending the same file twice
  geonode/tests/utils.py
  geonode/upload/api/tests.py
  geonode/upload/upload_validators.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8596 [Fixes #8508] Improve GeoLimits layer tiles loading
  geonode/templates/_permissions_form.html
Labels: cla-signed

#8581 [Fixes #8561] Refactor the API for the update of the thumbnails
  geonode/api/resourcebase_api.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/utils.py
  geonode/maps/api/views.py
  geonode/maps/utils/thumbnail.py
  geonode/resource/manager.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
Labels: cla-signed

#8512 [Fixes #8346] Implement upload size limiting mechanism for datasets
  .env_test
  geonode/base/api/permissions.py
  geonode/documents/forms.py
  geonode/documents/tests.py
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/settings.py
  geonode/tests/utils.py
  geonode/upload/admin.py
  geonode/upload/api/serializers.py
  geonode/upload/api/tests.py
  geonode/upload/api/urls.py
  geonode/upload/api/views.py
  geonode/upload/forms.py
  geonode/upload/migrations/0034_uploadsizelimit.py
  geonode/upload/models.py
  geonode/upload/tests/integration.py
  geonode/upload/uploadhandler.py
Labels: cla-signed

#8626 [Backport to 3.3.x][Fixes #8610] API v2 does not return keywords belo…
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/tests/utils.py
Labels: cla-signed

#8627 [Fixes #8610] API v2 does not return keywords belonging to thesauri
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/tests/utils.py
Labels: cla-signed

#8631 [Fixes #8629] set_thumbnail response should include the URL to the updated thumbnail
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#8632 [Backport to 3.2.x][Fixes #8610] API v2 does not return keywords belo…
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/tests/utils.py
Labels: cla-signed

#8624 [Fixes #8622] Drop CuratedThumbnail and fix the metadata wizard thumbnail widget
  geonode/base/admin.py
  geonode/base/forms.py
  geonode/base/migrations/0074_drop_curated_thumbs.py
  geonode/base/migrations/0075_delete_curatedthumbnail.py
  geonode/base/models.py
  geonode/base/templates/base/thumbnail_upload.html
  geonode/base/tests.py
  geonode/base/views.py
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/layers/templates/datasets/dataset_detail.html
  geonode/static/geonode/js/crop_widget/crop_widget.js
  geonode/static/geonode/js/crop_widget/crop_widget_es5.js
  geonode/static/geonode/js/crop_widget/crop_widget_es5.js.map
  geonode/static/geonode/js/messages/message_recipients_autocomplete_es5.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/openlayers-plugins.min.js
  geonode/urls.py
Labels: cla-signed

#8639 [Fixes #8637] Thumbnail not generated on creating a map
  geonode/maps/api/tests.py
  geonode/maps/api/views.py
Labels: cla-signed

#8648 [Fixes #8647] Fix upload API
  geonode/geoserver/helpers.py
  geonode/geoserver/management/commands/importlayers.py
  geonode/upload/api/tests.py
  geonode/upload/api/views.py
  geonode/upload/utils.py
Labels: cla-signed

#8660 [Fixes #8650] Set style editor support metadata for dataset default style at creation time
  geonode/geoserver/signals.py
  geonode/geoserver/tasks.py
  geonode/geoserver/tests/test_tasks.py
Labels: cla-signed

#8652 [Fixes #8646][Upload Improvements] Get rid of STATIC MIDDLEWHARES AWS and CACHE_BUSTING in favor of WhiteNoise
  .devcontainer/.env
  geonode/settings.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#8666 [Fixes #8665] Include new languages variables and file extensions for the client
  geonode/settings.py
Labels: cla-signed

#8664 [Fixes #8663] Remove automatic download from document embed template
  geonode/documents/templates/documents/document_embed.html
  geonode/documents/views.py
Labels: cla-signed

#8683 [Fixes #8681] TemplateSyntaxError on document Advanced Metadata form
  geonode/documents/templates/documents/document_metadata_advanced.html
Labels: cla-signed

#8680 [WIP] Fix failing test
  geonode/geoserver/tests/test_tasks.py
  geonode/proxy/tests.py
Labels: cla-signed

#8686 reduce tinymce tools
  geonode/settings.py
Labels: cla-signed

#8104 [Fixes #8057] GeoStory: missing tab in recent activities
  geonode/social/apps.py
  geonode/social/signals.py
  geonode/social/templates/social/activity_list.html
  geonode/social/templatetags/social_tags.py
  geonode/social/tests.py
  geonode/social/views.py
  geonode/static/geonode/css/base.css
  geonode/static/geonode/less/base.less
Labels: cla-signed

#8682 [Fixes #8422] Added pluggable service types
  geonode/services/forms.py
  geonode/services/serviceprocessors/handler.py
  geonode/services/tasks.py
  geonode/services/tests.py
  geonode/services/utils.py
  geonode/services/views.py
Labels: cla-signed

#8688 [Fixes #8422] Added pluggable service types
  geonode/services/forms.py
  geonode/services/serviceprocessors/handler.py
  geonode/services/tests.py
  geonode/services/utils.py
Labels: cla-signed

#8692 [Fixes #8691] Geonode 3.3.x build is broken
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/security/tests.py
Labels: cla-signed, 3.3.x

#8694 [Fixes #8693] Add variable for translations path for geonode-mapstore-client
  geonode/settings.py
Labels: cla-signed

#8695 [3.3.x][Fixes #8641] Replace Layer (stable 3.2.x)
  geonode/geoserver/helpers.py
  geonode/layers/utils.py
Labels: cla-signed, 3.3.x

#8696 [Backport 3.2.x] [Fixes #8641] Replace Layer (stable 3.2.x)
  geonode/geoserver/helpers.py
  geonode/layers/utils.py
Labels: cla-signed, 3.2.x

#8684 [Backport to 3.3.x][Fixes #8499] Added GeoApp types missing to search filter
  geonode/api/resourcebase_api.py
  geonode/base/templatetags/base_tags.py
  geonode/documents/forms.py
  geonode/templates/search/_type_filters.html
Labels: cla-signed

#8697 [Backport to 3.2.x][Fixes #8499] Added GeoApp types missing to search filter
  geonode/api/resourcebase_api.py
  geonode/base/templatetags/base_tags.py
  geonode/documents/forms.py
  geonode/templates/search/_type_filters.html
Labels: cla-signed

#8699 [Fixes #8698] Document replace page is not availalable anymore
  geonode/documents/forms.py
  geonode/documents/templates/documents/document_replace.html
  geonode/documents/tests.py
  geonode/documents/urls.py
  geonode/documents/views.py
Labels: cla-signed

#8715 [Fixes #8679] Unable to update map thumbnail on metadata form
  geonode/client/templates/ol/maps/map_ol2.html
  geonode/maps/views.py
Labels: cla-signed
