Repository GeoNode/geonode, pull requests merged in 2022-09, with the labels that each got.

#9947 [#Fixes #9945] Do not show the time configuration for raster datasets
  geonode/layers/templates/layouts/panels.html
  geonode/layers/views.py
  geonode/templates/metadata_form_js.html
Labels: cla-signed, backport 4.x

#9967 [dependencies] Align "setup.cfg" to the "requirements.txt" file
  setup.cfg
Labels: dependencies, cla-signed

#9948 [#Fixes #9944] Unable to clone a resource
  geonode/base/api/permissions.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed, backport 4.x

#9975 Bump djangorestframework to version 3.12.0
  geonode/base/api/tests.py
  geonode/layers/forms.py
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9973 [#Fixes #9970] Fix users has perms
  geonode/base/api/permissions.py
  geonode/base/api/views.py
  geonode/resource/api/views.py
Labels: cla-signed, backport 4.x

#9979 [#Fixes #9970] fix tests
  geonode/documents/api/tests.py
  geonode/layers/api/tests.py
  geonode/maps/api/tests.py
Labels: cla-signed

#9974 [Fixes #9960] Unable to edit style for cloned datasets
  geonode/geoserver/helpers.py
Labels: cla-signed, backport 4.x

#9982 [Fixes #9970] User has perms return 403
  geonode/base/api/permissions.py
Labels: cla-signed, backport 4.x

#9984 [Fixes #9972] SECURITY - Outdated requirements.txt for branch 3.3.x
  .circleci/config.yml
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed

#9988 [Fixes #9987] Avoid call to delete the style if is the default one
  geonode/geoserver/helpers.py
Labels: cla-signed, backport 4.x

#9991 Deprecated branch notice
  README.md
Labels: cla-signed

#9993 Deprecated branch notice
  README.md
Labels: cla-signed

#9992 Revert "Deprecated branch notice"
  README.md
Labels: cla-signed

#9994 switched to client 4.0.x
  requirements.txt
Labels: cla-signed

#10019 [Dependencies] Align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10025 [Fixes #10024] Wrong default style when creating layer
  geonode/geoserver/helpers.py
  geonode/geoserver/tasks.py
Labels: cla-signed, backport 4.0.x

#10035 [Fixes #10024] Wrong default style when creating layer
  geonode/geoserver/helpers.py
  geonode/geoserver/tasks.py
Labels: cla-signed

#10042 add installation type to issue template
  .github/ISSUE_TEMPLATE/report_issue.md
Labels: cla-signed, backport 4.0.x

#10038 [Dependencies] Align setup.cfg with requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10045 [Fixes #10040] Remove auto-generated thumbnail for documents
  geonode/documents/migrations/0036_clean_document_thumbnails.py
  geonode/documents/models.py
  geonode/documents/tasks.py
Labels: cla-signed, backport 4.0.x

#10062 Revert "Bump djangorestframework from 3.12.0 to 3.14.0"
  requirements.txt
Labels: dependencies, cla-signed

#10061 [Dependencies] Align setup.cfg with requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10056 Complete Translate pt_BR
  geonode/locale/pt_BR/LC_MESSAGES/django.mo
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/djangojs.mo
  geonode/locale/pt_BR/LC_MESSAGES/djangojs.po
Labels: translations, cla-signed, backport 4.0.x

#10046 [Fixes #10041] Review the thumbnail scaling process
  geonode/base/models.py
  geonode/documents/renderers.py
  geonode/documents/tasks.py
  geonode/documents/tests.py
  geonode/documents/tests/data/text.txt
  geonode/settings.py
Labels: cla-signed, backport 4.0.x

#10057 [Fixes #10055] Modify Metadata form with permissions check
  geonode/base/forms.py
  geonode/geoapps/tests.py
  geonode/layers/tests.py
  geonode/maps/tests.py
Labels: cla-signed, backport 4.0.x
