Repository GeoNode/geonode, pull requests merged in 2022-04, with the labels that each got.

#9014 [Fixes #9013] Advanced Workflow: workflow logic should take precedence over standard permissions
  geonode/api/api.py
  geonode/base/models.py
  geonode/base/templatetags/user_messages.py
  geonode/documents/views.py
  geonode/geoapps/views.py
  geonode/geoserver/helpers.py
  geonode/geoserver/management/commands/importlayers.py
  geonode/geoserver/manager.py
  geonode/geoserver/security.py
  geonode/geoserver/tests/test_server.py
  geonode/groups/forms.py
  geonode/groups/models.py
  geonode/groups/tests.py
  geonode/layers/models.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/monitoring/tests/integration.py
  geonode/people/adapters.py
  geonode/people/utils.py
  geonode/resource/manager.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/services/tests.py
  geonode/storage/manager.py
  geonode/storage/tests.py
  geonode/tests/utils.py
  geonode/thumbs/thumbnails.py
  geonode/upload/tests/integration.py
  geonode/views.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9031 [Fixes #9017] Make 500.html extend geonode_base html
  geonode/templates/500.html
Labels: cla-signed, master, backport 4.x

#9032 [Backport 4.x][Fixes #9017] Make 500.html extend geonode_base html
  geonode/templates/500.html
Labels: cla-signed

#9021 [Fixes #9016] Geoserver importer NO_CRS task status doesn't trigger t…
  .env_test
  geonode/base/api/tests.py
  geonode/base/populate_test_data.py
  geonode/documents/views.py
  geonode/geoserver/helpers.py
  geonode/resource/manager.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/tests/data/san_andres_y_providencia_coastline_no_prj.zip
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
  geonode/upload/api/tests.py
  geonode/upload/models.py
  geonode/upload/views.py
  test_csw.sh
Labels: cla-signed, backport 3.3.x, backport 4.x

#9043 [Fixes #9042] Disable caching header in GeoNode proxy for the REST API
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/views.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9051 [Fixes #9042] Disable caching header in GeoNode proxy for the REST API
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/views.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9040 [Fixes #9039] Allow configuration of extensions folder path via settings.py for geonode-mapstore-client
  geonode/settings.py
Labels: cla-signed, backport 3.3.x, 3.3.x, backport 4.x, 4.0.x

#9057 [Backport 3.3.x][Fixes #9016] Geoserver importer NO_CRS task status d…
  .env_test
  geonode/settings.py
  geonode/tests/data/san_andres_y_providencia_coastline_no_prj.zip
  geonode/upload/api/tests.py
  geonode/upload/views.py
Labels: cla-signed

#9058 [Backport to 4.x][Fixes #9044] Lots of keywords disconnected from resources (#9045)
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#9059 [Fixes #9056] Layer upload via API stuck in status waiting
  geonode/upload/api/tests.py
  geonode/upload/tasks.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9060 [Backport to 3.3.x][Fixes #9056] Layer upload via API stuck in status…
  geonode/upload/api/tests.py
  geonode/upload/tasks.py
Labels: cla-signed

#9065 [Backport to 3.3.x][Fixes #9064] Improve Upload Workflow resources state management]
  geonode/base/models.py
  geonode/br/tasks.py
  geonode/documents/tasks.py
  geonode/geoserver/helpers.py
  geonode/geoserver/signals.py
  geonode/geoserver/tasks.py
  geonode/layers/tasks.py
  geonode/maps/tasks.py
  geonode/monitoring/tasks.py
  geonode/security/tasks.py
  geonode/security/utils.py
  geonode/services/tasks.py
  geonode/tasks/tasks.py
  geonode/upload/api/tests.py
  geonode/upload/migrations/0034_auto_20220408_0922.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
  pavement.py
Labels: cla-signed

#9066 [Fixes #9064] Improve Upload Workflow resources state management
  .circleci/config.yml
  geonode/br/tasks.py
  geonode/documents/tasks.py
  geonode/geoserver/helpers.py
  geonode/geoserver/tasks.py
  geonode/layers/tasks.py
  geonode/monitoring/tasks.py
  geonode/tasks/tasks.py
  geonode/upload/tasks.py
  pavement.py
Labels: cla-signed

#9069 Backport 9066 to 4.x
  .circleci/config.yml
  geonode/br/tasks.py
  geonode/documents/tasks.py
  geonode/geoserver/helpers.py
  geonode/geoserver/tasks.py
  geonode/layers/tasks.py
  geonode/monitoring/tasks.py
  geonode/tasks/tasks.py
  geonode/upload/tasks.py
  pavement.py
Labels: cla-signed

#9062 [Fixes #8905] Implement API and remote file path support for layer data replace
  geonode/layers/api/exceptions.py
  geonode/layers/api/serializers.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/models.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/upload/upload.py
  geonode/upload/views.py
Labels: cla-signed

#9081 - Regression: data_retriever tempo folder issue
  geonode/upload/views.py
Labels: cla-signed

#9083 [3.3.x] Upload Workflow Stabilization and correct state management
  geonode/geoserver/upload.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
  geonode/upload/views.py
Labels: cla-signed

#9084 Upload workflow stabilization
  geonode/api/tests.py
  geonode/base/tests.py
  geonode/geoserver/upload.py
  geonode/proxy/tests.py
  geonode/resource/manager.py
  geonode/resource/tests.py
  geonode/security/tests.py
  geonode/upload/migrations/0038_alter_upload_name.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/upload/views.py
Labels: cla-signed

#9085 [3.3.x] Upload workflow stabilization
  geonode/upload/migrations/0035_auto_20220412_1700.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
  geonode/upload/utils.py
  geonode/upload/views.py
Labels: cla-signed

#9071 [Fixes #9070] Filter by extent issue with dateline
  geonode/base/bbox_utils.py
  geonode/base/tests.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9093 [Fixes #9092] The Upload Workflow never updates the Resource files
  geonode/upload/models.py
  geonode/upload/upload.py
Labels: cla-signed, backport 4.x

#9091 [Fixes #9092] The Upload Workflow never updates the Resource files
  geonode/upload/upload.py
Labels: cla-signed

#9102 [Fixes #9098] The list of regions inside the metadata template is not updated when they're changed inside the DB
  geonode/base/forms.py
  geonode/documents/forms.py
  geonode/geoapps/forms.py
  geonode/layers/forms.py
  geonode/maps/forms.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9090 [Backport to 3.3.x][Fixes #9070] Filter by extent issue with dateline…
  geonode/base/bbox_utils.py
  geonode/base/tests.py
Labels: cla-signed

#9113 - Fix env and docker-compose variables accordingly to the updated ge…
  .env
  .env_dev
  .env_local
  .env_test
  .gitignore
  docker-compose-geoserver-server.yml
  docker-compose-test.yml
  docker-compose.yml
  scripts/docker/env/development/db.env
  scripts/docker/env/development/geoserver.env
  scripts/docker/env/production/db.env
  scripts/docker/env/production/geoserver.env
Labels: cla-signed

#9110 [Fixes #9106] Implement API for compact permissions
  geonode/base/api/tests.py
  geonode/resource/manager.py
  geonode/security/permissions.py
  geonode/security/tests.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9111 [Fixes #9101] Keywords filter only returns the root nodes of the tree
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/models.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9117 [Fixes #9116] Permissions API return 403 on users in groups with manage permission on a resource
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed, backport 4.x

#9124 [Backport to 3.3.x][Fixes #9101] Keywords filter only returns the roo…
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/models.py
Labels: cla-signed

#9137 [Fixes #9136] Async Upload deletes Importer folders cusing GeoServer to trigger the import again
  geonode/base/models.py
  geonode/geoserver/manager.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
  geonode/upload/views.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9126 [Fixes #9125] Backup/Restore list of apps into ".ini" sample must be …
  geonode/br/management/commands/settings_docker_sample.ini
  geonode/br/management/commands/settings_sample.ini
Labels: cla-signed, backport 4.x

#9140 [Backport to 3.3.x][Fixes #9136] Async Upload deletes Importer folder…
  geonode/base/models.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
  geonode/upload/views.py
Labels: cla-signed

#9122 [Fixes #9108] Unable to add category to geostories and dashboards
  geonode/geoapps/tests.py
  geonode/geoapps/views.py
Labels: cla-signed, backport 4.x

#9118 [Fixes #9114] Group managers are assigned Manage permission on adding a group with any permission in share permissions form
  geonode/groups/models.py
Labels: cla-signed, backport 4.x

#9160 [Fixes #9148] switch from wikimedia to osm for thumbnail basemap
  geonode/settings.py
Labels: cla-signed, backport 4.x

#9149 [Dependencies] Align requirements to setup.cfg
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9165 [Fixes #9163] Advanced Workflow: Demotion/Promotion/removal of managers in owner's group is not working; it works for the resource group
  geonode/security/utils.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9168 [Fixes #9166] Upload Workflow: The upload api keeps calling the "final" step causing inconsistent states
  geonode/resource/manager.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/views.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9174 [Fixes #9173] Upload Workflow: The finalize task set "INVALID" state if the final step vew returns "error" without actually checking the real Import Session state
  geonode/upload/tasks.py
  geonode/upload/upload.py
Labels: cla-signed, backport 4.x

#9167 [Backport to 3.3.x][Fixes #9115] Advanced Workflow: permissions assigned to managers/members should be filtered by owner and resource group metadata only
  geonode/documents/views.py
  geonode/geoapps/views.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/security/models.py
  geonode/security/utils.py
Labels: cla-signed

#9171 [Backport to 3.3.x][Fixes #9166] Upload Workflow: The upload api keep…
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/views.py
Labels: cla-signed

#9172 - Missing commits on : [Fixes #9115] Advanced Workflow: permissions …
  geonode/documents/views.py
  geonode/geoapps/views.py
  geonode/maps/views.py
Labels: cla-signed, backport 4.x

#9155 [Fixes #9154] Remove buttons action after style and metadata upload
  geonode/static/geonode/js/upload/LayerInfo.js
Labels: cla-signed

#9177 [Backport to 3.3.x][Fixes #9173] Upload Workflow: The finalize task set "INVALID" state if the final step vew returns "error" without actually checking the real Import Session state
  geonode/upload/tasks.py
  geonode/upload/upload.py
Labels: cla-signed

#9181 - Typo: [Backport to 3.3.x][Fixes #9173] Upload Workflow: The finali…
  geonode/upload/upload.py
Labels: cla-signed

#9178 Backport issue 9154
  geonode/static/geonode/js/upload/LayerInfo.js
  geonode/static/lib/js/angular-sanitize.min.js
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/moment-with-locales.js
  geonode/static/lib/js/openlayers-plugins.min.js
Labels: cla-signed

#9180 - Missing static files [Fixes #9154] Remove buttons action after sty…
  geonode/static/lib/js/assets.min.js
  geonode/static/lib/js/moment-with-locales.js
  geonode/static/lib/js/openlayers-plugins.min.js
Labels: cla-signed

#9185 [Fixes #9184] Let final step work in async mode for layer replace
  geonode/layers/views.py
Labels: cla-signed

#9187 [Fixes #9186] Upload marks as PROCESSED a resource not ready yet
  geonode/base/models.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9192 [Dependencies] Bump django-geonode-mapstore-client to version 4.0.0
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9191 [Backport to 3.3.x][Fixes #9186] Upload marks as PROCESSED a resource not ready yet
  geonode/base/models.py
  geonode/upload/models.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
Labels: cla-signed

#9189 [Fixes #9188] Unable to clone/copy geoapps
  geonode/base/api/tests.py
  geonode/geoapps/tests.py
  geonode/geoserver/manager.py
  geonode/layers/tests.py
  geonode/resource/manager.py
  geonode/resource/tests.py
  geonode/resource/utils.py
  geonode/tests/csw.py
Labels: cla-signed, backport 4.x

#9195 [Dependencies] Bump django-geonode-mapstore-client to version 4.x
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed

#9198 Bump to version 4.0.0rc0
  CHANGELOG.md
  geonode/__init__.py
Labels: cla-signed, backport 4.x

#9201 [Fixes #9200] Reference client 4.0.1 inside branch 4.x
  requirements.txt
Labels: cla-signed

#9204 [Fixes #9200] Make 4.x track client 4.x
  setup.cfg
Labels: cla-signed

#9203 [Fixes #9202] PEP-440 compliant version
  geonode/version.py
Labels: cla-signed, backport 4.x

#9209 [Fixes #9208] Fix mapstore client version in setup.cfg and requirements
  requirements.txt
  setup.cfg
Labels: cla-signed

#9214 [Fixes #9212] Login with basic auth or token headers or apikey GET parameter
  geonode/base/auth.py
  geonode/security/middleware.py
  geonode/security/tests.py
  geonode/settings.py
Labels: cla-signed

#9217 Revert "[Fixes #9212] Login with basic auth or token headers or apikey GET parameter"
  geonode/base/auth.py
  geonode/security/middleware.py
  geonode/security/tests.py
  geonode/settings.py
Labels: cla-signed

#9206 [Fixes #9205] Include Dataset.ows_url inside migrate_url
  geonode/base/management/commands/migrate_baseurl.py
Labels: cla-signed, backport 4.x

#9244 [Dependencies] Align setup.cfg to requirements
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9215 [Fixes #9210] Owner is still able to edit data and style after a resource has been approved and A/W is active
  geonode/base/api/serializers.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#9246 [Master][Fixes #9210] Owner is still able to edit data and style after a reso…
  geonode/base/api/serializers.py
  geonode/base/api/views.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed, backport 4.x

#9251 [Fixes #9250] Upload: task.set_charset(charset) may cause blocking error in case the GeoServer catalog has not aligned yet
  geonode/upload/upload.py
Labels: cla-signed, backport 3.3.x, backport 4.x
