Repository GeoNode/geonode, pull requests merged in 2022-03, with the labels that each got.

#8853 [Fixes #8849] Add tests for the automatic permissions set when a new resource is created
  geonode/geoserver/tests/integration.py
Labels: cla-signed, master

#8871 [Backport to 3.3.x][Fixes #8869] "updatelayers" management command does not fully update…
  geonode/base/forms.py
  geonode/base/models.py
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_helpers.py
  geonode/layers/models.py
  geonode/layers/views.py
  geonode/security/views.py
  geonode/services/serviceprocessors/wms.py
  geonode/settings.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
  geonode/utils.py
Labels: cla-signed

#8878 [Fixes #8873] Permissions not checked on the direct download button of a resource
  geonode/layers/tests.py
  geonode/layers/views.py
Labels: cla-signed, backport 4.x

#8882 [Fixes #8873] Permissions not checked on the direct download button of a resource
  geonode/layers/tests.py
  geonode/layers/views.py
Labels: cla-signed, backport 4.x

#8886 [Backport][Fixes #8873] Permissions not checked on the direct download button of a resource
  geonode/layers/tests.py
  geonode/layers/views.py
Labels: cla-signed

#8904 [Fixes #8887] Fixes and adjustments required for dataset direct download
  geonode/geoserver/helpers.py
  geonode/layers/tests.py
  geonode/layers/views.py
Labels: cla-signed, backport 4.x

#8857 [Fixes #8347] Implement limiting for the number of upload sessions per user
  geonode/settings.py
  geonode/upload/admin.py
  geonode/upload/api/serializers.py
  geonode/upload/api/tests.py
  geonode/upload/api/urls.py
  geonode/upload/api/views.py
  geonode/upload/forms.py
  geonode/upload/migrations/0037_uploadparallelismlimit.py
  geonode/upload/models.py
  geonode/upload/views.py
Labels: cla-signed, backport 4.x

#8914 [Fixes #8910] "migrate_baseurl" Management Command does not replace the "source-address" on all the "blobs"
  geonode/base/management/commands/migrate_baseurl.py
Labels: cla-signed, backport 4.x

#8925 Add function to get max upload parallelism limit for a given slug
  geonode/upload/tests/test_utils.py
  geonode/upload/utils.py
Labels: cla-signed

#8926 [Fixes #8913] Duplicate keyword error raised on massive upload
  geonode/base/models.py
  geonode/base/tests.py
  geonode/resource/utils.py
  geonode/tests/smoke.py
  geonode/upload/tests/test_utils.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#8933 [Backport][Fixes #8913] Duplicate keyword error raised on massive upload
  geonode/base/models.py
  geonode/upload/utils.py
Labels: cla-signed

#8936 [Backport 3.3.x][Fixes #8934] Allow configuration of projection and patch rules via settings.py for geonode-mapstore-client
  geonode/settings.py
Labels: cla-signed

#8935 [Fixes #8934] Allow configuration of projection and patch rules via settings.py for geonode-mapstore-client
  geonode/settings.py
Labels: cla-signed

#8940 [Fixes #8939] Fix store_spatial_files in upload form
  geonode/upload/views.py
Labels: backport 3.3.x

#8949 Issue 8946
  geonode/base/api/exceptions.py
  geonode/layers/api/exceptions.py
  geonode/layers/api/serializers.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/models.py
  geonode/layers/utils.py
Labels: cla-signed

#8951 [Fixes #8950] DocumentUploadView exception return HTML instead of JSON
  geonode/documents/views.py
Labels: cla-signed, backport 4.x

#8911 [Fixes #8908] Review API v2 allowed methods
  geonode/base/api/permissions.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/documents/api/views.py
  geonode/geoapps/api/tests.py
  geonode/geoapps/api/views.py
  geonode/layers/api/views.py
  geonode/maps/api/views.py
  geonode/resource/api/urls.py
  geonode/upload/api/tests.py
  geonode/upload/api/views.py
Labels: cla-signed, backport 4.x

#8953 [Backport 8911 to 4.x][Fixes #8908] Review API v2 allowed methods (#8911)
  geonode/base/api/permissions.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/documents/api/views.py
  geonode/geoapps/api/tests.py
  geonode/geoapps/api/views.py
  geonode/layers/api/views.py
  geonode/maps/api/views.py
  geonode/resource/api/urls.py
  geonode/upload/api/tests.py
  geonode/upload/api/views.py
Labels: cla-signed

#8968 Issue 8947
  geonode/base/api/exceptions.py
  geonode/geoserver/manager.py
  geonode/layers/api/exceptions.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/utils.py
  geonode/resource/manager.py
  geonode/storage/data_retriever.py
  geonode/storage/exceptions.py
  geonode/storage/manager.py
  geonode/storage/tests.py
  geonode/upload/api/tests.py
  geonode/upload/forms.py
  geonode/upload/upload.py
  geonode/upload/upload_validators.py
  geonode/upload/views.py
  geonode/utils.py
Labels: cla-signed

#8988 [Fixes #8987]Add missing option for list remote resources
  geonode/services/tasks.py
Labels: cla-signed, 3.3.x

#8985 [Fixes #8984] Error adding remote services
  geonode/base/models.py
Labels: cla-signed

#8967 Deep testing "Advanced Workflow" use cases
  geonode/base/api/permissions.py
  geonode/base/api/tests.py
  geonode/base/migrations/0080_alter_resourcebase_uuid.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/geoserver/manager.py
  geonode/groups/models.py
  geonode/groups/tests.py
  geonode/layers/tests.py
  geonode/resource/manager.py
  geonode/security/models.py
  geonode/security/permissions.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/settings.py
  geonode/tests/test_search.py
  geonode/upload/views.py
  tasks.py
Labels: security, cla-signed, performance, enhancement, code quality, backport 4.x

#8978 [Backport 3.3.x][Fixes #8937] User with perms can edit approved and published resources when Advanced workflow is enabled
  geonode/base/populate_test_data.py
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/documents/views.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
  test_dev.sh
Labels: cla-signed

#9008 [Fixes #8937] User with perms can edit approved and published resources when Advanced workflow is enabled
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed, backport 4.x
