Repository GeoNode/geonode, pull requests merged in 2022-08, with the labels that each got.

#9793 [Backport to 4.x] Dependencies alignement 4.x
  geonode/documents/tests.py
  geonode/geoserver/helpers.py
  geonode/invitations/forms.py
  geonode/layers/utils.py
  geonode/maps/tests.py
  geonode/security/tests.py
  geonode/utils.py
  setup.cfg
Labels: dependencies, cla-signed

#9796 [Fixes #9794] Include favorite property inside resource endpoint
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
Labels: cla-signed, backport 4.x

#9613 [Fixes #9604] Report empty thumbnail in case a thumbnail has not been generated for a resource
  geonode/api/resourcebase_api.py
  geonode/base/migrations/0083_clean_resources_with_missing_thumb.py
  geonode/base/models.py
  geonode/base/tests.py
  geonode/geoserver/helpers.py
  geonode/geoserver/manager.py
  geonode/geoserver/signals.py
  geonode/maps/api/tests.py
  geonode/resource/manager.py
  geonode/thumbs/tests/test_integration.py
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
  geonode/utils.py
Labels: cla-signed, backport 4.x

#9798 [Fixes #9797] "importlayers" management command ignores sidecar and zip files
  geonode/geoserver/management/commands/importlayers.py
  geonode/upload/upload.py
Labels: cla-signed, backport 4.x

#9803 [Fixes #9795] Registered members with edit/manage permission can not …
  geonode/security/models.py
  geonode/security/utils.py
Labels: cla-signed, backport 4.x

#9817 [Fixes #9816] Cannot add favorite
  geonode/base/api/permissions.py
  geonode/base/api/views.py
  geonode/security/tests.py
Labels: cla-signed, backport 4.x

#9800 [Fixes #9799] Thesaurus selectbox performance in metadata editor is very slow
  geonode/base/forms.py
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/base/views.py
Labels: cla-signed, backport 4.x

#9836 [BACKPORT][Fixes #9799] Thesaurus selectbox performance in metadata editor is v…
  geonode/base/forms.py
  geonode/base/tests.py
  geonode/base/utils.py
  geonode/base/views.py
Labels: cla-signed

#9841 [Fixes #9838] forever loading state on index site (API returns 403)
  geonode/base/api/permissions.py
Labels: cla-signed, backport 4.x

#9859 Add test on extra metadata
  geonode/base/api/tests.py
Labels: cla-signed, backport 4.x

#9810 [Backport to 4.x][Fixes #9604] Report empty thumbnail in case a thumbnail has not been…
  geonode/api/resourcebase_api.py
  geonode/base/migrations/0083_clean_resources_with_missing_thumb.py
  geonode/base/models.py
  geonode/base/tests.py
  geonode/geoserver/helpers.py
  geonode/geoserver/manager.py
  geonode/geoserver/signals.py
  geonode/maps/api/tests.py
  geonode/resource/manager.py
  geonode/thumbs/tests/test_integration.py
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
  geonode/utils.py
Labels: cla-signed

#9855 [Fixes #9839] db healthcheck fails with 'FATAL: role "root" does not exist'
  docker-compose-test.yml
  docker-compose.yml
Labels: cla-signed, backport 4.x

#9882 [Backport to 4.x][Fixes #9839] db healthcheck fails with 'FATAL: role "root" does not …
  docker-compose-test.yml
  docker-compose.yml
Labels: cla-signed

#9900 [Dependencies] align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9888 [Fixes #9887]Data retriever wrongly assign base_file value
  geonode/storage/data_retriever.py
  geonode/storage/tests.py
  geonode/storage/tests/data/example.zip
Labels: cla-signed, backport 4.x

#9864 [Fixes #9862] Thesaurus label are not available with default language
  geonode/base/forms.py
  geonode/base/utils.py
  geonode/base/views.py
  requirements.txt
  setup.cfg
Labels: cla-signed, backport 4.x

#9905 [Fixes #9901] Infinite loading if no resource with "view permissions"…
  geonode/base/api/permissions.py
Labels: cla-signed, backport 4.x

#9907 [Fixes #9881] AttributeError on viewing recent activities
  geonode/base/migrations/0084_remove_comments_from_actions.py
  geonode/context_processors.py
  geonode/documents/__init__.py
  geonode/geoapps/__init__.py
  geonode/geoserver/__init__.py
  geonode/geoserver/helpers.py
  geonode/groups/templates/groups/activity.html
  geonode/groups/views.py
  geonode/layers/__init__.py
  geonode/maps/__init__.py
  geonode/messaging/notifications.py
  geonode/notifications_helper.py
  geonode/settings.py
  geonode/social/signals.py
  geonode/social/templates/social/activity_list.html
  geonode/social/templatetags/social_tags.py
  geonode/social/views.py
  geonode/templates/_actions.html
  geonode/templates/about.html
  geonode/templates/pinax/notifications/document_comment/full.txt
  geonode/templates/pinax/notifications/document_comment/short.txt
  geonode/templates/pinax/notifications/layer_comment/full.txt
  geonode/templates/pinax/notifications/layer_comment/short.txt
  geonode/templates/pinax/notifications/map_comment/full.txt
  geonode/templates/pinax/notifications/map_comment/short.txt
Labels: cla-signed, backport 4.x

#9908 [Fixes #9878] drf_spectacular error breaks redoc and swagger-ui schemas
  geonode/resource/models.py
Labels: cla-signed

#9840 [Fixes #9821] Time serie selection handled by the advanced metadata panel
  geonode/geoserver/helpers.py
  geonode/layers/forms.py
  geonode/layers/models.py
  geonode/layers/templates/layouts/panels.html
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/security/models.py
  geonode/templates/metadata_form_js.html
  geonode/upload/upload.py
Labels: cla-signed, backport 4.x

#9915 [Fixes #9913] 3.3.X - Update django-markdownify package to 0.9.2 in r…
  requirements.txt
  setup.cfg
Labels: cla-signed

#9918 [Fixes #9917] Current django health check in docker-compose.yml useless.
  docker-compose.yml
Labels: cla-signed, backport 3.3.x, backport 4.x

#9929 Update helpers.py
  geonode/geoserver/helpers.py
Labels: cla-signed, backport 4.x

#9937 WIP - fix broken tests
  geonode/geoserver/helpers.py
Labels: cla-signed

#9936 [Dependencies] Align requirements.txt with setup.cfg
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9942 [3.3.x][Fixes #9921] Original Layer / Dataset not offered as Download on layer detail page
  geonode/base/utils.py
  geonode/layers/templates/layers/layer_detail.html
  geonode/templates/metadata_detail.html
Labels: cla-signed

#9941 [Fixes #9919] User endpoint return 404 if user is not in registered members
  geonode/base/api/tests.py
  geonode/people/utils.py
Labels: cla-signed, backport 4.x
