Repository GeoNode/geonode, pull requests merged in 2022-05, with the labels that each got.

#9255 [Backport 3.3.x] [Fixes #9250] Upload: task.set_charset(charset) may …
  geonode/upload/upload.py
Labels: cla-signed

#9264 bump django-markdownify to 0.9.1 fixes #9263
  requirements.txt
  setup.cfg
Labels: dependencies

#9267 [Fixes #9268] Refresh the harvest_job object
  geonode/services/tasks.py
Labels: cla-signed

#9265 Update uploadhandler.py
  geonode/layers/api/tests.py
  geonode/layers/views.py
  geonode/tests/base.py
  geonode/upload/api/tests.py
  geonode/upload/forms.py
  geonode/upload/uploadhandler.py
Labels: cla-signed

#9274 [Fixes #9269] Favorite tab shows Add to Favorites even when geoapp is…
  geonode/favorite/models.py
  geonode/favorite/tests.py
Labels: cla-signed

#9266 [33x] Set target store during upload phase
  geonode/geoserver/helpers.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
  geonode/upload/utils.py
Labels: cla-signed

#9270 [master] Set target store during upload phase
  geonode/geoserver/helpers.py
  geonode/layers/views.py
  geonode/storage/manager.py
  geonode/upload/tasks.py
  geonode/upload/upload.py
  geonode/upload/uploadhandler.py
  geonode/upload/utils.py
  geonode/version.py
Labels: cla-signed

#9282 [Dependencies] Align "setup.cfg" with "requirements.txt"
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9295 Owner is unable to delete a published/approved map and Request Change button is shown on map with a user having permissions to edit in A/W
  geonode/base/templatetags/base_tags.py
  geonode/maps/templates/maps/map_detail.html
Labels: cla-signed

#9303 [Dependencies] Align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: cla-signed, backport 4.x

#9300 [MASTER][Fixes #9283] Issue with owner perms on A/W
  geonode/base/templatetags/base_tags.py
Labels: cla-signed, backport 4.x

#9313 [Fixes #9312] Harvesters admin page is broken
  geonode/harvesting/admin.py
  geonode/services/serviceprocessors/wms.py
Labels: cla-signed, backport 4.x

#9316 [Fixes #9315] Avoid the "set_permissions" method breaks the dataset in the case a perm cannot be assigned to the resource
  geonode/resource/manager.py
Labels: cla-signed, backport 4.x

#9322 [Fixes #9196] Fix storage manager copy function
  geonode/storage/manager.py
Labels: cla-signed, backport 4.x

#9333 [Fixes #9332] A/W: owner should not have any modification permission on published resource
  geonode/security/utils.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9335 [33x][Fixes #9332] A/W: owner should not have any modification permission …
  geonode/security/utils.py
Labels: cla-signed

#9337 Revert "[Fixes #9332] A/W: owner should not have any modification permission on published resource"
  geonode/security/utils.py
Labels: cla-signed

#9338 [Fixes #9332] A/W: owner should not have any modification permission on published resource
  geonode/security/utils.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9331 [Fixes #9330] Upload randomly causing "java.lang.NullPointerException" during Import
  geonode/geoserver/tests/test_server.py
  geonode/security/tests.py
  geonode/upload/api/tests.py
  geonode/upload/tests/test_utils.py
  geonode/upload/tests/utils.py
  geonode/upload/upload.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9343 [Fixes #9332][Test Cases] A/W: owner should not have any modification permission on published resource
  geonode/security/tests.py
Labels: cla-signed, backport 4.x

#9342 [Backport 3.3.x] [Fixes #9330] Upload randomly causing "java.lang.NullPointerException" during Import
  geonode/upload/upload.py
Labels: cla-signed

#9344 [Backport 3.3.x][Fixes #9332][Test Cases] A/W: owner should not have any modification permission on published resource
  geonode/security/tests.py
Labels: cla-signed

#9366 [Dependencies] Align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9374 [Fixes #9314] Error on Searching uploads in Admin Site
  geonode/upload/admin.py
Labels: cla-signed

#9375 [4.x][Fixes #9314] Error on Searching uploads in Admin Site
  geonode/upload/admin.py
Labels: cla-signed

#9376 [3.3.x][Fixes #9314] Error on Searching uploads in Admin Site
  geonode/upload/admin.py
Labels: cla-signed

#9371 [Fixes #9370] "catalogue_post_save" fails on retrieving the self resource
  geonode/base/api/tests.py
  geonode/catalogue/models.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9372 [Backport 3.3.x][Fixes #9370] "catalogue_post_save" fails on retrieving the self resource
  geonode/base/api/tests.py
  geonode/catalogue/models.py
  geonode/thumbs/thumbnails.py
  geonode/version.py
Labels: cla-signed

#9378 [Fixes #9377] Login Middleware with APIToken
  geonode/base/auth.py
  geonode/security/middleware.py
  geonode/security/tests.py
  geonode/settings.py
Labels: cla-signed, backport 4.x

#9387 [Fixes #9386] Adopt DRF exceptions inside maps APIv2
  geonode/maps/api/exception.py
  geonode/maps/api/tests.py
  geonode/maps/api/views.py
Labels: cla-signed, API v2, backport 4.x

#9412 [Dependencies] Align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9423 [Fixes #9413] Adopt DRF exceptions inside geoapps APIv2 4.0.x API v2
  geonode/geoapps/api/exceptions.py
  geonode/geoapps/api/serializers.py
  geonode/geoapps/api/tests.py
Labels: cla-signed, backport 4.x

#9427 [Fixes #9426][Remote Services] Errors on creating WMS Cascade stores and layers
  geonode/services/serviceprocessors/wms.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#9425 [Fixes #9418] change the default JAVA_OPTS to the public URL inside GeoNode .env file
  .env
  .env_dev
  .env_local
  .env_test
Labels: cla-signed, backport 3.3.x, backport 4.x

#9390 [Fixes #9389] Geoapps are added to favorites but not listed on client UI
  geonode/base/api/filters.py
  geonode/base/api/tests.py
Labels: cla-signed, backport 4.x

#9391 [Fixes #9381] Hide users to anonoymous users and restric visibility for authenticated users
  geonode/api/api.py
  geonode/api/authorization.py
  geonode/api/tests.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/people/tests.py
  geonode/people/urls.py
  geonode/people/utils.py
  geonode/people/views.py
  geonode/tests/smoke.py
Labels: cla-signed, backport 4.x

#9438 [Fixes #9109] Filter for Regions and categories include items with no resources connectet
  geonode/base/api/filters.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed, backport 4.x

#9451 [Dependencies] Align "setup.cfg" to "requirements.txt"
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/layers/tests.py
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x
