Repository GeoNode/geonode, pull requests merged in 2022-11, with the labels that each got.

#10242 [Dependencies] Align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10252 [Fixes #10251] Review geonode management command set_layers_permissions
  geonode/base/admin.py
  geonode/base/forms.py
  geonode/base/templates/base/user_and_group_permissions.html
  geonode/base/views.py
  geonode/layers/management/commands/set_layers_permissions.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/people/tests.py
  geonode/people/urls.py
  geonode/settings.py
Labels: cla-signed, backport 4.0.x

#10212 [4.0.x][Fixes #10208] Add a custom hook at the end of the permissions assign
  geonode/geoserver/manager.py
  geonode/geoserver/signals.py
Labels: cla-signed

#10264 [Fixes #10263] non admin user in fresh instance cannot create resources_
  geonode/base/api/views.py
  geonode/geoapps/api/views.py
  geonode/layers/api/views.py
  geonode/maps/api/views.py
Labels: cla-signed, backport 4.0.x

#10213 [Fixes #10208] Add a custom hook at the end of the permissions assign
  geonode/geoserver/manager.py
  geonode/geoserver/signals.py
Labels: cla-signed

#10266 Fix broken test
  geonode/base/auth.py
  geonode/security/tests.py
Labels: cla-signed, backport 4.0.x

#10164 Bump GeoServer to version 2.20.6
  .devcontainer/.env
  .env
  .env_dev
  .env_local
  .env_test
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose-test.yml
  docker-compose.yml
  package/geoserver/rpm/SPECS/geoserver.spec
  pavement.py
Labels: dependencies, cla-signed, backport 4.0.x

#10281 [Fixes #10251] improve feedback to the user and UI experience of batch permisisons assignment
  geonode/base/admin.py
  geonode/base/forms.py
  geonode/base/templates/base/user_and_group_permissions.html
  geonode/base/urls.py
  geonode/base/views.py
  geonode/people/tests.py
Labels: cla-signed, backport 4.0.x

#10284 [Dependencies] Align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10288 [Fixes #10287] The "set_layer_permissions" management command does not behave correctly with "AnonyousUser"
  geonode/base/views.py
  geonode/layers/tests.py
  geonode/layers/utils.py
Labels: cla-signed, backport 4.0.x

#10271 [Fixes #10270] Document creation via API v2
  geonode/base/migrations/0085_alter_resourcebase_uuid.py
  geonode/base/models.py
  geonode/documents/api/exceptions.py
  geonode/documents/api/serializers.py
  geonode/documents/api/tests.py
  geonode/documents/api/views.py
Labels: cla-signed, backport 4.0.x

#10315 [Dependencies] Align setup.cfg with requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10309 [Fixes #10302] Incorrect permissions assigned on cloning a resource
  geonode/base/api/tests.py
  geonode/resource/manager.py
Labels: cla-signed, backport 4.0.x

#10338 [Fixes #9041] Docker NGINX listen on ports 80/443
  scripts/docker/nginx/docker-entrypoint.sh
  scripts/docker/nginx/nginx.conf.envsubst
  scripts/docker/nginx/nginx.https.available.conf.envsubst
Labels: cla-signed, backport 4.0.x

#10339 [Dependencies] Align setup.cfg with requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10300 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  requirements_dev.txt
Labels: dependencies, security, cla-signed, backport 4.0.x, backport 4.1.x

#10317 [Fixes #10316] bbox_polygon & ll_bbox_polygon should be read-only in serializer
  geonode/base/api/serializers.py
Labels: backport 4.0.x, backport 4.1.x
