Repository GeoNode/geonode, pull requests merged in 2022-06, with the labels that each got.

#9453 Bump gn-gsimporter to version 2.0.4
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9455 Bump django-geonode-mapstore-client to version 3.3.2
  requirements.txt
Labels: dependencies, cla-signed

#9472 [Fixes #9471] add resource_type as filter in legacy API
  geonode/api/resourcebase_api.py
Labels: cla-signed, 3.3.x

#9476 [Fixes #9475] PRINT_BASE_URL on JAVA_OPTS should be pointing to localhost:8080 on default env
  .env
Labels: cla-signed, backport 3.3.x, backport 4.x

#9485 [Fixes #9475] PRINT_BASE_URL on JAVA_OPTS should be pointing to local…
  .env
Labels: cla-signed, backport 3.3.x, backport 4.x

#9488 Bump to version 3.3.2 final
  CHANGELOG.md
  geonode/__init__.py
Labels: cla-signed

#9482 [Dependencies] Align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: cla-signed, backport 4.x

#9495 Bump to version 3.3.2.post1
  CHANGELOG.md
  geonode/__init__.py
Labels: cla-signed

#9499 [Fixes #9498] Documents, Maps and GeoApps permissions are not persisted on GeoNode
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#9501 [Fixes #9500] OWS Url wrong for INDEXED Remote Services
  geonode/utils.py
Labels: cla-signed

#9512 [Fixes #9510] Extend ExecutionRequest model
  geonode/resource/api/tasks.py
  geonode/resource/api/views.py
  geonode/resource/migrations/0004_executionrequest_step.py
  geonode/resource/migrations/0005_executionrequest_log.py
  geonode/resource/models.py
Labels: cla-signed, backport 4.x

#9532 [Fixes #9531] Provide priority to _update_geofence_rule method
  geonode/geoserver/security.py
Labels: cla-signed

#9530 [Fixes #9529] psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "base_hierarchicalkeyword_path_key"
  geonode/base/models.py
Labels: backport 4.x

#9528 [Fixes #9511] extrapolate FileUploadSizeLimit and UploadParallelismLi…
  geonode/settings.py
  geonode/upload/api/tests.py
  geonode/upload/forms.py
  geonode/upload/uploadhandler.py
  geonode/upload/utils.py
Labels: cla-signed, backport 4.x

#9558 [Dependencies] Align setup.cfg to requirements
  setup.cfg
Labels: dependencies, cla-signed
