Repository GeoNode/geonode, pull requests merged in 2022-10, with the labels that each got.

#10074 [Fixes #10073] Unable to view Maps tab in Recent activities
  geonode/social/templates/social/activity_list.html
Labels: cla-signed, backport 4.0.x

#10092 [Fixes #10091] improve thumbnails quality
  geonode/base/api/tests.py
  geonode/base/models.py
  geonode/documents/tasks.py
  geonode/documents/tests.py
  geonode/thumbs/tests/test_integration.py
Labels: cla-signed, backport 4.0.x

#10094 [Fixes #10075] Improvements to the upload time step UI
  geonode/static/geonode/js/upload/time.js
  geonode/upload/templates/upload/dataset_upload_base.html
  geonode/upload/templates/upload/dataset_upload_time.html
Labels: cla-signed, backport 4.0.x

#10114 [Fixes #10113] Data retriver keep kmz files even if is unzipped
  geonode/storage/data_retriever.py
  geonode/storage/tests.py
  geonode/storage/tests/data/Italy.kmz
Labels: cla-signed, backport 4.0.x

#10105 [Fixes #10104] Sort resource APIs with created date
  geonode/base/api/serializers.py
  geonode/base/api/views.py
  geonode/documents/api/views.py
  geonode/geoapps/api/views.py
  geonode/layers/api/views.py
  geonode/maps/api/views.py
Labels: cla-signed, backport 4.0.x

#10124 [Dependencies] Align setup.cfg to requirements.txt
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10121 [Fixes #10120] Celery autoscale values are too low and wrongly positi…
  .env
  celery-cmd
Labels: cla-signed, backport 3.3.x, backport 4.0.x

#10128 [Backport to 4.0.x][Dependencies] Align setup.cfg to requirements.txt (#10124)
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed

#10131 [Fixes #10130] Data retriever dont assign the folder/file permissions…
  geonode/storage/data_retriever.py
Labels: cla-signed, backport 4.0.x

#10135 [Fixes #10134] New simple renderer to generate thumbnails for PDFs
  geonode/documents/management/commands/sync_geonode_documents.py
  geonode/documents/tasks.py
  geonode/documents/tests.py
  geonode/documents/tests/data/pdf_doc.pdf
  requirements.txt
  setup.cfg
Labels: cla-signed, backport 4.0.x

#10139 [Fixes #10138] Render pdf thumbnails from top margin
  geonode/base/models.py
  geonode/documents/management/commands/sync_geonode_documents.py
  geonode/documents/tasks.py
Labels: cla-signed, backport 4.0.x

#10143 [Fixes #10142] storage_manager copy dont assign the folder/file permi…
  geonode/storage/manager.py
  geonode/storage/tests.py
Labels: cla-signed, backport 4.0.x

#10162 Align setup.cfg with requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10169 [Fixes #10168] Add 'executions' field to concrete instance endpoints
  geonode/documents/api/serializers.py
  geonode/geoapps/api/serializers.py
  geonode/layers/api/serializers.py
  geonode/maps/api/serializers.py
Labels: cla-signed, backport 4.0.x

#10166 [Fixes #10165][3.2.x][Depencendies] Security audit and checks
  geonode/security/tests.py
  requirements.txt
  setup.cfg
Labels: dependencies, security, cla-signed

#10172 [Fixes #10171] Dynamic rendering of document_detail view template
  geonode/documents/templates/documents/document_metadata_detail.html
  geonode/templates/metadata_detail.html
Labels: cla-signed, backport 4.0.x

#10176 Fix migrations 4x
  geonode/base/migrations/0060_resourcebase_state.py
  geonode/base/migrations/0064_resourcebase_metadata.py
  geonode/upload/migrations/0032_uploadsizelimit.py
  geonode/upload/migrations/0033_auto_20210527_1520.py
  geonode/upload/migrations/0033_auto_20210528_1556.py
  geonode/upload/migrations/0033_auto_20210531_1252.py
  geonode/upload/migrations/0033_upload_store_spatial_files.py
  geonode/upload/migrations/0035_update_uploadsizelimit_objects.py
  geonode/upload/migrations/0037_uploadparallelismlimit.py
Labels: cla-signed, backport 4.0.x

#10199 [Fixes #10198] uwsgi library update
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.0.x

#10196 [Fixes #10195] Backup and restore procedure is not successful
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
Labels: cla-signed, backport 4.0.x

#10205 [Fixes #10204] restore mapstore catalog settings
  geonode/local_settings.py.geoserver.sample
  geonode/settings.py
Labels: cla-signed, backport 4.0.x

#10193 [Fixes #10192] Include source into the ExecutionRequest model
  geonode/resource/api/tests.py
  geonode/resource/migrations/0008_executionrequest_source.py
  geonode/resource/models.py
Labels: cla-signed, backport 4.0.x

#10218 [Fixes #10217] fix ip whitelisting
  geonode/base/auth.py
Labels: cla-signed, backport 4.0.x
