Repository GeoNode/geonode, pull requests merged in 2022-07, with the labels that each got.

#9563 [Fixes #9562] Inconsistency information on layer upload along with an…
  geonode/upload/upload.py
Labels: cla-signed

#9582 [Fixes #9518] br/restore call to migrate always fails
  geonode/br/management/commands/restore.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9584 [Backport 4.x][Fixes #9518] br/restore call to migrate always fails
  geonode/br/management/commands/restore.py
Labels: cla-signed

#9586 [Backport 3.3.x] [Fixes #9518] br/restore call to migrate always fails
  geonode/br/management/commands/restore.py
Labels: cla-signed

#9588 [Dependencies] Align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9593 [Snyk] Security upgrade django from 3.2.13 to 3.2.14
  requirements.txt
Labels: dependencies, cla-signed, backport 4.x

#9599 [Dependencies] Align "setup.cfg" to "requirements.txt" (#9588)
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9600 [Fixes https://github.com/GeoNode/geonode-project/issues/342] Geoserv…
  package/install.sh
Labels: cla-signed, backport 3.3.x, backport 4.x

#9592 [Fixes #9591] Expose supported upload file formats as configurations
  geonode/settings.py
  geonode/tests/test_utils.py
  geonode/utils.py
Labels: cla-signed, enhancement, 4.0.x

#9612 [Backport 4x][Fixes #9591] Expose supported upload file formats as configurations…
  geonode/settings.py
  geonode/tests/test_utils.py
  geonode/utils.py
Labels: cla-signed

#9616 [Fixes #9591] Expose supported upload file formats as configurations
  geonode/tests/test_utils.py
  geonode/utils.py
Labels: cla-signed

#9605 - Bump GeoServer to version 2.20.5
  .circleci/config.yml
  .devcontainer/.env
  .env
  .env_dev
  .env_local
  .env_test
  Dockerfile
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose-test.yml
  docker-compose.yml
Labels: dependencies, cla-signed, backport 4.x

#9638 [Fixes #9637] Performance scalability issues with Thumbnail generation
  geonode/geoserver/helpers.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/utils.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9641 [Backport to 3.3.x][Fixes #9637] Performance scalability issues with Thumbnail generation
  geonode/geoserver/helpers.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/utils.py
Labels: cla-signed

#9653 [Fixes #9652] Avoid Whitenoise compression if not explicitly needed
  geonode/settings.py
  pavement.py
Labels: cla-signed, backport 4.x

#9626 [Fixes #9623] 400 error on some APIs when a Bearer token is used
  geonode/base/api/views.py
Labels: cla-signed, backport 4.x

#9666 [Backport to 3.3.x][Fixes #9662][Docker] Wrong healthcheck on Django container
  docker-compose.yml
Labels: cla-signed

#9670 [Fixes #9669] Updatelayers unexpectedly fails if layer is 'None'
  geonode/geoserver/helpers.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9674 [Fixes #9673] Proxy must use OGC_REQUEST_TIMEOUT instead of an hardcoded one
  geonode/proxy/views.py
Labels: cla-signed, backport 3.3.x, backport 4.x

#9688 [Fixes #9687] fix Geoserver public location in ident_json
  geonode/views.py
Labels: cla-signed, backport 4.x

#9684 Fix #9683 typo in italian translation
  geonode/locale/it/LC_MESSAGES/django.po
Labels: translations

#9690 [Fix #9689] Fix people tests
  .circleci/config.yml
Labels: cla-signed, backport 4.x

#9686 [Fix #9685] Implement additional password validators
  geonode/people/password_validators.py
  geonode/people/tests.py
Labels: cla-signed, backport 4.x

#9712 [Snyk] Security upgrade nginx from 1.21.4-alpine to 1.23.0-alpine
  scripts/docker/nginx/Dockerfile
Labels: dependencies, cla-signed, backport 3.3.x, backport 4.x

#9709 [Dependencies] Align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9703 [Fixes #9696] Make the concrete manager injectable
  geonode/resource/manager.py
Labels: cla-signed, backport 4.x

#9719 [Fixes #9718] fix renaming of CORS_ORIGIN_ALLOW_ALL
  .circleci/config.yml
  .devcontainer/.env
  .env
  .env_dev
  .env_local
  .env_test
  geonode/local_settings.py.geoserver.sample
  geonode/settings.py
  geonode/tests/test_headers.py
  package/support/geonode.local_settings
Labels: cla-signed, backport 3.3.x, backport 4.x

#9710 [Fixes #9698] Allow admin access from whitelisted IPs
  geonode/base/auth.py
  geonode/security/middleware.py
  geonode/security/tests.py
  geonode/settings.py
Labels: cla-signed, backport 4.x

#9737 [Fixes #9736] Rename ExecutionRequest enum
  geonode/resource/enumerator.py
  geonode/resource/migrations/0007_alter_executionrequest_action.py
  geonode/resource/models.py
Labels: cla-signed, backport 4.x

#9743 fix error in refactor
  geonode/resource/migrations/0006_executionrequest_action.py
Labels: cla-signed, backport 4.x

#9724 [Fixes #9722] dump_thesaurus management script not working properly
  geonode/base/management/commands/dump_thesaurus.py
Labels: cla-signed, backport 4.x

#9746 [dependencies] align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.x

#9728 [Fixes #9727] Improvements to admin whitelisting
  geonode/base/auth.py
  geonode/security/backends.py
  geonode/security/middleware.py
  geonode/security/tests.py
  geonode/settings.py
  geonode/tests/test_headers.py
Labels: cla-signed, backport 4.x

#9745 [Backport to 4.x][Fixes #9722] dump_thesaurus management script not working properly (…
  geonode/base/management/commands/dump_thesaurus.py
Labels: cla-signed

#9755 [Fixes #9754] handle get_dataset_detail_context returned value
  geonode/layers/views.py
Labels: cla-signed, backport 4.x

#9753 [Fixes #9752] fix SessionControlMiddleware test
  geonode/security/tests.py
Labels: cla-signed, backport 4.x

#9751 [Fixes #9749] ALLOWED_EXTENSIONS should rely on filetype in the settings
  geonode/base/models.py
  geonode/geoserver/manager.py
  geonode/upload/files.py
  geonode/utils.py
Labels: cla-signed, backport 4.x

#9757 [Fixes #9756] ExecutionRequest endpoint should allow the delete
  geonode/resource/api/exceptions.py
  geonode/resource/api/tests.py
  geonode/resource/api/views.py
Labels: cla-signed, backport 4.x

#9758 [Backport to 4.x][Fixes #9752] fix SessionControlMiddleware test (#9753)
  geonode/security/tests.py
Labels: cla-signed

#9763 [Backport 4.x] [Fixes #9748] Cleanup of stale code
  geonode/base/migrations/0082_remove_dialogos_comment.py
  geonode/br/management/commands/settings_docker_sample.ini
  geonode/br/management/commands/settings_sample.ini
  geonode/client/templates/ol/datasets/dataset_ol3_map.html
  geonode/client/templates/ol/maps/map_ol3.html
  geonode/documents/search_indexes.py
  geonode/documents/templates/documents/document_thumb_upload.html
  geonode/documents/tests.py
  geonode/favorite/README.md
  geonode/favorite/templates/favorite/_favorite.html
  geonode/favorite/templates/favorite/_favorite_js.html
  geonode/favorite/templates/favorite/favorite_list.html
  geonode/favorite/tests.py
  geonode/favorite/urls.py
  geonode/favorite/views.py
  geonode/geoserver/createlayer/templates/createlayer/dataset_create.html
  geonode/geoserver/helpers.py
  geonode/groups/templates/groups/category_list.html
  geonode/groups/templates/groups/group_list.html
  geonode/groups/templates/groups/group_members.html
  geonode/layers/search_indexes.py
  geonode/layers/templates/datasets/dataset_append.html
  geonode/layers/templates/datasets/dataset_detail.html
  geonode/layers/templates/datasets/dataset_metadata_upload.html
  geonode/layers/templates/datasets/dataset_replace.html
  geonode/layers/templates/datasets/dataset_style_upload.html
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/maps/search_indexes.py
  geonode/maps/tests.py
  geonode/people/templates/people/profile_detail.html
  geonode/people/templates/people/profile_list.html
  geonode/settings.py
  geonode/social/apps.py
  geonode/social/signals.py
  geonode/social/tests.py
  geonode/static/gruntfile.js
  geonode/templates/_actions.html
  geonode/templates/_comments.html
  geonode/templates/_permissions_form.html
  geonode/templates/_permissions_form_js.html
  geonode/templates/avatar/add.html
  geonode/templates/avatar/change.html
  geonode/templates/avatar/confirm_delete.html
  geonode/templates/base.html
  geonode/templates/dialogos/_comment.html
  geonode/templates/index.html
  geonode/templates/metadata_base.html
  geonode/templates/rating.html
  geonode/templates/relationships/_list_connections.html
  geonode/templates/relationships/_manage_connections.html
  geonode/templates/relationships/_profile_follow.html
  geonode/templates/relationships/confirm.html
  geonode/templates/relationships/relationship_list.html
  geonode/templates/relationships/success.html
  geonode/templates/request_download.html
  geonode/urls.py
  package/debian/control
  requirements.txt
  setup.cfg
Labels: cla-signed

#9764 Fixes CSW test cases
  .circleci/config.yml
  .env_test
  geonode/people/utils.py
  geonode/resource/api/tests.py
  geonode/settings.py
  geonode/tests/csw.py
  geonode/tests/test_headers.py
  geonode/tests/test_utils.py
Labels: cla-signed

#9717 Align letsencrypt docker container to geonode-project
  scripts/docker/letsencrypt/Dockerfile
  scripts/docker/letsencrypt/README.md
  scripts/docker/letsencrypt/crontab
  scripts/docker/letsencrypt/docker-entrypoint.sh
Labels: docker, cla-signed, backport 3.3.x, backport 4.x

#9762 [Fixes #9761] simplify map embed biew
  geonode/layers/views.py
Labels: cla-signed, backport 4.x

#9768 [Backport to 4.x] - Bunch of minor improvements that must be backported to 4.x
  .clabot
  README.md
  geonode/layers/views.py
  geonode/locale/it/LC_MESSAGES/django.po
  requirements.txt
Labels: cla-signed

#9771 [Backport to 4.x] simplify map embed biew (#9762)
  geonode/layers/views.py
Labels: cla-signed
