Repository GeoNode/geonode, pull requests merged in 2022-02, with the labels that each got.

#8724 [Fixes #8723] Return plain text error response when document upload is run with no__redirect
  geonode/documents/views.py
Labels: cla-signed

#8725 [Fixes #8720] Change total_upload_size_sum slug to dataset_upload_size
  geonode/upload/admin.py
  geonode/upload/api/serializers.py
  geonode/upload/api/tests.py
  geonode/upload/api/views.py
  geonode/upload/forms.py
  geonode/upload/migrations/0035_update_uploadsizelimit_objects.py
  geonode/upload/models.py
  geonode/upload/tests/integration.py
Labels: cla-signed, master

#8722 [Fixes #8721] Missing resource type for some uploaded datasets
  geonode/resource/manager.py
Labels: cla-signed, master

#8702 Re-implement thesaurus import/export using rdflib to support a wider range of RDF formats [Fixes #8701]
  geonode/base/management/commands/dump_thesaurus.py
  geonode/base/management/commands/load_thesaurus.py
  geonode/base/migrations/0076_auto_20220128_0919.py
  geonode/base/models.py
  geonode/tests/test_dump_thesaurus.py
  geonode/tests/test_load_thesaurus.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#8729 Add function to get upload size
  geonode/upload/tests/test_utils.py
  geonode/upload/utils.py
Labels: cla-signed

#8717 [Backport 3.3.x][Fixes #8454] Rating average available only in English
  geonode/geoapps/templates/apps/app_detail.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/maps/templates/maps/map_detail.html
Labels: cla-signed, 3.3.x

#8716 [3.2.x][Fixes #8454] Rating average available only in English
  geonode/geoapps/templates/apps/app_detail.html
  geonode/layers/templates/layers/layer_detail.html
  geonode/maps/templates/maps/map_detail.html
Labels: cla-signed, 3.2.x

#8727 [3.3.x][Fixes #8689] Extend the ResourceBase metadata model with an opaque JSONField
  geonode/api/resourcebase_api.py
  geonode/api/tests.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/forms.py
  geonode/base/migrations/0062_resourcebase_extra_metadata.py
  geonode/base/migrations/0063_auto_20220128_1042.py
  geonode/base/migrations/0064_resourcebase_metadata.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/base/utils.py
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/tests.py
  geonode/documents/views.py
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoapps/tests.py
  geonode/geoapps/views.py
  geonode/layers/api/views.py
  geonode/layers/templates/layouts/panels.html
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/settings.py
  geonode/templates/metadata_form_js.html
  requirements.txt
  setup.cfg
Labels: cla-signed, 3.3.x

#8735 [Fixes #8732] Notifications for account approval are sent even if GeoNode is configured for open signup
  geonode/people/signals.py
  geonode/templates/pinax/notifications/account_approve/full.txt
Labels: cla-signed

#8733 [3.3.x] [Fixes #8690] Custom filters available for the “ResourceBase” opaque filters
  geonode/api/resourcebase_api.py
  geonode/base/templatetags/base_tags.py
  geonode/templates/search/_dynamic_metadata_filter.html
  geonode/templates/search/_search_content.html
Labels: cla-signed

#8742 [Fixes #8740] Adopt default permissions for new resources
  geonode/documents/forms.py
  geonode/documents/tests.py
  geonode/geoserver/createlayer/templates/createlayer/dataset_create.html
  geonode/geoserver/createlayer/tests.py
  geonode/geoserver/createlayer/utils.py
  geonode/geoserver/createlayer/views.py
  geonode/layers/forms.py
  geonode/security/permissions.py
  geonode/upload/forms.py
Labels: cla-signed

#8713 [Fixes #8700] Add the option to include the executions status of a resource inside the resources API response
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed, master

#8761 [Fixes #8760] Support Basic Auth for proxied requests to change styles
  geonode/api/tests.py
  geonode/base/auth.py
  geonode/documents/tests.py
  geonode/geoserver/tests/integration.py
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/urls.py
  geonode/geoserver/views.py
  geonode/groups/tests.py
  geonode/people/tests.py
  geonode/proxy/views.py
  geonode/settings.py
  geonode/social/tests.py
  geonode/utils.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8769 [Backport to 3.2.x][Fixes #8760] Support Basic Auth for proxied…
  geonode/base/auth.py
  geonode/documents/tests.py
  geonode/geoserver/tests/integration.py
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/urls.py
  geonode/geoserver/views.py
  geonode/people/tests.py
  geonode/settings.py
  geonode/tests/csw.py
  geonode/utils.py
Labels: cla-signed

#8739 [Fixes #8690 #8689] Port issue #8690 and #8689 on Master
  geonode/api/resourcebase_api.py
  geonode/api/tests.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/forms.py
  geonode/base/migrations/0062_resourcebase_extra_metadata.py
  geonode/base/migrations/0063_auto_20220128_1042.py
  geonode/base/migrations/0064_resourcebase_metadata.py
  geonode/base/migrations/0076_merge_20220204_1339.py
  geonode/base/migrations/0077_merge_20220204_1347.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/base/utils.py
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/tests.py
  geonode/documents/views.py
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoapps/tests.py
  geonode/geoapps/views.py
  geonode/layers/templates/layouts/panels.html
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/tests.py
  geonode/maps/views.py
  geonode/resource/manager.py
  geonode/resource/utils.py
  geonode/settings.py
  geonode/templates/metadata_form_js.html
  requirements.txt
  setup.cfg
Labels: cla-signed

#8774 [Fixes #8772] Previous owner is assigned to the cloned resource, instead of the user that performed the clone operation
  geonode/base/api/tests.py
  geonode/resource/manager.py
Labels: cla-signed

#8781 [Fixes #8780] Thumbnail is not created when createing a new dataset
  geonode/geoserver/createlayer/utils.py
Labels: cla-signed

#8775 [Fixes #8719] Configure specific labels for document permissions
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/forms.py
  geonode/base/models.py
  geonode/documents/models.py
  geonode/security/permissions.py
  geonode/settings.py
  geonode/upload/data_retriever.py
Labels: cla-signed

#8763 [Fixes #8762] Drop legacy dataset upload page and implement client upload url hookset
  geonode/client/hooksets.py
  geonode/client/templatetags/client_lib_tags.py
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/people/templates/people/profile_detail.html
  geonode/security/tests.py
  geonode/templates/500.html
  geonode/templates/base.html
  geonode/templates/index.html
  geonode/upload/templates/upload/dataset_upload.html
  geonode/upload/templates/upload/dataset_upload_crs.html
  geonode/upload/templates/upload/dataset_upload_csv.html
  geonode/upload/templates/upload/dataset_upload_invalid.html
  geonode/upload/templates/upload/dataset_upload_time.html
  geonode/upload/templates/upload/no_upload.html
  geonode/upload/views.py
Labels: cla-signed

#8783 [Fixes #8779] Unable to favorite geostories and dashboards
  geonode/favorite/models.py
Labels: cla-signed, master

#8794 [Fixes #8793] Add is_copyable property to the resource
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/models.py
Labels: cla-signed, master

#8777 Correctly assign a user when creating a new upload session.
  geonode/layers/utils.py
Labels: cla-signed

#8796 [Fixes #8795] Make resourcese API only returned unfinished executions and only for the current user
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
Labels: cla-signed

#8770 [Fixes #8737] Errors in devcontainer and docker
  .devcontainer/.env
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  entrypoint.sh
Labels: cla-signed, backport 3.3.x

#8809 [Fixes #8808] Order execution requests by last_updated
  geonode/base/api/serializers.py
Labels: cla-signed

#8776 [3.3.x][Fixes #8667] Implement the upload of files from remote locations
  geonode/base/migrations/0065_auto_20220217_1117.py
  geonode/base/models.py
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/settings.py
  geonode/thumbs/background.py
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
  geonode/upload/admin.py
  geonode/upload/api/tests.py
  geonode/upload/api/views.py
  geonode/upload/data_retriever.py
  geonode/upload/forms.py
  geonode/upload/migrations/0033_upload_store_spatial_files.py
  geonode/upload/models.py
  geonode/upload/upload.py
  geonode/upload/upload_validators.py
  geonode/upload/utils.py
  geonode/upload/views.py
  geonode/utils.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#8816 [Fixes #8782] Expose download links on API v2
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/documents/models.py
  geonode/geoserver/helpers.py
  geonode/geoserver/templates/geoserver/dataset_download.xml
  geonode/layers/models.py
  geonode/layers/tests.py
  geonode/layers/urls.py
  geonode/layers/views.py
Labels: cla-signed

#8807 [Fixes #8687] Simplify Upload Size Limiting setup
  .env_dev
  .env_test
  geonode/base/api/tests.py
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/settings.py
  geonode/upload/admin.py
  geonode/upload/api/serializers.py
  geonode/upload/api/tests.py
  geonode/upload/forms.py
  geonode/upload/migrations/0034_uploadsizelimit.py
  geonode/upload/models.py
  geonode/upload/tests/integration.py
  geonode/upload/uploadhandler.py
Labels: cla-signed, backport 3.3.x

#8821 [Fixes #8820] Exclude anonymous user from execution requests retrieval
  geonode/base/api/serializers.py
  geonode/upload/api/serializers.py
Labels: cla-signed

#8826 [Fixes #8813] Total in responsible facet for Apps and layers does not…
  geonode/api/api.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8825 [Fixes #8824] Fix error management for direct downloads
  geonode/geoserver/templates/geoserver/dataset_download.xml
  geonode/layers/tests.py
  geonode/layers/views.py
Labels: cla-signed

#8828 [Backport #8687] Simplify Upload Size Limiting setup
  .env_dev
  .env_test
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/settings.py
  geonode/upload/admin.py
  geonode/upload/api/serializers.py
  geonode/upload/api/tests.py
  geonode/upload/forms.py
  geonode/upload/migrations/0032_uploadsizelimit.py
  geonode/upload/models.py
  geonode/upload/tests/integration.py
  geonode/upload/uploadhandler.py
Labels: cla-signed

#8500 Update django.po
  geonode/locale/el/LC_MESSAGES/django.po
Labels: translations

#8812 [Fixes #8736] Align importlayers command to the new upload interface
  geonode/geoserver/management/commands/importlayers.py
  geonode/upload/api/tests.py
  geonode/upload/api/views.py
Labels: cla-signed

#8843 [Fixes #8842] Remote Services default links are not updated anymore, …
  geonode/geoserver/helpers.py
  geonode/geoserver/manager.py
  geonode/services/migrations/0048_service_harvester.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
Labels: cla-signed

#8815 [3.3.x][Fixes #8736] Align importlayers command to the new upload interface
  geonode/layers/management/commands/importlayers.py
  geonode/tests/csw.py
  geonode/upload/api/tests.py
  geonode/upload/api/views.py
  geonode/upload/utils.py
  pavement.py
Labels: cla-signed

#8840 [Fixes #8786] Drop legacy document upload page
  geonode/documents/templates/documents/document_upload.html
  geonode/documents/tests.py
  geonode/documents/views.py
Labels: cla-signed, master

#8846 [Backport to 3.3.x][Fixes #8844] Typo in valid user invite submission…
  geonode/invitations/views.py
  geonode/locale/af/LC_MESSAGES/django.po
  geonode/locale/al/LC_MESSAGES/django.po
  geonode/locale/am/LC_MESSAGES/django.po
  geonode/locale/ar/LC_MESSAGES/django.mo
  geonode/locale/ar/LC_MESSAGES/django.po
  geonode/locale/bg_BG/LC_MESSAGES/django.po
  geonode/locale/bn/LC_MESSAGES/django.po
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
  geonode/locale/el/LC_MESSAGES/django.mo
  geonode/locale/el/LC_MESSAGES/django.po
  geonode/locale/en/LC_MESSAGES/django.mo
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/django.mo
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/fa/LC_MESSAGES/django.po
  geonode/locale/fa_IR/LC_MESSAGES/django.po
  geonode/locale/fi/LC_MESSAGES/django.po
  geonode/locale/fil/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.mo
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/hu/LC_MESSAGES/django.po
  geonode/locale/id/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/locale/ja/LC_MESSAGES/django.po
  geonode/locale/ka/LC_MESSAGES/django.po
  geonode/locale/km/LC_MESSAGES/django.po
  geonode/locale/ko/LC_MESSAGES/django.po
  geonode/locale/lt/LC_MESSAGES/django.po
  geonode/locale/ne/LC_MESSAGES/django.po
  geonode/locale/nl_NL/LC_MESSAGES/django.po
  geonode/locale/no/LC_MESSAGES/django.po
  geonode/locale/pl/LC_MESSAGES/django.mo
  geonode/locale/pl/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/django.mo
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.mo
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/locale/ro/LC_MESSAGES/django.po
  geonode/locale/ru/LC_MESSAGES/django.po
  geonode/locale/si/LC_MESSAGES/django.po
  geonode/locale/sk/LC_MESSAGES/django.po
  geonode/locale/sq/LC_MESSAGES/django.po
  geonode/locale/sv/LC_MESSAGES/django.po
  geonode/locale/sw/LC_MESSAGES/django.po
  geonode/locale/ta/LC_MESSAGES/django.po
  geonode/locale/th/LC_MESSAGES/django.po
  geonode/locale/tl/LC_MESSAGES/django.po
  geonode/locale/uk/LC_MESSAGES/django.po
  geonode/locale/vi/LC_MESSAGES/django.po
  geonode/locale/zh/LC_MESSAGES/django.po
  test_dev.sh
Labels: cla-signed

#8847 [Backport to 3.2.x][Fixes #8844] Typo in valid user invite submission…
  geonode/invitations/views.py
  geonode/locale/af/LC_MESSAGES/django.po
  geonode/locale/al/LC_MESSAGES/django.po
  geonode/locale/am/LC_MESSAGES/django.po
  geonode/locale/ar/LC_MESSAGES/django.mo
  geonode/locale/ar/LC_MESSAGES/django.po
  geonode/locale/bg_BG/LC_MESSAGES/django.po
  geonode/locale/bn/LC_MESSAGES/django.po
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
  geonode/locale/el/LC_MESSAGES/django.mo
  geonode/locale/el/LC_MESSAGES/django.po
  geonode/locale/en/LC_MESSAGES/django.mo
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/es/LC_MESSAGES/django.mo
  geonode/locale/es/LC_MESSAGES/django.po
  geonode/locale/fa/LC_MESSAGES/django.po
  geonode/locale/fa_IR/LC_MESSAGES/django.po
  geonode/locale/fi/LC_MESSAGES/django.po
  geonode/locale/fil/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.mo
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/hu/LC_MESSAGES/django.po
  geonode/locale/id/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/locale/ja/LC_MESSAGES/django.po
  geonode/locale/ka/LC_MESSAGES/django.po
  geonode/locale/km/LC_MESSAGES/django.po
  geonode/locale/ko/LC_MESSAGES/django.po
  geonode/locale/lt/LC_MESSAGES/django.po
  geonode/locale/ne/LC_MESSAGES/django.po
  geonode/locale/nl_NL/LC_MESSAGES/django.po
  geonode/locale/no/LC_MESSAGES/django.po
  geonode/locale/pl/LC_MESSAGES/django.mo
  geonode/locale/pl/LC_MESSAGES/django.po
  geonode/locale/pt/LC_MESSAGES/django.mo
  geonode/locale/pt/LC_MESSAGES/django.po
  geonode/locale/pt_BR/LC_MESSAGES/django.mo
  geonode/locale/pt_BR/LC_MESSAGES/django.po
  geonode/locale/ro/LC_MESSAGES/django.po
  geonode/locale/ru/LC_MESSAGES/django.po
  geonode/locale/si/LC_MESSAGES/django.po
  geonode/locale/sk/LC_MESSAGES/django.po
  geonode/locale/sq/LC_MESSAGES/django.po
  geonode/locale/sv/LC_MESSAGES/django.po
  geonode/locale/sw/LC_MESSAGES/django.po
  geonode/locale/ta/LC_MESSAGES/django.po
  geonode/locale/th/LC_MESSAGES/django.po
  geonode/locale/tl/LC_MESSAGES/django.po
  geonode/locale/uk/LC_MESSAGES/django.po
  geonode/locale/vi/LC_MESSAGES/django.po
  geonode/locale/zh/LC_MESSAGES/django.po
Labels: cla-signed

#8852 fix typo in file_fields
  geonode/upload/forms.py
Labels: cla-signed

#8851 Fix typo
  geonode/upload/forms.py
Labels: cla-signed

#8859 [Fixes #8858] Support "workspaced" requests on GeoServer proxy view
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/views.py
Labels: cla-signed, backport 3.2.x, backport 3.3.x

#8860 [Backport to 3.3.x][Fixes #8858] Support "workspaced" requests on GeoServer proxy view
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/views.py
Labels: cla-signed

#8861 [Backport to 3.2.x][Fixes #8858] Support "workspaced" requests on GeoServer proxy view
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/views.py
Labels: cla-signed

#8856 [Fixes #8855] Plugged service type are ignored in the model validation
  geonode/base/migrations/0066_auto_20220223_1548.py
  geonode/base/models.py
  geonode/layers/migrations/0035_auto_20220223_1547.py
  geonode/layers/models.py
  geonode/services/enumerations.py
  geonode/services/forms.py
  geonode/services/migrations/0047_auto_20220225_0945.py
  geonode/services/models.py
  geonode/services/serviceprocessors/__init__.py
  geonode/services/serviceprocessors/handler.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/tests.py
  test_dev.sh
Labels: cla-signed

#8863 [Fixes #8855] Plugged service type are ignored in the model validation
  geonode/base/migrations/0079_alter_resourcebase_alternate.py
  geonode/base/models.py
  geonode/geoserver/helpers.py
  geonode/layers/enumerations.py
  geonode/layers/migrations/0043_auto_20220225_1605.py
  geonode/layers/models.py
  geonode/resource/manager.py
  geonode/resource/utils.py
  geonode/services/enumerations.py
  geonode/services/forms.py
  geonode/services/migrations/0054_alter_service_type.py
  geonode/services/models.py
  geonode/services/serviceprocessors/__init__.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/base.py
  geonode/services/serviceprocessors/handler.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/tests.py
  geonode/utils.py
  test_dev.sh
Labels: cla-signed
