Repository GeoNode/geonode, pull requests merged in 2023-02, with the labels that each got.

#10592 [Fixes #10521] Make metadata wizard more flexible for custom metadata
  geonode/documents/api/serializers.py
  geonode/documents/api/tests.py
  geonode/documents/templates/documents/document_metadata.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/views.py
  geonode/geoapps/api/serializers.py
  geonode/geoapps/api/tests.py
  geonode/geoapps/templates/apps/app_metadata.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoapps/views.py
  geonode/layers/api/serializers.py
  geonode/layers/api/tests.py
  geonode/layers/templates/datasets/dataset_metadata.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/views.py
  geonode/maps/api/serializers.py
  geonode/maps/api/tests.py
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_metadata.html
  geonode/maps/views.py
  geonode/templates/metadata_detail.html
Labels: cla-signed, backport 4.1.x

#10665 [Dependencies] align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: dependencies, cla-signed, backport 4.1.x

#10674 [Fixes #10675] Set RabbitMQ native expiration property on the message queues
  geonode/base/api/views.py
  geonode/base/views.py
  geonode/br/management/commands/restore.py
  geonode/br/tasks.py
  geonode/documents/tasks.py
  geonode/geoserver/manager.py
  geonode/geoserver/signals.py
  geonode/geoserver/tasks.py
  geonode/harvesting/api/serializers.py
  geonode/harvesting/models.py
  geonode/harvesting/tasks.py
  geonode/layers/tasks.py
  geonode/monitoring/tasks.py
  geonode/monitoring/tests/integration.py
  geonode/notifications_helper.py
  geonode/resource/api/tasks.py
  geonode/services/serviceprocessors/base.py
  geonode/tasks/tasks.py
  geonode/upload/tasks.py
Labels: feature, cla-signed, backport 4.1.x

#10681 [Hardening] Make sure we resolve a Dataset even if more Services have…
  geonode/layers/views.py
  geonode/resource/utils.py
Labels: minor, cla-signed, backport 4.1.x

#10686 [4.0.x] Bump GeoServer to version 2.20.7
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose-test.yml
  docker-compose.yml
Labels: docker, dependencies, security, cla-signed, geoserver

#10687 Bump to release 4.0.3
  CHANGELOG.md
  geonode/__init__.py
  requirements.txt
Labels: cla-signed

#10689 [Dependencies] Align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.1.x

#10692 [Fixes #10615] Implement fallback language for PyCSW to avoid warnings
  geonode/settings.py
Labels: cla-signed, backport 4.1.x

#10706 [Fixes #0705]Log missing download url as INFO
  geonode/layers/models.py
Labels: cla-signed, backport 4.1.x

#10691 [Fixes #9879] LANGUAGE example is not valid and results in broken home page
  .env
  geonode/settings.py
Labels: cla-signed, backport 4.1.x
