Repository GeoNode/geonode, pull requests merged in 2023-08, with the labels that each got.

#11313 [Fixes #11312] Expose dataset ows url
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_helpers.py
  geonode/layers/api/serializers.py
  geonode/layers/models.py
Labels: cla-signed, backport 4.1.x

#11315 [Backport 4.1.x] [Fixes #11080] Unable to add ArcGIS REST ImageServer as Remote Servic…
  geonode/harvesting/harvesters/arcgis.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#11324 [Fixes #11323] Align the Position labels and translations
  geonode/locale/en/LC_MESSAGES/django.mo
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/people/templates/people/profile_detail.html
Labels: cla-signed, backport 4.1.x

#11334 [Fixes #11333] Backport monitoring disabled
  .env
Labels: cla-signed

#11343 [Fixes #11342] use bracket notation inside the default feature template
  geonode/layers/api/serializers.py
Labels: cla-signed, master, backport 4.1.x

#11341 [Fixes #11251] Extend MapLayer model with visualization properties
  geonode/maps/api/serializers.py
  geonode/maps/api/tests.py
  geonode/maps/migrations/0043_auto_20230807_1234.py
  geonode/maps/models.py
Labels: cla-signed

#11351 [Fixes #11350] Fix tests for layer featureinfo template
  geonode/layers/api/tests.py
Labels: cla-signed, backport 4.1.x

#11353 Bump to 4.1.1
  geonode/__init__.py
  requirements.txt
Labels: cla-signed

#11355 changelog and fixes for packaging
  CHANGELOG.md
  setup.cfg
  setup.py
Labels: cla-signed

#11354 Bump to dev versions
  geonode/__init__.py
  requirements.txt
Labels: cla-signed

#11359 Bump version
  geonode/__init__.py
  setup.cfg
Labels: cla-signed

#11369 [Fixes #11368] Fix spatial representation type parsing
  geonode/base/fixtures/test_xml.xml
  geonode/catalogue/templates/catalogue/full_metadata.xml
  geonode/layers/metadata.py
  geonode/layers/tests.py
  geonode/resource/utils.py
Labels: cla-signed, backport 4.1.x

#11371 Bump to 4.1.2
  CHANGELOG.md
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#11321 [Fixes #11320] API V1 delivers information on users that shouldn't be…
  geonode/api/api.py
  geonode/api/tests.py
Labels: cla-signed, backport 4.1.x

#11298 Fixes #11296 Implement custom download URLs
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/resource/download_handler.py
  geonode/settings.py
  geonode/tests/smoke.py
Labels: cla-signed, backport 4.1.x

#11382 [Fixes #11383] Remove explicit dependency from wandb
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed

#11395 [Fixes #11394] Enable IFC format
  geonode/settings.py
Labels: cla-signed

#11385 [Fixes #11347] Import resources page displays service name instead of title
  geonode/services/templates/services/service_detail.html
  geonode/services/templates/services/service_remove.html
  geonode/services/templates/services/service_resources_harvest.html
  geonode/services/views.py
Labels: enhancement

#11363 [Fixes #11357] Remove legacy upload code code quality
  geonode/geoserver/context_processors.py
  geonode/upload/__init__.py
  geonode/upload/api/views.py
  geonode/upload/forms.py
  geonode/upload/tasks.py
  geonode/upload/tests/test_upload_preprocessing.py
  geonode/upload/upload.py
  geonode/upload/upload_preprocessing.py
  geonode/upload/urls.py
  geonode/upload/utils.py
  geonode/upload/views.py
Labels: cla-signed

#11319 [Fixes #11316] external pyCSW Service breaks upload of Documents and Datasets
  geonode/catalogue/backends/generic.py
Labels: minor, cla-signed

#11407 create-envfile doesn't need Django
  README.md
Labels: cla-signed

#11297 [Fixes #11226] Faceting: improvement: key to filter - step 2
  geonode/facets/models.py
  geonode/facets/providers/baseinfo.py
  geonode/facets/providers/category.py
  geonode/facets/providers/keyword.py
  geonode/facets/providers/region.py
  geonode/facets/providers/thesaurus.py
  geonode/facets/providers/users.py
  geonode/facets/tests.py
Labels: cla-signed, master

#11408 Remove Install paragraph from README
  README.md
Labels: cla-signed

#11409 Update link to demo in README
  README.md
Labels: cla-signed

#10843 [Fixes: #10841] Serializing and deserializing ResourceBase and Dataset objects breaks validation check
  geonode/base/api/fields.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
Labels: cla-signed, backport 4.0.x, backport 4.1.x

#11411 Typos and fixes to the links in the README
  README.md
Labels: cla-signed

#11426 Update settings_docker_sample.ini
  geonode/br/management/commands/settings_docker_sample.ini
  geonode/br/management/commands/settings_sample.ini
Labels: cla-signed
