Repository GeoNode/geonode, pull requests merged in 2023-04, with the labels that each got.

#10860 [Snyk] Security upgrade alpine from 3.14 to 3.16
  scripts/docker/letsencrypt/Dockerfile
Labels: docker, dependencies, security, cla-signed, backport 4.1.x

#10903 [Fixes #10887] Fix test request
  geonode/geoserver/tests/test_helpers.py
Labels: cla-signed, backport 4.0.x, backport 4.1.x

#10908 [Fixes #10907] Bump to Geoserver 2.23.0
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose-test.yml
  docker-compose.yml
Labels: cla-signed, backport 4.1.x

#10926 [Fixes #10925] Fix default value for crop widget thumbnail prefetch
  geonode/documents/templates/layouts/doc_panels.html
Labels: cla-signed, backport 4.0.x, backport 4.1.x

#10930 Revert "Bump owslib from 0.28.1 to 0.29.1"
  requirements.txt
Labels: dependencies, cla-signed, backport 4.1.x

#10941 [Fixes #10936] Implement a generic API endpoint for linked resources
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#10934 [Dependencies] align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.1.x

#10906 [Fixes #10859] Deadlock in HierarchicalTagManager when creating tags
  geonode/base/models.py
  geonode/base/tests.py
Labels: cla-signed, backport 4.0.x, backport 4.1.x

#10948 [Fixes #10947] Update Docker image from debian to ubuntu 22.04
  Dockerfile
  geonode/thumbs/tests/test_unit.py
Labels: cla-signed

#10962 [Fixes #19061] Time serie date field not recognized
  geonode/geoserver/helpers.py
  geonode/layers/forms.py
  geonode/layers/tests.py
  geonode/layers/views.py
Labels: cla-signed, backport 4.1.x

#10974 [Dependencies] Align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed

#10979 [Fixes #10978] Page size in linked_resources raise an issue
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed
