Repository GeoNode/geonode, pull requests merged in 2023-09, with the labels that each got.

#11362 [Fixes #11335] Hookable logic for the automatic assignment of regions
  geonode/base/tests.py
  geonode/resource/manager.py
  geonode/resource/regions_storer.py
  geonode/resource/utils.py
  geonode/settings.py
  geonode/tests/smoke.py
Labels: cla-signed

#11423 [Fixes #11421] Improvements for DownloadHandler
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/documents/models.py
  geonode/documents/tests.py
  geonode/geoserver/tests/test_server.py
  geonode/layers/api/tests.py
  geonode/layers/download_handler.py
  geonode/layers/models.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/security/permissions.py
  geonode/security/tests.py
  geonode/settings.py
  geonode/tests/smoke.py
  geonode/utils.py
Labels: cla-signed

#11459 Add args and kwargs in resources API
  geonode/base/api/views.py
  geonode/documents/api/views.py
  geonode/layers/api/views.py
  geonode/maps/api/views.py
Labels: cla-signed

#11462 Update .clabot with Francisco Vicent
  .clabot
Labels: cla-signed

#11433 [Fixes #11381] Remove `ProfileCreationForm.clean_username()`
  geonode/people/forms.py
Labels: cla-signed, enhancement, master

#8818 Add own service for memcached
  .env.sample
  .env_dev
  .env_local
  .env_test
  docker-compose-test.yml
  docker-compose.yml
  entrypoint.sh
  scripts/docker/base/ubuntu/Dockerfile
Labels: cla-signed

#11443 [Fixes #11349] Keep into account maplayers visibility and order when …
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#11481 [Fixes #11480] Discard alpha channel from thumbnail mask
  geonode/thumbs/thumbnails.py
Labels: cla-signed

#11431 [Fixes #11430] Improve metadata template
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
Labels: cla-signed, enhancement

#11442 [Fixes #11441]Implement the update of the spatial extent for non-spat…
  geonode/base/api/exceptions.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/models.py
  geonode/base/populate_test_data.py
  geonode/documents/api/tests.py
  geonode/geoapps/api/tests.py
  geonode/security/utils.py
  geonode/utils.py
Labels: cla-signed

#11486 [Backport 4.1.x] SSRF Bypass to return internal host data
  .env_test
  geonode/proxy/tests.py
  geonode/proxy/views.py
  geonode/utils.py
Labels: security, cla-signed, 4.1.x

#11489 [Fixes #11430] Improve metadata template for geoapp
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
Labels: cla-signed, backport 4.1.x

#11495 Update .env_test
  .env_test
Labels: cla-signed, backport 4.1.x

#11493 [Fixes #11491 abd #11492] Fix alpha blending and remote layers in thumbnails
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
Labels: cla-signed, enhancement

#11500 [Snyk] Security upgrade nginx from 1.25.1-alpine to 1.25.2-alpine
  scripts/docker/nginx/Dockerfile
Labels: cla-signed

#11508 Fix client and importer versions for 4.1.3
  requirements.txt
  setup.cfg
Labels: cla-signed

#11498 [Fixes #11497] Dehydrate `organization` field
  geonode/api/api.py
Labels: cla-signed

#11531 [Fixes #11487] Revert to Ubuntu 22.04 LTS
  Dockerfile
  docker-compose-test.yml
  docker-compose.yml
  scripts/docker/base/ubuntu/Dockerfile
Labels: cla-signed

#11536 [Fixes #11535] Return category description in API response
  geonode/base/api/serializers.py
Labels: cla-signed, enhancement

#11537 [Fixes #11533] Remote resources created by harvesters do not have remote subtype
  geonode/harvesting/harvesters/base.py
  geonode/harvesting/harvesters/geonodeharvester.py
  geonode/harvesting/tests/test_integrations.py
  geonode/resource/utils.py
Labels: cla-signed
