Repository GeoNode/geonode, pull requests merged in 2023-06, with the labels that each got.

#11136 Revert "[Fixes #11100] Bump to Geoserver 2.23.1 (#11104) (#11107)"
  dev_config.yml
  docker-compose-geoserver-server.yml
  docker-compose-test.yml
  docker-compose.yml
Labels: cla-signed

#11148 [Fixes #11147] Strip port from visitor_ip_address
  geonode/base/auth.py
Labels: cla-signed, backport 4.1.x

#11151 Track client and importer development packages
  requirements.txt
  setup.cfg
Labels: cla-signed

#11167 Fix region intersection test
  geonode/base/fixtures/regions.json
  geonode/resource/utils.py
Labels: cla-signed, backport 4.1.x

#11189 [Fixes #11188] Make keywords optional when editing a resource with th…
  geonode/base/admin.py
Labels: cla-signed, 4.1.x

#11138 [Snyk] Security upgrade cryptography from 40.0.2 to 41.0.0
  requirements.txt
Labels: dependencies, security, cla-signed

#11165 Direct download on preview on dataset list is not working #11156
  geonode/layers/tests.py
  geonode/utils.py
Labels: cla-signed, backport 4.1.x

#11205 [Fixes #11102] Faceting: prefiltering
  geonode/base/api/filters.py
  geonode/facets/tests.py
  geonode/facets/views.py
Labels: cla-signed
