Repository GeoNode/geonode, pull requests merged in 2023-07, with the labels that each got.

#11223 [Snyk] Security upgrade ubuntu from 22.04 to 22.10
  Dockerfile
Labels: docker, security, cla-signed

#11232 [Fixes #11230] Split and tag base Docker image
  Dockerfile
  scripts/docker/base/ubuntu/Dockerfile
Labels: cla-signed

#11231 [Fixes #11101] Faceting: keywords
  geonode/facets/models.py
  geonode/facets/providers/keyword.py
  geonode/facets/tests.py
  geonode/settings.py
Labels: cla-signed

#11218 GNIP 94: Generic and pluggable OIDC SocialAccount Provider for GeoNode
  .circleci/config.yml
  .env_test
  geonode/groups/models.py
  geonode/messaging/notifications.py
  geonode/people/adapters.py
  geonode/people/profileextractors.py
  geonode/people/socialaccount/__init__.py
  geonode/people/socialaccount/providers/__init__.py
  geonode/people/socialaccount/providers/geonode_openid_connect/__init__.py
  geonode/people/socialaccount/providers/geonode_openid_connect/provider.py
  geonode/people/socialaccount/providers/geonode_openid_connect/tests.py
  geonode/people/socialaccount/providers/geonode_openid_connect/urls.py
  geonode/people/socialaccount/providers/geonode_openid_connect/views.py
  geonode/settings.py
  geonode/utils.py
  pavement.py
Labels: gnip, security, cla-signed

#11236 Faceting : #11226 key to filter - step 1 + #11233 configuration
  geonode/facets/models.py
  geonode/facets/providers/baseinfo.py
  geonode/facets/providers/category.py
  geonode/facets/providers/keyword.py
  geonode/facets/providers/region.py
  geonode/facets/providers/thesaurus.py
  geonode/facets/providers/users.py
  geonode/facets/tests.py
  geonode/facets/views.py
  geonode/settings.py
Labels: cla-signed, master

#11247 [Fixes #11246] Create thumbnails for remote documents
  geonode/documents/models.py
  geonode/documents/tasks.py
  geonode/documents/tests.py
  geonode/resource/manager.py
  geonode/storage/manager.py
Labels: cla-signed

#11250 [Fixes #11249] Mark remote documents with sourcetype REMOTE
  geonode/documents/api/tests.py
  geonode/documents/api/views.py
  geonode/documents/tests.py
  geonode/documents/views.py
Labels: cla-signed

#11257 [Fixes #11256] Assign regions based on contains and overlaps
  geonode/base/models.py
  geonode/base/tests.py
  geonode/resource/utils.py
Labels: cla-signed

#11260 [Fixes #11259] Faceting: fixes
  geonode/facets/providers/keyword.py
  geonode/facets/providers/users.py
Labels: cla-signed, master

#11274 [Fixes #11273] Faceting: /facets loses some filters along the way
  geonode/facets/tests.py
  geonode/facets/views.py
Labels: cla-signed

#11283 [Fixes #11225] Italian translations aren't built with the latest fixes
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
Labels: cla-signed, 4.1.x, backport 4.1.x

#11291 [Fixes #11265] Change the WMS URL to a more generic OWS URL
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_helpers.py
Labels: cla-signed, 4.1.x

#11275 [Fixes #11262] Faceting: improvement: include count 0 topics
  geonode/facets/models.py
  geonode/facets/providers/baseinfo.py
  geonode/facets/providers/category.py
  geonode/facets/providers/keyword.py
  geonode/facets/providers/region.py
  geonode/facets/providers/thesaurus.py
  geonode/facets/providers/users.py
  geonode/facets/tests.py
  geonode/facets/views.py
Labels: cla-signed

#11199 - Updating docker-compose tags, images versions and .envs - Bump Po…
  .env
  .env_dev
  .env_local
  .env_test
  docker-compose.yml
  scripts/docker/base/ubuntu/Dockerfile
  scripts/docker/letsencrypt/Dockerfile
  scripts/docker/nginx/Dockerfile
  start_django_async.sh
Labels: docker, security, cla-signed, enhancement

#11309 [Fixes #11080] Unable to add ArcGIS REST ImageServer as Remote Service
  geonode/harvesting/harvesters/arcgis.py
  requirements.txt
  setup.cfg
Labels: cla-signed
