Repository GeoNode/geonode, pull requests merged in 2023-01, with the labels that each got.

#10473 [Fixes #10472] Fix code scanning alert - Polynomial regular expression used on uncontrolled data
  .github/workflows/pyre.yml
  .github/workflows/pysa.yml
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_helpers.py
  geonode/geoserver/views.py
Labels: cla-signed, backport 4.1.x

#10507 [Dependencies] Align "setup.cfg" to "requirements.txt"
  .github/workflows/codeql-analysis.yml
  .github/workflows/codeql.yml
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.1.x

#10510 [Fixes #10509] Configure UTF-8 encoding for shapefiles in Geoserver by default
  .devcontainer/.env
  .env
  .env_dev
  .env_local
  .env_test
Labels: cla-signed, backport 4.1.x

#10511 [Backport to 4.1.x][Fixes #10509] Configure UTF-8 encoding for shapef…
  .devcontainer/.env
  .env
  .env_dev
  .env_local
  .env_test
Labels: cla-signed

#10488 Fix ISO 19139 metadata validity
  geonode/catalogue/templates/catalogue/full_metadata.xml
Labels: cla-signed

#10544 [Fixes #10524] Resource permissions are not returned in the users/groups endpoint
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed, backport 4.1.x

#10483 [Fixes #10482] Upload ISO-19115 xml metadata via the API
  geonode/layers/api/exceptions.py
  geonode/layers/api/serializers.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
Labels: cla-signed, backport 4.1.x

#10526 [Fixes #10525] set/unset batch permissions on groups raise an error
  geonode/layers/tests.py
  geonode/layers/utils.py
Labels: cla-signed, backport 4.1.x

#10538 [Fixes #10537] Improve rules creation using GeoFence batch
  geonode/base/api/tests.py
  geonode/br/management/commands/restore.py
  geonode/geoserver/geofence.py
  geonode/geoserver/helpers.py
  geonode/geoserver/security.py
  geonode/layers/tests.py
  geonode/security/tests.py
  geonode/utils.py
Labels: cla-signed, backport 4.1.x

#10572 [Dependencies] Align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: dependencies, cla-signed, backport 4.1.x

#10577 [Backport 4.1.x] bbox_polygon & ll_bbox_polygon should be read-only in serializer
  geonode/base/api/serializers.py
Labels: cla-signed

#10580 [Dependencies] Bump black to version 22.12.0
  requirements.txt
Labels: dependencies, cla-signed, backport 4.1.x

#10582 [Code Formatting] Applying black to root files
  pavement.py
  setup.py
  tasks.py
Labels: cla-signed, code quality, backport 4.1.x

#10585 [Fixes #10537] Improve rules creation using GeoFence batch - more imp…
  geonode/api/tests.py
  geonode/geoserver/geofence.py
  geonode/geoserver/helpers.py
  geonode/geoserver/manager.py
  geonode/geoserver/security.py
  geonode/local_settings.py.geoserver.sample
  geonode/security/tests.py
  geonode/settings.py
  geonode/upload/tests/integration.py
  geonode/utils.py
Labels: cla-signed

#10589 [Code Format] Minor refactoring of geofence create options
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/utils.py
Labels: cla-signed, code quality, backport 4.1.x

#10597 Add black geonode to the requested QA xchecks
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed, backport 4.1.x

#10602 Monitoring frontend bundle update
  geonode/monitoring/static/monitoring/bundle.js
Labels: cla-signed, frontend, javascript, backport 4.1.x

#10623 [Dependencies] Align "setup.cfg" to "requirements.txt"
  setup.cfg
Labels: dependencies, cla-signed, backport 4.1.x
