Repository GeoNode/geonode, pull requests merged in 2023-10, with the labels that each got.

#11560 Test fix CircleCi test
  geonode/upload/api/tests.py
Labels: cla-signed

#11555 [Fixes #11554] Implement WMTS backgrounds for thumbnails (only 3857 tilematricsets)
  geonode/thumbs/background.py
  geonode/thumbs/tests/expected_results/tiles/background.png
  geonode/thumbs/tests/expected_results/tiles/wmts_7_5_4.png
  geonode/thumbs/tests/expected_results/tiles/wmts_7_6_4.png
  geonode/thumbs/tests/expected_results/tiles/wmts_8_5_4.png
  geonode/thumbs/tests/expected_results/tiles/wmts_8_6_4.png
  geonode/thumbs/tests/expected_results/tiles/wmts_9_5_4.png
  geonode/thumbs/tests/expected_results/tiles/wmts_9_6_4.png
  geonode/thumbs/tests/test_backgrounds.py
Labels: cla-signed

#11558 [Snyk] Security upgrade urllib3 from 1.26.15 to 1.26.17
  requirements.txt
Labels: cla-signed

#11563 [Snyk] Security upgrade django from 3.2.21 to 3.2.22
  requirements.txt
  setup.cfg
Labels: dependencies, security, cla-signed

#11557 adding hostname to celery state db
  celery-cmd
Labels: cla-signed

#11564 Fix requires bucket name for AWS tests
  geonode/storage/tests.py
Labels: cla-signed, master

#11567 issue#11566_pre-commit_hook_black_isnt_working_on_Ubuntu_22_04_3
  .pre-commit-config.yaml
Labels: cla-signed

#11565 [Fixes #11494] Implement relations between resources
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/forms.py
  geonode/base/migrations/0086_linkedresource.py
  geonode/base/models.py
  geonode/documents/api/views.py
  geonode/documents/forms.py
  geonode/documents/migrations/0037_delete_documentresourcelink.py
  geonode/documents/models.py
  geonode/documents/templates/documents/document_metadata.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/tests.py
  geonode/documents/views.py
  geonode/geoapps/templates/apps/app_metadata.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoapps/views.py
  geonode/layers/models.py
  geonode/layers/templates/datasets/dataset_metadata.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/views.py
  geonode/maps/models.py
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_metadata.html
  geonode/maps/views.py
  geonode/resource/manager.py
  geonode/resource/utils.py
Labels: cla-signed

#11584 [Fixes #11579] Use autocomplete API for editing linked resources
  geonode/base/forms.py
  geonode/base/tests.py
  geonode/base/urls.py
  geonode/base/views.py
  geonode/documents/templates/documents/document_metadata.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/tests.py
  geonode/geoapps/templates/apps/app_metadata.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/layers/templates/datasets/dataset_metadata.html
  geonode/layers/templates/layouts/panels.html
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_metadata.html
Labels: cla-signed, master

#11586 [Fixes #11585] Move linked resources to the "optional metadata" tab
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/layers/templates/layouts/panels.html
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/maps/templates/layouts/map_panels.html
Labels: cla-signed

#11604 [Fixes #11601] Fix image template src reference
  geonode/layers/api/serializers.py
Labels: cla-signed

#11580 [Fixes #11574] Fix CircleCI black tests
  .circleci/config.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/flake8.yml
Labels: cla-signed

#11605 Fix black formatting
  geonode/layers/api/serializers.py
Labels: cla-signed

#10842 Enumerate unzipped files
  geonode/storage/data_retriever.py
  geonode/storage/tests.py
  geonode/storage/tests/data/example.zip
Labels: cla-signed

#11611 [Fixes #11610] Make thumbs backgrounds tests run
  geonode/thumbs/background.py
  geonode/thumbs/tests/__init__.py
  geonode/thumbs/tests/test_backgrounds.py
Labels: cla-signed

#11618 [Fixes #11617] Introduce icons for thesauri keywords
  geonode/base/migrations/0087_thesauruskeyword_icon.py
  geonode/base/models.py
  geonode/facets/providers/thesaurus.py
Labels: cla-signed

#11619 [Snyk] Security upgrade urllib3 from 1.26.17 to 1.26.18
  requirements.txt
  setup.cfg
Labels: cla-signed

#11607 [Fixes #11603] Improve codecov integration
  .circleci/config.yml
Labels: cla-signed

#11625 [Fixes #11620] Facets: refact view as a class
  geonode/facets/tests.py
  geonode/facets/urls.py
  geonode/facets/views.py
Labels: cla-signed

#11631 Makes more clear the is_enable function in themes
  geonode/themes/migrations/0015_alter_geonodethemecustomization_is_enabled.py
  geonode/themes/models.py
Labels: cla-signed

#10367 [Fixes #10290] complete ISO contact roles per ressource base with multiplicity
  geonode/base/api/serializers.py
  geonode/base/forms.py
  geonode/base/migrations/0086_linkedresource.py
  geonode/base/models.py
  geonode/base/templates/base/_resourcebase_info_panel.html
  geonode/base/templatetags/base_tags.py
  geonode/base/tests.py
  geonode/base/widgets.py
  geonode/catalogue/backends/pycsw_local_mappings.py
  geonode/catalogue/templates/catalogue/full_metadata.xml
  geonode/catalogue/templates/geonode_metadata_full.html
  geonode/catalogue/views.py
  geonode/documents/api/tests.py
  geonode/documents/migrations/0037_delete_documentresourcelink.py
  geonode/documents/templates/documents/document_metadata.html
  geonode/documents/templates/documents/document_metadata_advanced.html
  geonode/documents/templates/layouts/doc_panels.html
  geonode/documents/views.py
  geonode/geoapps/templates/apps/app_metadata.html
  geonode/geoapps/templates/apps/app_metadata_advanced.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/geoapps/views.py
  geonode/geoserver/helpers.py
  geonode/harvesting/harvesters/geonodeharvester.py
  geonode/layers/api/tests.py
  geonode/layers/templates/datasets/dataset_metadata.html
  geonode/layers/templates/datasets/dataset_metadata_advanced.html
  geonode/layers/templates/layouts/panels.html
  geonode/layers/templatetags/contact_roles.py
  geonode/layers/tests.py
  geonode/layers/views.py
  geonode/locale/de/LC_MESSAGES/django.mo
  geonode/locale/de/LC_MESSAGES/django.po
  geonode/locale/en/LC_MESSAGES/django.mo
  geonode/locale/en/LC_MESSAGES/django.po
  geonode/locale/fr/LC_MESSAGES/django.mo
  geonode/locale/fr/LC_MESSAGES/django.po
  geonode/locale/it/LC_MESSAGES/django.mo
  geonode/locale/it/LC_MESSAGES/django.po
  geonode/maps/api/tests.py
  geonode/maps/models.py
  geonode/maps/templates/layouts/map_panels.html
  geonode/maps/templates/maps/map_metadata.html
  geonode/maps/templates/maps/map_metadata_advanced.html
  geonode/maps/views.py
  geonode/people/__init__.py
  geonode/people/forms.py
  geonode/resource/utils.py
  geonode/settings.py
  geonode/templates/metadata_detail.html
Labels: cla-signed

#11624 Fixes #11578: align geoapp metadata update to other resources
  geonode/geoapps/views.py
Labels: cla-signed

#11638 Add missing init for facets module
  geonode/facets/providers/__init__.py
Labels: cla-signed, backport 4.2.x

#11644 [Fixes #11643] Thesaurus topics should only return its own keys
  geonode/facets/providers/thesaurus.py
  geonode/facets/tests.py
Labels: cla-signed
