Repository GeoNode/geonode, pull requests merged in 2023-03, with the labels that each got.

#10711 [Fixes #10710] Drop stale account settings
  .devcontainer/.env
  .env
  .env_dev
  .env_local
  .env_test
Labels: cla-signed, 4.1.x, backport 4.1.x

#10704 [Fixes #10703] Error on setting batch permissions
  geonode/base/forms.py
  geonode/base/views.py
  geonode/people/tests.py
Labels: cla-signed, backport 4.1.x

#10742 [Dependencies] Align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.1.x

#10749 Fixes for multiple migrations
  geonode/base/migrations/0067_resourcebase_storetype.py
  geonode/base/migrations/0074_drop_curated_thumbs.py
  geonode/layers/migrations/0036_remove_layer_storetype.py
  geonode/layers/migrations/0040_dataset_ows_url.py
  geonode/upload/migrations/0033_auto_20210527_1520.py
Labels: cla-signed, backport 4.1.x

#10756 [Cherry Pick #10749] Fixes for multiple migrations
  geonode/base/migrations/0067_resourcebase_storetype.py
  geonode/base/migrations/0074_drop_curated_thumbs.py
  geonode/layers/migrations/0036_remove_layer_storetype.py
  geonode/layers/migrations/0040_dataset_ows_url.py
  geonode/upload/migrations/0033_auto_20210527_1520.py
Labels: cla-signed, backport 4.1.x

#10740 [Fixes #10716] Configure user notifications off by default
  geonode/messaging/notifications.py
  geonode/settings.py
Labels: cla-signed, backport 4.1.x

#10754 [Fixes #10750] Implement custom download URLs
  geonode/documents/models.py
  geonode/documents/tests.py
  geonode/layers/models.py
  geonode/layers/tests.py
Labels: cla-signed, backport 4.0.x, backport 4.1.x

#10761 [Backport 4.0.x] [Fixes #10750] Implement custom download URLs
  geonode/documents/models.py
  geonode/documents/tests.py
  geonode/layers/models.py
  geonode/layers/tests.py
Labels: cla-signed

#10763 [Backport 4.0.x][Fixes #10615] Implement fallback language for PyCSW to avoid warnings
  geonode/settings.py
Labels: cla-signed

#10773 [Minor] Add autocomplete_fields to maps admin MapLayer datasets
  geonode/maps/admin.py
Labels: cla-signed, backport 4.1.x

#10775 [Backport to 4.0.x] - Set RabbitMQ native expiration property on the message queues (#10…
  geonode/base/api/views.py
  geonode/base/views.py
  geonode/br/management/commands/restore.py
  geonode/br/tasks.py
  geonode/documents/tasks.py
  geonode/geoserver/manager.py
  geonode/geoserver/signals.py
  geonode/geoserver/tasks.py
  geonode/harvesting/api/serializers.py
  geonode/harvesting/models.py
  geonode/harvesting/tasks.py
  geonode/layers/tasks.py
  geonode/monitoring/tasks.py
  geonode/monitoring/tests/integration.py
  geonode/notifications_helper.py
  geonode/resource/api/tasks.py
  geonode/services/serviceprocessors/base.py
  geonode/tasks/tasks.py
  geonode/upload/tasks.py
Labels: cla-signed

#10788 [Dependencies] Align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.1.x

#10789 [Backport to 4.1.x][Dependencies] Align setup.cfg to requirements.txt (#10788)
  setup.cfg
Labels: dependencies, cla-signed

#10791 [Fixes #10790] GeoNode "HttpClient" not catching the Connection Timeo…
  geonode/utils.py
Labels: cla-signed, backport 4.0.x, backport 4.1.x

#10806 [Backport to 4.0.x][Fixes #10790] GeoNode "HttpClient" not catching the Connection Timeo…
  geonode/utils.py
Labels: cla-signed

#10831 [Fixes #10830] Reset password rises 502 gatweay error if any error occurs
  geonode/people/adapters.py
Labels: cla-signed, backport 4.0.x, backport 4.1.x

#10821 [Backport to 4.0.x][Dependencies] Align setup.cfg to requirements.txt
  requirements.txt
  setup.cfg
Labels: dependencies, security, cla-signed

#10828 [Dependencies] Align setup.cfg to requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.1.x

#10837 [Fixes #10836] Use GS ows service for healthchecks
  docker-compose-test.yml
  docker-compose.yml
  tasks.py
Labels: cla-signed, backport 4.0.x, backport 4.1.x
