Repository GeoNode/geonode, pull requests merged in 2024-08, with the labels that each got.

#12471 [Fixes #12472] Importer autoregister
  geonode/settings.py
Labels: cla-signed

#12502 [Fixes #12501] Localized TKeywords are not properly parsed
  geonode/resource/utils.py
Labels: cla-signed, backport 4.3.x

#12515 [Fixes #8848] Implment can_feature, can_publish and can_approve methods
  geonode/base/views.py
  geonode/documents/views.py
  geonode/geoapps/views.py
  geonode/layers/views.py
  geonode/maps/views.py
  geonode/people/models.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed

#12527 [Fixes #12526] Expose the metadata_uploaded_preserve property over th…
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
Labels: cla-signed, API v2

#12461 [Fixes #12458] black fails on python3.10 constructs
  .github/workflows/flake8.yml
  pyproject.toml
Labels: cla-signed

#12518 [Fix #12517] Update layer to dataset for pinax notification
  geonode/templates/pinax/notifications/dataset_approved/full.txt
  geonode/templates/pinax/notifications/dataset_approved/short.txt
  geonode/templates/pinax/notifications/dataset_created/full.txt
  geonode/templates/pinax/notifications/dataset_created/short.txt
  geonode/templates/pinax/notifications/dataset_deleted/full.txt
  geonode/templates/pinax/notifications/dataset_deleted/short.txt
  geonode/templates/pinax/notifications/dataset_published/full.txt
  geonode/templates/pinax/notifications/dataset_published/short.txt
  geonode/templates/pinax/notifications/dataset_rated/full.txt
  geonode/templates/pinax/notifications/dataset_rated/short.txt
  geonode/templates/pinax/notifications/dataset_updated/full.txt
  geonode/templates/pinax/notifications/dataset_updated/short.txt
Labels: cla-signed

#12539 Update .clabot
  .clabot
Labels: cla-signed
