Repository GeoNode/geonode, pull requests merged in 2024-09, with the labels that each got.

#12550 Profile icon proportions
  geonode/static/geonode/less/base.less
Labels: cla-signed

#12554 [Fixes #12553] Remove type control from uuid url
  geonode/catalogue/urls.py
Labels: cla-signed, baclport 4.4.x

#12566 [Fixes #12553][Backport 4.4.x] The uuid direct link doesn't work if the uuid field is not a uuid value
  geonode/catalogue/urls.py
Labels: cla-signed

#12572 [Fix #12567] Duplicate "forgot password" in login page
  geonode/templates/account/login.html
Labels: cla-signed, backport 4.4.x

#12583 Reference client 4.4.x
  requirements.txt
Labels: cla-signed

#12597 [Fixes #12596] User with notification disabled still receive the noti…
  geonode/notifications_helper.py
Labels: cla-signed, backport 4.4.x

#12411 [Fixes #12326] Assets: implement migration for old uploaded files
  geonode/assets/management/__init__.py
  geonode/assets/management/commands/__init__.py
  geonode/assets/management/commands/migrate_file_to_assets.py
Labels: cla-signed

#11872 [Fixes #11703] Documents can now be uploaded without specifying title via the REST API.
  geonode/documents/api/serializers.py
  geonode/documents/api/tests.py
  geonode/documents/models.py
  geonode/resource/utils.py
Labels: cla-signed, backport 4.4.x

#12611 [Backport 4.4.x] [Fixes #12326] Assets: implement migration for old uploaded files
  geonode/assets/management/__init__.py
  geonode/assets/management/commands/__init__.py
  geonode/assets/management/commands/migrate_file_to_assets.py
Labels: cla-signed

#12613 [Fixes #12610] Metadata Wizard steps leaked inside the settings tab
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
Labels: cla-signed, backport 4.4.x

#12595 [Fixes #12594] Error when saving a new map
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/models.py
  geonode/maps/api/tests.py
  geonode/people/models.py
  geonode/security/utils.py
Labels: cla-signed
