Repository GeoNode/geonode, pull requests merged in 2024-02, with the labels that each got.

#11913 [Fixes #11912] GWC layers only cache default style after B/R restore
  geonode/br/management/commands/create_tile_layers.py
Labels: cla-signed

#11916 Align Black and Flake versions to requirements inside the github action
  .github/workflows/flake8.yml
Labels: cla-signed

#11924 Update geonode-oauth-toolkit dependency
  requirements.txt
  setup.cfg
Labels: cla-signed, master

#11926 Celery cleanup task is not running #11925
  geonode/upload/apps.py
Labels: cla-signed

#11929 Upgrade Geoserver with fix for oauth2
  docker-compose-dev.yml
  docker-compose-test.yml
  docker-compose.yml
  geonode/base/api/tests.py
  geonode/harvesting/harvesters/geonodeharvester.py
Labels: cla-signed, geoserver

#11884 [Fixes #11883] the extent values should now only include decimal separator
  geonode/catalogue/templates/catalogue/full_metadata.xml
Labels: cla-signed

#11942 [Backport 4.1.x][Fixes #11912] GWC layers only cache default style after B/R restore
  geonode/br/management/commands/create_tile_layers.py
Labels: cla-signed

#11945 Release 4.1.4
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#11927 [Fixes #11918] Implement linked_resources API creation and deletion methods
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: feature, cla-signed

#11946 [Fixes #11944] Implement filtering for linked_resources
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed, API v2

#11957 [Snyk] Fix for 2 vulnerabilities
  requirements.txt
  setup.cfg
Labels: cla-signed

#11859 [Fixes #11862] Sanitize HTML data
  geonode/base/templatetags/sanitize_html.py
  geonode/base/tests.py
  geonode/templates/metadata_detail.html
  requirements.txt
  setup.cfg
Labels: security, cla-signed, backport 4.2.x

#11958 [Fixes #11862] Sanitize HTML data
  geonode/base/templatetags/sanitize_html.py
  geonode/base/tests.py
  geonode/templates/metadata_detail.html
  requirements.txt
  setup.cfg
Labels: security, cla-signed

#11975 [Fixes #11960] NoReverseMatch at /people/edit/<username>
  geonode/base/api/tests.py
  geonode/people/templates/people/profile_edit.html
Labels: cla-signed

#11979 [Fixes #11978] Remove Bearer token parsing from userinfo
  .circleci/config.yml
  geonode/api/tests.py
  geonode/api/views.py
Labels: cla-signed

#11983 [Fixes #10880] REST API always filters dirty resources
  geonode/layers/api/permissions.py
  geonode/layers/api/tests.py
  geonode/security/utils.py
Labels: cla-signed

#11976 [Fixes #11675] Demo WMS service used in services tests returns 404
  geonode/services/test_selenium.py
  geonode/services/tests.py
Labels: cla-signed

#11994 hide resources from search and catalogue listing
  geonode/base/api/mixins.py
  geonode/base/api/views.py
  geonode/documents/api/tests.py
  geonode/documents/api/views.py
  geonode/geoapps/api/tests.py
  geonode/geoapps/api/views.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/maps/api/tests.py
  geonode/maps/api/views.py
Labels: cla-signed

#11997 [Fixes #11992] Transfer users API under people app
  geonode/base/api/urls.py
  geonode/base/api/views.py
  geonode/people/urls.py
  geonode/people/views.py
Labels: cla-signed

#11984 [Snyk] Upgrade axios from 1.6.4 to 1.6.7
  geonode/monitoring/frontend/package.json
Labels: cla-signed

#11985 [Snyk] Upgrade moment from 2.29.4 to 2.30.1
  geonode/monitoring/frontend/package.json
Labels: cla-signed

#12004 [Fixes #11977][Backport 4.1.x] B/R should only deal with data
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
Labels: cla-signed
