Repository GeoNode/geonode, pull requests merged in 2024-05, with the labels that each got.

#12211 Release 4.2.4
  docker-compose.yml
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#12212 Bump 4.2.x to dev
  docker-compose.yml
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#12230 [Fixes #12229] tinymce is not visible after the upgrade to v4
  requirements.txt
  setup.cfg
Labels: backport 4.3.x

#12231 [Backport 4.3.x] [Fixes #12229] tinymce is not visible after the upgrade to v4
  requirements.txt
  setup.cfg
Labels: cla-signed

#12233 [Fixes #12232] Increase the default value of CLIENT_RESULTS_LIMIT
  geonode/settings.py
Labels: cla-signed

#12236 [Fixes #12235] Retrieve the ows_url for ArcGIS resources from the harvester url
  geonode/harvesting/harvesters/arcgis.py
Labels: cla-signed

#12224 [Fixes #12223] Fix comment in Dockerfile
  Dockerfile
Labels: cla-signed

#12238 [Fixes #12237] Extend tests for permissions assignment
  geonode/resource/manager.py
  geonode/security/models.py
  geonode/security/tests.py
  geonode/security/utils.py
Labels: cla-signed, backport 4.3.x

#12251 [Fixes #12250] Add missing migration
  geonode/base/migrations/0091_alter_hierarchicalkeyword_slug.py
Labels: cla-signed, backport 4.3.x

#12254 [Fixes #12253] Improvements to the proxy view
  geonode/proxy/apps.py
  geonode/proxy/tests.py
  geonode/proxy/utils.py
  geonode/proxy/views.py
  geonode/services/models.py
  geonode/settings.py
  geonode/utils.py
Labels: cla-signed, backport 4.3.x

#12258 [Fixes #12255] Harvester is not deleted when its Service is deleted
  geonode/services/tests.py
  geonode/services/views.py
Labels: cla-signed, backport 4.3.x

#12262 [Fixes #12261] Current user is assigned as owner on geoapp update
  geonode/geoapps/api/serializers.py
  geonode/geoapps/api/tests.py
  geonode/geoapps/api/views.py
Labels: cla-signed, backport 4.3.x

#12281 Fixed tests counting 'Featured' words
  geonode/layers/tests.py
  geonode/maps/tests.py
Labels: cla-signed, backport 4.3.x

#12278 [Fixes #12277] Remove the MS catalog service configuration
  geonode/local_settings.py.geoserver.sample
  geonode/settings.py
Labels: cla-signed, backport 4.3.x

#12286 [Fixes #12285] Fix metadata page url inside the metadata detail page
  geonode/documents/templates/documents/document_metadata_detail.html
  geonode/geoapps/templates/apps/app_metadata_detail.html
  geonode/layers/templates/datasets/dataset_metadata_detail.html
  geonode/maps/templates/maps/map_metadata_detail.html
Labels: cla-signed, backport 4.3.x

#12288 Release 4.3.0
  CHANGELOG.md
  docker-compose-dev.yml
  docker-compose-test.yml
  docker-compose.yml
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#12289 Release 4.2.5
  docker-compose-test.yml
  docker-compose.yml
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#12292 Update dynamic-rest to 2.3.0
  requirements.txt
  setup.cfg
Labels: cla-signed, backport 4.3.x

#12295 Use published PyPi modules
  requirements.txt
  setup.cfg
Labels: cla-signed, backport 4.3.x

#12298 Bump to dev versions
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#12299 Bump to dev deps
  docker-compose.yml
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#12300 Fixes missing __init__.py inside people/api
  geonode/people/api/__init__.py
Labels: cla-signed, backport 4.3.x

#12303 Bump to dev deps
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed
