Repository GeoNode/geonode, pull requests merged in 2024-01, with the labels that each got.

#11802 [Fixes #11801] Upgrade to geoserver-restconfig 2.0.10
  requirements.txt
  setup.cfg
Labels: cla-signed

#11807 [Fixes #11806] Don't quote JAVA_OPTS
  .env.sample
Labels: cla-signed, backport 4.2.x

#11811 [Fixes #11808] Fix template variable for print base url
  .env.sample
Labels: cla-signed, backport 4.2.x

#11813 [Backport 4.2.x] [Fixes #11808] Fix template variable for print base url
  .env.sample
Labels: cla-signed

#11809 [Snyk] Security upgrade ipython from 7.34.0 to 8.10.0
  requirements_dev.txt
Labels: cla-signed

#11796 [Snyk] Security upgrade axios from 0.21.2 to 1.6.4
  geonode/monitoring/frontend/package.json
Labels: cla-signed

#11738 [Snyk] Fix for 1 vulnerabilities
  geonode/static/package.json
Labels: cla-signed

#11816 [Snyk] Fix for 6 vulnerabilities
  requirements.txt
  setup.cfg
Labels: cla-signed

#11720 [Snyk] Security upgrade node-sass from 4.14.1 to 7.0.2
  geonode/monitoring/frontend/package.json
Labels: cla-signed

#11719 [Snyk] Fix for 4 vulnerabilities
  geonode/static/package.json
Labels: cla-signed

#11559 [Snyk] Upgrade select2 from 4.0.10 to 4.0.13
  geonode/static/package.json
Labels: cla-signed

#11819 [Snyk] Security upgrade node-sass from 7.0.3 to 8.0.0
  geonode/monitoring/frontend/package.json
Labels: cla-signed

#11818 [Fixes #11817] Drop Nginx and Letsencrypt Dockerfiles
  docker-compose-dev.yml
  docker-compose-geoserver-server.yml
  docker-compose-test.yml
  docker-compose.yml
  scripts/docker/letsencrypt/Dockerfile
  scripts/docker/letsencrypt/README.md
  scripts/docker/letsencrypt/crontab
  scripts/docker/letsencrypt/docker-entrypoint.sh
  scripts/docker/nginx/Dockerfile
  scripts/docker/nginx/docker-autoreload.sh
  scripts/docker/nginx/docker-entrypoint.sh
  scripts/docker/nginx/geonode.conf.envsubst
  scripts/docker/nginx/nginx.conf.envsubst
  scripts/docker/nginx/nginx.https.available.conf.envsubst
Labels: cla-signed, backport 4.2.x

#11823 [Fixes #11822] Update Docker images to final tags
  docker-compose.yml
Labels: cla-signed, master

#11824 [Backport 4.2.x] [Fixes #11822] Update Docker tags for 4.2.x
  docker-compose.yml
Labels: cla-signed

#11826 [Fixes #11825] Use GeoNode 4.2.x Docker image
  docker-compose-test.yml
  docker-compose.yml
Labels: cla-signed

#11827 Release 4.2.0
  docker-compose-dev.yml
  docker-compose-test.yml
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#11828 Fixed docker image tags for test and dev compose files
  docker-compose-dev.yml
  docker-compose-test.yml
Labels: cla-signed

#11831 [Fixes #11830] Add long_description_content_type for Markdown
  setup.py
Labels: cla-signed, backport 4.2.x

#11835 [Backport 4.2.x] Remove docker-compose-dev reference to nginx script
  docker-compose-dev.yml
Labels: cla-signed

#11836 Update setup.cfg django-recaptcha to 4.0.0
  setup.cfg
Labels: cla-signed

#11854 Fix minimum version for the client
  setup.cfg
Labels: cla-signed

#11848 [Fixes #11847] Implement the option to hide resources from search and…
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/migrations/0089_resourcebase_advertised.py
  geonode/base/models.py
  geonode/documents/templates/layouts/doc_panels.html
  geonode/geoapps/templates/layouts/app_panels.html
  geonode/layers/templates/layouts/panels.html
  geonode/maps/templates/layouts/map_panels.html
Labels: cla-signed

#11873 [Backport 4.2.x] recreated .mo file for italian
  geonode/locale/it/LC_MESSAGES/django.mo
Labels: cla-signed

#11874 [Backport 4.2.x] [Fixes #11855] Reduce log level in donwload handler (#11856)
  geonode/layers/download_handler.py
Labels: cla-signed

#11875 Release 4.2.1
  docker-compose.yml
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed
