Repository GeoNode/geonode, pull requests merged in 2024-03, with the labels that each got.

#12020 Upgrade Remote Docker version for CircleCI
  .circleci/config.yml
Labels: cla-signed, backport 4.1.x, backport 4.2.x

#12007 [Fixes #11977] B/R should only deal with data
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
Labels: cla-signed

#12006 [Fixes #11977][Backport 4.2.x] B/R should only deal with data
  geonode/br/management/commands/backup.py
  geonode/br/management/commands/restore.py
Labels: cla-signed

#12011 [Fixes #11995 Implement POST and PATCH methods for the User API
  .circleci/config.yml
  geonode/base/api/permissions.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/people/tests.py
  geonode/people/views.py
Labels: cla-signed, API v2

#12028 [Fixes #11995] Implement the DELETE method for the User API
  geonode/base/api/tests.py
  geonode/people/tests.py
  geonode/people/utils.py
  geonode/people/views.py
  geonode/settings.py
Labels: cla-signed

#12043 Bump geoserver restconfig
  requirements.txt
  setup.cfg
Labels: cla-signed

#12040 [Fixes #12039] Upgrade to GeoServer 2.24.2
  docker-compose-test.yml
  docker-compose.yml
Labels: cla-signed

#12047 Fix to login rate limits configuration
  geonode/settings.py
Labels: cla-signed

#12045 [FIXES #12041] Fix bug in geonode/people that throws error when using…
  geonode/people/adapters.py
  geonode/people/profileextractors.py
Labels: cla-signed

#12048 [Backport 4.2.x] Upgrade to GeoServer 2.24.2
  docker-compose-test.yml
  docker-compose.yml
Labels: cla-signed

#12064 [Fixes #12063] Cannot clone map/geoapp with linked resources
  geonode/resource/manager.py
  geonode/resource/tests.py
Labels: cla-signed, backport 4.2.x

#12067 [Fixes #11995] Implement endpoint to transfer resources
  geonode/people/tests.py
  geonode/people/views.py
Labels: cla-signed

#12070 Fix upgraded image tags for GS 2.24.2
  docker-compose-dev.yml
  docker-compose.yml
Labels: cla-signed

#12069 [Fixes #12068] linked_resources API is slow
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/geoserver/signals.py
Labels: cla-signed

#12050 [Fixes #12049] Adapt the SLD and XML upload forms to the new progress API
  geonode/geoserver/context_processors.py
  geonode/layers/templates/datasets/dataset_metadata_upload.html
  geonode/layers/templates/datasets/dataset_style_upload.html
  geonode/settings.py
  geonode/static/geonode/js/upload/LayerInfo.js
Labels: cla-signed

#12066 [Issue 11995] Implement endpoint to unregister as a project manager
  geonode/people/tests.py
  geonode/people/views.py
Labels: cla-signed

#12071 [Fixes #12068][Backport 4.2.x] linked_resources API is slow
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/geoserver/signals.py
Labels: cla-signed

#12074 Bump dynamic rest library to v2.2.0
  requirements.txt
  setup.cfg
Labels: cla-signed

#12073 [Fixes #12046] Remove legacy forms and views for layer upload, replace and append
  geonode/base/api/mixins.py
  geonode/base/api/tests.py
  geonode/geoserver/helpers.py
  geonode/geoserver/tests/test_helpers.py
  geonode/geoserver/tests/test_server.py
  geonode/geoserver/urls.py
  geonode/geoserver/views.py
  geonode/layers/api/serializers.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/layers/forms.py
  geonode/layers/templates/datasets/dataset_append.html
  geonode/layers/templates/datasets/dataset_replace.html
  geonode/layers/templates/datasets/dataset_style_manage.html
  geonode/layers/tests.py
  geonode/layers/urls.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/security/middleware.py
  geonode/security/tests.py
  geonode/upload/api/tests.py
  geonode/upload/forms.py
  geonode/upload/upload_validators.py
  geonode/utils.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#12075 [Backport #12050] [Fixes #12049] Adapt the SLD and XML upload forms to the new progress API
  geonode/geoserver/context_processors.py
  geonode/layers/templates/datasets/dataset_metadata_upload.html
  geonode/layers/templates/datasets/dataset_style_upload.html
  geonode/settings.py
  geonode/static/geonode/js/upload/LayerInfo.js
Labels: cla-signed

#12093 Release 4.2.3
  docker-compose-dev.yml
  docker-compose-test.yml
  docker-compose.yml
  geonode/__init__.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#12094 [Fixes #12079] Fix resources API
  geonode/base/api/mixins.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/documents/api/serializers.py
  geonode/geoapps/api/serializers.py
  geonode/layers/api/serializers.py
  geonode/maps/api/serializers.py
Labels: cla-signed

#12100 [Fixes #12099] Fix API tests
  geonode/base/api/tests.py
Labels: cla-signed

#12092 [Fixes #12089] Errors in init entrypoint
  tasks.py
Labels: cla-signed

#12101 [Snyk] Security upgrade tinymce from 5.10.9 to 7.0.0
  geonode/static/package.json
Labels: cla-signed

#12103 [Fixes #12102] Replace azure account with microsoftgraph account
  geonode/settings.py
Labels: cla-signed

#12081 [Fixes #12076] Move the new users API under API module
  geonode/base/api/serializers.py
  geonode/base/api/views.py
  geonode/people/api/serializers.py
  geonode/people/api/urls.py
  geonode/people/api/views.py
  geonode/people/urls.py
  geonode/people/views.py
  geonode/urls.py
Labels: cla-signed
