Repository GeoNode/geonode, pull requests merged in 2024-07, with the labels that each got.

#12383 [Fixes #12382] Fix permsission on API for assets
  geonode/assets/views.py
Labels: cla-signed, master

#12385 [Fixes #12384] Uploaded thumbnail for 3dtiles resource is not saved
  geonode/thumbs/tests/test_unit.py
  geonode/thumbs/thumbnails.py
Labels: cla-signed, master

#12392 [Fixes #12361] Fix captcha field visualization in signup page
  geonode/people/forms.py
  geonode/people/views.py
  geonode/templates/account/signup.html
Labels: cla-signed, backport 4.3.x

#12394 [Fixes #12304] Move create_tile_layers to backup.sh
  geonode/br/management/commands/restore.py
Labels: cla-signed, backport 4.3.x

#12396 [Fixes #12369] Create a command to regenerate the XML metadata
  geonode/base/management/command_utils.py
  geonode/catalogue/management/__init__.py
  geonode/catalogue/management/commands/__init__.py
  geonode/catalogue/management/commands/regenerate_xml.py
  geonode/catalogue/models.py
Labels: cla-signed, backport 4.3.x

#12266 Add missing "m" in "Request permission"
  geonode/templates/owner_rights_request.html
Labels: cla-signed, backport 4.3.x

#12275 Add test coverage for simple resourcebase
  geonode/base/api/tests.py
Labels: cla-signed

#12414 [Fixes #12413] Group filter autocomplete does not work
  geonode/facets/providers/group.py
  geonode/facets/tests.py
Labels: cla-signed, backport 4.3.x

#12437 [Fixes #12436] Linked resources are not present in maps api payload
  geonode/base/api/serializers.py
Labels: cla-signed, backport 4.3.x

#12425 [Fixes #12412] Download whole asset
  .github/workflows/flake8.yml
  geonode/assets/local.py
  geonode/assets/tests.py
  geonode/proxy/tests.py
  geonode/proxy/views.py
  geonode/storage/data_retriever.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#12442 [Fixes #12441] GS layers metadata update
  geonode/geoserver/helpers.py
  geonode/geoserver/management/commands/sync_geonode_datasets.py
  geonode/layers/api/views.py
Labels: cla-signed, backport 4.3.x

#12444 Uncomment Docker build
  docker-compose.yml
Labels: cla-signed

#12459 [Fixes #12435] Improve resource serializer for Links - Assets
  geonode/base/api/serializers.py
Labels: cla-signed

#12457 [Fixes #12445] Possible missing fields when parsing temporalExtent
  geonode/layers/metadata.py
Labels: cla-signed, backport 4.3.x
