Repository GeoNode/geonode, pull requests merged in 2025-08, with the labels that each got.

#13433 [Fixes #13432] Do not switch to group detail when adding or removing members
  geonode/groups/views.py
Labels: cla-signed

#13429 [Fixes #13425] Make upload procedures use directly the AssetHandler
  geonode/assets/local.py
  geonode/storage/data_retriever.py
  geonode/storage/manager.py
  geonode/storage/settings.py
  geonode/storage/utils.py
  geonode/upload/api/tests.py
  geonode/upload/api/views.py
  geonode/upload/celery_tasks.py
  geonode/upload/datastore.py
  geonode/upload/handlers/base.py
  geonode/upload/handlers/common/raster.py
  geonode/upload/handlers/common/vector.py
  geonode/upload/orchestrator.py
  geonode/upload/tests/unit/test_task.py
Labels: cla-signed, master

#13453 [Fixes #13368] Download ISO metadata directly from Resource metadata_xml
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed

#13458 [Fixes #13364] Update of Backport of Base RestrictionType Fixture Fixed (#13404)
  geonode/base/migrations/0094_fix_otherrestrictions_codetype.py
Labels: cla-signed, 4.4.x

#13352 [Fixes #13361] Implementation of Vector Dataset Inserts / Updates
  .env.sample
  .env_dev
  .env_local
  .env_test
  geonode/settings.py
  geonode/upload/api/exceptions.py
  geonode/upload/api/serializer.py
  geonode/upload/api/views.py
  geonode/upload/celery_tasks.py
  geonode/upload/datastore.py
  geonode/upload/handlers/common/tests_vector.py
  geonode/upload/handlers/common/vector.py
  geonode/upload/handlers/csv/handler.py
  geonode/upload/handlers/shapefile/handler.py
  geonode/upload/handlers/sld/handler.py
  geonode/upload/handlers/xml/handler.py
  geonode/upload/handlers/xml/serializer.py
  geonode/upload/orchestrator.py
  geonode/upload/tests/end2end/test_end2end.py
  geonode/upload/tests/end2end/test_end2end_copy.py
  geonode/upload/tests/end2end/test_env2end_upsert.py
  geonode/upload/tests/fixture/upsert/original.dbf
  geonode/upload/tests/fixture/upsert/original.prj
  geonode/upload/tests/fixture/upsert/original.shp
  geonode/upload/tests/fixture/upsert/original.shx
  geonode/upload/tests/fixture/upsert/upsert.dbf
  geonode/upload/tests/fixture/upsert/upsert.prj
  geonode/upload/tests/fixture/upsert/upsert.shp
  geonode/upload/tests/fixture/upsert/upsert.shx
  geonode/upload/tests/unit/test_models.py
  geonode/upload/tests/unit/test_task.py
  geonode/upload/utils.py
Labels: cla-signed

#13460 Revert "[Fixes #13361] Implementation of Vector Dataset Inserts / Updates"
  .env.sample
  .env_dev
  .env_local
  .env_test
  geonode/settings.py
  geonode/upload/api/exceptions.py
  geonode/upload/api/serializer.py
  geonode/upload/api/views.py
  geonode/upload/celery_tasks.py
  geonode/upload/datastore.py
  geonode/upload/handlers/common/tests_vector.py
  geonode/upload/handlers/common/vector.py
  geonode/upload/handlers/csv/handler.py
  geonode/upload/handlers/shapefile/handler.py
  geonode/upload/handlers/sld/handler.py
  geonode/upload/handlers/xml/handler.py
  geonode/upload/handlers/xml/serializer.py
  geonode/upload/orchestrator.py
  geonode/upload/tests/end2end/test_end2end.py
  geonode/upload/tests/end2end/test_end2end_copy.py
  geonode/upload/tests/end2end/test_env2end_upsert.py
  geonode/upload/tests/fixture/upsert/original.dbf
  geonode/upload/tests/fixture/upsert/original.prj
  geonode/upload/tests/fixture/upsert/original.shp
  geonode/upload/tests/fixture/upsert/original.shx
  geonode/upload/tests/fixture/upsert/upsert.dbf
  geonode/upload/tests/fixture/upsert/upsert.prj
  geonode/upload/tests/fixture/upsert/upsert.shp
  geonode/upload/tests/fixture/upsert/upsert.shx
  geonode/upload/tests/unit/test_models.py
  geonode/upload/tests/unit/test_task.py
  geonode/upload/utils.py
Labels: cla-signed
