Repository GeoNode/geonode, pull requests merged in 2025-03, with the labels that each got.

#12852 [Backport Fixes #12828] New remote datasets are not registered inside…
  geonode/proxy/utils.py
Labels: cla-signed

#12964 [Fixes #12956] Metadata editor: review mandatory flags
  geonode/metadata/schemas/base.json
Labels: cla-signed

#12987 [Fixes #12983] Metadata manager: add pre- and post- save hooks
  geonode/metadata/handlers/abstract.py
  geonode/metadata/manager.py
Labels: cla-signed

#12989 [Fixes #12988] Metadata editor: fix jsonschema caching mechanism
  geonode/metadata/manager.py
  geonode/metadata/signals.py
  geonode/metadata/tests/tests.py
Labels: cla-signed

#12990 [Fixes #12957] Metadata editor: customizable title and description labels
  geonode/metadata/handlers/abstract.py
  geonode/metadata/handlers/base.py
  geonode/metadata/handlers/sparse.py
  geonode/metadata/i18n.py
  geonode/metadata/settings.py
Labels: cla-signed, enhancement, master, metadata

#13000 [Fixes #12749] Sanitize uploaded layers that start with a numeric cha…
  geonode/upload/handlers/base.py
  geonode/upload/handlers/tests.py
Labels: cla-signed

#12999 [Fixes #12951] CSV file preview fails
  geonode/documents/forms.py
  geonode/documents/tests.py
  geonode/documents/tests/data/test.CSV
  geonode/documents/views.py
  geonode/resource/utils.py
Labels: cla-signed, backport 4.4.x

#13004 [Fixes #12998] Metadata editor: improve return info when updating data
  geonode/metadata/api/views.py
  geonode/metadata/i18n.py
  geonode/metadata/tests/tests.py
Labels: cla-signed, enhancement, master, metadata

#13029 Fix master build
  geonode/metadata/tests/tests.py
Labels: cla-signed
