Repository GeoNode/geonode, pull requests merged in 2025-07, with the labels that each got.

#13322 [Fixes #13320] Upgrade to postgis 15-3.5
  docker-compose-dev.yml
  docker-compose-test.yml
  docker-compose.yml
Labels: cla-signed, backport 4.4.x

#13319 [Fixes #13318] Adapt Harvester tasks expiration dynamically
  geonode/harvesting/tasks.py
  geonode/harvesting/tests/test_tasks.py
  geonode/settings.py
Labels: cla-signed, enhancement, backport 4.4.x

#13329 [Fixes #13327] Metadata editor: improve label customization
  geonode/metadata/handlers/abstract.py
  geonode/metadata/handlers/base.py
  geonode/metadata/handlers/contact.py
  geonode/metadata/handlers/doi.py
  geonode/metadata/handlers/hkeyword.py
  geonode/metadata/handlers/region.py
  geonode/metadata/handlers/sparse.py
  geonode/metadata/handlers/thesaurus.py
  geonode/metadata/i18n.py
  geonode/metadata/tests/test_handlers.py
  geonode/metadata/tests/test_i18n.py
Labels: cla-signed

#13349 [Fixes #13343] POST requests throw crsf error when ENABLE_APIKEY_LOGIN is active
  geonode/assets/views.py
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/auth.py
  geonode/documents/api/views.py
  geonode/facets/views.py
  geonode/geoapps/api/views.py
  geonode/harvesting/api/views.py
  geonode/layers/api/tests.py
  geonode/layers/api/views.py
  geonode/maps/api/views.py
  geonode/metadata/api/views.py
  geonode/people/api/views.py
  geonode/resource/api/views.py
  geonode/security/middleware.py
  geonode/security/tests.py
  geonode/settings.py
  geonode/upload/api/tests_old.py
  geonode/upload/api/views.py
Labels: cla-signed, backport 4.4.x

#13363 [Fixes #13362] Use OIDC Server from oauthlib
  geonode/security/oauth2_grant_types.py
  geonode/security/oauth2_servers.py
  geonode/security/oauth2_validators.py
  geonode/settings.py
Labels: cla-signed

#13370 [Fixes #13262] Memcached container not starting upon reboot
  docker-compose-test.yml
  docker-compose.yml
Labels: cla-signed, backport 4.4.x

#13390 [Fixes #13389] Metadata editor: fix capitalization
  geonode/metadata/schemas/base.json
Labels: minor, cla-signed, metadata
