Repository GeoNode/geonode, pull requests merged in 2025-02, with the labels that each got.

#12853 [Fixes 12766] New fixes regarding the Timeseries API
  geonode/layers/api/serializers.py
  geonode/layers/api/views.py
  geonode/upload/handlers/common/vector.py
Labels: cla-signed

#12873 [Fixes #12872] Improvements to GeoNode OpenID for Entra ID
  geonode/people/adapters.py
  geonode/settings.py
Labels: cla-signed, backport 4.4.x

#12454 [Fixes #12880] Asset download doesn't work with 3D Tiles
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/layers/download_handler.py
Labels: cla-signed, backport 4.4.x

#12882 Revert "[Fixes #12880] Asset download doesn't work with 3D Tiles"
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/layers/download_handler.py
Labels: cla-signed

#12878 [Fixes #12876] Removal of tests from root
  test.sh
  test_api_v2.sh
  test_csw.sh
  test_dev.sh
  test_integration.sh
  test_oauth2.sh
  test_upload.sh
Labels: cla-signed

#12884 [Fixes #12883] Error in passing params from metadata parsers to storers
  geonode/resource/manager.py
  geonode/resource/tests.py
Labels: cla-signed

#12905 [Fixes #12904] Include advertised in the list editable fields
  geonode/documents/admin.py
Labels: cla-signed, backport 4.4.x

#12922 [Fixes #12921] Fix Layers admin interface raise error
  geonode/base/forms.py
  geonode/documents/admin.py
  geonode/geoapps/admin.py
  geonode/layers/admin.py
  geonode/maps/admin.py
Labels: cla-signed, master

#12926 Bump to geoserver-restconfig 2.0.13
  requirements.txt
  setup.cfg
Labels: cla-signed, backport 4.4.x

#12714 [Fixes #12713] Permissions Registry and permissions handler
  geonode/base/api/permissions.py
  geonode/base/api/serializers.py
  geonode/base/api/tests.py
  geonode/base/views.py
  geonode/documents/tests.py
  geonode/geoapps/views.py
  geonode/geoserver/security.py
  geonode/geoserver/tests/integration.py
  geonode/groups/tests.py
  geonode/layers/tests.py
  geonode/layers/utils.py
  geonode/layers/views.py
  geonode/people/tests.py
  geonode/resource/manager.py
  geonode/security/apps.py
  geonode/security/handlers.py
  geonode/security/models.py
  geonode/security/registry.py
  geonode/security/tests.py
  geonode/security/utils.py
  geonode/security/views.py
  geonode/services/views.py
  geonode/settings.py
  geonode/upload/tests/end2end/integration.py
  geonode/upload/tests/end2end/test_end2end.py
  geonode/upload/tests/integration.py
Labels: cla-signed
