Repository GeoNode/geonode, pull requests merged in 2025-04, with the labels that each got.

#13033 [FIXIES 13031] Fixing bug related with the thumbnail's update on a map
  geonode/base/api/views.py
  geonode/thumbs/thumbnails.py
Labels: cla-signed, bug, backport 4.4.x

#13047 [Fixes #13046] Fixing the layer's serializer which dynamically creates the featureino (For GeoNode 4.4.x)
  docker-compose-test.yml
  docker-compose.yml
  geonode/layers/api/serializers.py
Labels: cla-signed

#12592 [Fixes #12591] Migration documents.0037_delete_documentresourcelink may fail
  geonode/documents/migrations/0037_delete_documentresourcelink.py
Labels: cla-signed, backport 4.2.x, backport 4.3.x, backport 4.4.x

#13045 [FIXIES 13044] Remote WMS dataset store is not correct if uploaded vi…
  geonode/upload/handlers/common/remote.py
  geonode/upload/handlers/remote/wms.py
Labels: cla-signed

#13056 [Fixes #13055] Limit the list of punctuations used inside create-envfile.py
  create-envfile.py
Labels: cla-signed, backport 4.4.x

#13066 [Fixes #13065] Upgrade Django version to 4.2.17 on GeoNode 4.4.x
  requirements.txt
Labels: cla-signed

#13058 [Fixies #13057] Removing Twisted library from the dependencies and the related code
  geonode/tests/suite/base.py
  geonode/tests/suite/runner.py
  requirements.txt
  requirements_tests.txt
  setup.cfg
Labels: dependencies, cla-signed

#13062 [Backport 4.4.x][FIXIES #13057] Removing Twisted library from the dependencies and the related code
  geonode/tests/suite/base.py
  geonode/tests/suite/runner.py
  requirements.txt
  requirements_tests.txt
  setup.cfg
Labels: dependencies, cla-signed

#13082 [Fixes #13067] Thesaurus: improve management commands
  geonode/base/admin.py
  geonode/base/management/command_utils.py
  geonode/base/management/commands/dump_thesaurus.py
  geonode/base/management/commands/load_thesaurus.py
  geonode/base/management/commands/thesaurus.py
  geonode/base/management/commands/thesaurus_subcommands/__init__.py
  geonode/base/management/commands/thesaurus_subcommands/dump.py
  geonode/base/management/commands/thesaurus_subcommands/list.py
  geonode/base/management/commands/thesaurus_subcommands/load.py
Labels: cla-signed

#13060 [Fixes #13087] Remove flower - this comes from old monitoring solution
  celery.sh
  scripts/docker/base/ubuntu/Dockerfile
Labels: dependencies, backport 4.4.x

#13013 [Fixes #13012] Use global UUID online resource inside ISO Metadata
  geonode/catalogue/templates/catalogue/full_metadata.xml
Labels: cla-signed, backport 4.4.x

#13091 [Fixes #13090] Syncing PIP upgrade with setup.cfg
  setup.cfg
Labels: dependencies, cla-signed, backport 4.4.x

#13086 [FIXIES #13085] Upgrade Cryptography and remove pyOpenSSL
  requirements.txt
  setup.cfg
Labels: dependencies, cla-signed, backport 4.4.x

#13032 [FIXIES #13030] Endpoint to delete a resource's thumbnail
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: feature, cla-signed

#12997 [Fixes #12996] Allow changing ownership of a single resource
  geonode/base/api/views.py
  geonode/people/api/views.py
  geonode/people/tests.py
Labels: cla-signed, master

#13101 [Fixes #13100] Fixing permissions bug of the delete_thumbnail endpoint
  geonode/base/api/tests.py
  geonode/base/api/views.py
Labels: cla-signed, bug

#13014 [Fixes #13009] Implement Basic Auth support for Remote Services
  geonode/harvesting/harvesters/wms.py
  geonode/services/forms.py
  geonode/services/migrations/0055_service_password_service_username.py
  geonode/services/models.py
  geonode/services/serviceprocessors/__init__.py
  geonode/services/serviceprocessors/arcgis.py
  geonode/services/serviceprocessors/wms.py
  geonode/services/templates/services/service_detail.html
  geonode/services/templates/services/service_list.html
  geonode/services/templates/services/service_register.html
  geonode/thumbs/thumbnails.py
  geonode/thumbs/utils.py
Labels: cla-signed

#13027 [Fixes #13011] Return edit data permissions for remote layers
  geonode/security/models.py
  geonode/security/permissions.py
  geonode/security/tests.py
Labels: cla-signed

#13104 [Fixes #13102] Define a specific version of the Wheel package
  scripts/docker/base/ubuntu/Dockerfile
Labels: dependencies, cla-signed, backport 4.4.x

#13028 [Fixes #13010] Add describe layer to the WMS harvester
  geonode/harvesting/harvesters/wms.py
  geonode/services/models.py
Labels: cla-signed

#13103 Update test_end2end.py
  geonode/upload/tests/end2end/test_end2end.py
Labels: cla-signed

#13109 [Fixes #13010] Create WFS Links for WMS remote layers that have WFS support
  geonode/harvesting/harvesters/wms.py
Labels: cla-signed

#13083 [Fixes #13043] Metadata editor: allow customization of error messages
  geonode/metadata/api/views.py
  geonode/metadata/handlers/abstract.py
  geonode/metadata/handlers/base.py
  geonode/metadata/handlers/contact.py
  geonode/metadata/handlers/sparse.py
  geonode/metadata/i18n.py
  geonode/metadata/manager.py
  geonode/metadata/signals.py
  geonode/metadata/tests/test_handlers.py
  geonode/metadata/tests/tests.py
Labels: cla-signed, enhancement

#13121 Fix download perms for assets
  geonode/assets/tests.py
  geonode/assets/utils.py
  geonode/assets/views.py
Labels: cla-signed

#13135 [Fixes #13133] Removing ingest() method and the related code from GeoNode 4.4.x
  geonode/base/api/views.py
  geonode/geoserver/manager.py
  geonode/harvesting/harvesters/base.py
  geonode/resource/manager.py
  geonode/resource/tests.py
  geonode/thumbs/tests/test_integration.py
Labels: dependencies, cla-signed, enhancement

#13137 [Fixes #13133] Removing ingest() method and the related code from Geo…
  geonode/base/api/views.py
  geonode/geoserver/manager.py
  geonode/harvesting/harvesters/base.py
  geonode/resource/manager.py
  geonode/resource/tests.py
  geonode/thumbs/tests/test_integration.py
Labels: cla-signed
