Repository GeoNode/geonode, pull requests merged in 2025-09, with the labels that each got.

#13483 Upgrade to geoserver-restconfig 2.0.15
  requirements.txt
  setup.cfg
Labels: cla-signed

#13396 [Fixes #13378] Implement POST API for asset creation.
  geonode/api/tests.py
  geonode/assets/serializers.py
  geonode/assets/tests.py
  geonode/assets/utils.py
  geonode/base/api/views.py
  geonode/settings.py
  geonode/upload/migrations/0052_asset_upload_size.py
  geonode/upload/uploadhandler.py
Labels: cla-signed, master

#13481 [Fixes #13462] Update set_attributes_from_geoserver to use authenticated calls
  geonode/geoserver/helpers.py
Labels: cla-signed, master

#13482 [Fixes #13478] Enhancement / bugfix of upsert functionality
  .env_dev
  geonode/settings.py
  geonode/upload/celery_tasks.py
  geonode/upload/handlers/common/vector.py
  geonode/upload/handlers/shapefile/handler.py
  geonode/upload/tests/end2end/test_env2end_upsert.py
  geonode/upload/tests/fixture/upsert/original.dbf
  geonode/upload/tests/fixture/upsert/original.json
  geonode/upload/tests/fixture/upsert/original.prj
  geonode/upload/tests/fixture/upsert/original.shp
  geonode/upload/tests/fixture/upsert/original.shx
  geonode/upload/tests/fixture/upsert/upsert.dbf
  geonode/upload/tests/fixture/upsert/upsert.json
  geonode/upload/tests/fixture/upsert/upsert.prj
  geonode/upload/tests/fixture/upsert/upsert.shp
  geonode/upload/tests/fixture/upsert/upsert.shx
Labels: cla-signed, master

#13455 [Fixes #13454] Add 'select all' actions to the `should_be_harvested` property in the `Harvestable resources` admin section
  geonode/harvesting/admin.py
Labels: cla-signed, enhancement

#13509 [Fixes #13508] Missing Migration in Master Added
  geonode/harvesting/migrations/0050_alter_harvester_harvester_type.py
  geonode/people/migrations/0037_alter_profile_keywords.py
Labels: cla-signed

#13518 [Fixes #13514] Extended the asset link serializer to inform the client whether an asset can be deleted or not
  geonode/assets/serializers.py
  geonode/assets/utils.py
  geonode/base/api/serializers.py
  geonode/base/tests.py
Labels: cla-signed

#13535 [Fixes #13520] Improved Error Robustness for special characters and whitespaces in filenames and attribute tables
  geonode/upload/handlers/base.py
  geonode/upload/handlers/common/tests_vector.py
  geonode/upload/handlers/common/vector.py
  geonode/upload/handlers/tests.py
  geonode/upload/templates/upload/vrt_template.xml
  geonode/upload/utils.py
Labels: cla-signed

#13542 [Fixes #13451] Upsert improvments / refactor
  .env_dev
  geonode/settings.py
  geonode/upload/celery_tasks.py
  geonode/upload/handlers/base.py
  geonode/upload/handlers/common/tests_vector.py
  geonode/upload/handlers/common/vector.py
  geonode/upload/tests/end2end/test_env2end_upsert.py
Labels: cla-signed
