Repository GeoNode/geonode, pull requests merged in 2025-05, with the labels that each got.

#13141 [Fixes #13113] Fixing multiple Keyerror logs when DEBUG=False
  geonode/services/serviceprocessors/wms.py
  geonode/services/tests.py
  geonode/urls.py
  geonode/views.py
Labels: cla-signed, investigation, master, 4.4.x

#13145 [Fixes #13143] Adding default blank argument to the username and password fields of the Service model
  geonode/services/migrations/0056_alter_service_password_alter_service_username.py
  geonode/services/models.py
Labels: cla-signed, investigation, master, bug

#13151 [Fixes #13150] Drop stale account settings
  .env.sample
  .env_dev
  .env_local
  .env_test
Labels: cla-signed, master

#13153 [Fixes #13152] Removing the method resource_service_ingest() from master
  geonode/base/api/views.py
Labels: cla-signed, master

#13142 [Fixes #13144] Improve Sparse field handler
  geonode/metadata/handlers/doi.py
  geonode/metadata/handlers/sparse.py
Labels: cla-signed, enhancement

#13132 [Fixes #13107] Removing unused and inderect dependencies from requirements.txt and setup.cfg
  requirements.txt
  requirements_dev.txt
  requirements_tests.txt
  setup.cfg
Labels: dependencies, cla-signed

#13161 Update requirements.txt
  requirements.txt
Labels: cla-signed

#13174 Fix test suite
  geonode/groups/tests.py
Labels: cla-signed

#13185 [Fixes #13184] Ensure resource is in dirty state during clone and delete
  geonode/resource/manager.py
  geonode/upload/celery_tasks.py
Labels: cla-signed

#13140 [Fixes #12901] Metadata: Enforcing group permission on save
  geonode/base/api/serializers.py
  geonode/metadata/api/views.py
  geonode/metadata/handlers/group.py
  geonode/metadata/manager.py
  geonode/metadata/tests/test_handlers.py
  geonode/metadata/tests/tests.py
Labels: cla-signed, enhancement, master

#13179 [Fixes #13159] Removing change ownership support from the `/permissions` endpoint
  geonode/base/api/views.py
Labels: cla-signed, enhancement

#13160 Fixes #13111: drop messaging service
  .circleci/config.yml
  geonode/base/views.py
  geonode/layers/models.py
  geonode/messaging/__init__.py
  geonode/messaging/apps.py
  geonode/messaging/consumer.py
  geonode/messaging/management/__init__.py
  geonode/messaging/management/commands/__init__.py
  geonode/messaging/management/commands/purgemessaging.py
  geonode/messaging/management/commands/runmessaging.py
  geonode/messaging/models.py
  geonode/messaging/notifications.py
  geonode/messaging/producer.py
  geonode/messaging/queues.py
  geonode/messaging/tests.py
  geonode/messaging/urls.py
  geonode/messaging/views.py
  geonode/people/templates/people/profile_detail.html
  geonode/settings.py
  geonode/templates/invitations/email/email_invite_message.html
  geonode/templates/invitations/email/email_invite_message.txt
  geonode/templates/user_messages/_field_error_block.html
  geonode/templates/user_messages/_field_group_header.html
  geonode/templates/user_messages/_message_snippet.html
  geonode/templates/user_messages/inbox.html
  geonode/templates/user_messages/message_create.html
  geonode/templates/user_messages/thread_detail.html
  geonode/tests/smoke.py
  geonode/tests/test_message_notifications.py
  geonode/urls.py
  requirements.txt
  setup.cfg
Labels: cla-signed

#13176 [Fixes #13166] Clean up the base.html
  geonode/static/geonode/js/utils/thumbnail.js
  geonode/templates/base.html
  geonode/templates/metadata_base.html
Labels: cla-signed, enhancement

#13191 [Fixes #13190] Make the Thesaurus autocomplete referenceable by identifier
  geonode/metadata/api/views.py
Labels: cla-signed

#13112 [Fixies #12540] PyCSW upgrade to version 3
  geonode/catalogue/backends/pycsw_local.py
  geonode/catalogue/backends/pycsw_local_mappings.py
  geonode/catalogue/tests.py
  geonode/catalogue/views.py
  geonode/layers/views.py
  geonode/local_settings.py.geoserver.sample
  geonode/settings.py
  geonode/views.py
  requirements.txt
  setup.cfg
Labels: cla-signed, enhancement

#13214 [Fixes #13213] Do not copy the featured flag value when copying a resource
  geonode/base/api/tests.py
  geonode/base/api/views.py
  geonode/base/urls.py
  geonode/base/views.py
  geonode/resource/manager.py
  geonode/upload/celery_tasks.py
Labels: cla-signed, enhancement, master
